Repository pyro-ppl/pyro, pull requests merged in 2018-07, with the labels that each got.

#1203 Welford's Scheme Implementation
  pyro/ops/welford.py
  tests/ops/test_welford.py
Labels: awaiting review, discussion

#1211 add LSH to contrib.tracking
  docs/source/contrib.tracking.rst
  pyro/contrib/tracking/hashing.py
  tests/contrib/tracking/test_hashing.py
Labels: awaiting review

#1218 Fix elbo links in docs
  pyro/infer/elbo.py
  pyro/infer/svi.py
Labels: awaiting review, documentation, easy

#1189 add MixtureOfDiagNormalsSharedCovariance to pyro
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/diag_normal_mixture_shared_cov.py
  tests/distributions/test_gaussian_mixtures.py
Labels: awaiting review

#1219 Implement pyro.contrib.tracking.merge_points()
  pyro/contrib/tracking/hashing.py
  tests/contrib/tracking/test_hashing.py
Labels: awaiting review

#1220 Implement VonMises3D distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/binomial.py
  pyro/distributions/delta.py
  pyro/distributions/torch.py
  pyro/distributions/von_mises.py
  pyro/distributions/von_mises_3d.py
  tests/distributions/test_von_mises.py
Labels: awaiting review, bug, enhancement

#1214 Implement renyi elbo
  docs/source/inference_algos.rst
  pyro/distributions/util.py
  pyro/infer/__init__.py
  pyro/infer/renyi_elbo.py
  pyro/infer/trace_elbo.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/tracegraph_elbo.py
  tests/infer/test_inference.py
Labels: discussion

#1224 Continuous EIG estimation: first step and example
  docs/source/contrib.oed.rst
  docs/source/index.rst
  examples/contrib/oed/ab_test.py
  pyro/contrib/__init__.py
  pyro/contrib/autoguide/__init__.py
  pyro/contrib/oed/__init__.py
  pyro/contrib/oed/eig.py
  pyro/contrib/oed/search.py
  pyro/distributions/torch_distribution.py
  tests/contrib/autoguide/test_mean_field_guide_entropy.py
  tests/contrib/oed/test_eig.py
  tests/distributions/test_distributions.py
  tests/distributions/test_reshape.py
  tests/test_examples.py
Labels: awaiting review

#1228 Numerically stable log slice computation in NUTS
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
Labels: awaiting review, easy

#1229 Add RSA tutorials
  tutorial/source/RSA-hyperbole.ipynb
  tutorial/source/RSA-implicature.ipynb
  tutorial/source/search_inference.py
Labels: Anchor examples, awaiting review

#1233 Scrub tutorials to ensure uniform metadata
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/bo.ipynb
  tutorial/source/dmm.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/intro_part_i.ipynb
  tutorial/source/intro_part_ii.ipynb
  tutorial/source/ss-vae.ipynb
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_ii.ipynb
  tutorial/source/svi_part_iii.ipynb
  tutorial/source/tensor_shapes.ipynb
  tutorial/source/tracking_1d.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review, easy

#1230 Consolidate *ELBO._get_trace
  pyro/infer/enum.py
  pyro/infer/renyi_elbo.py
  pyro/infer/trace_elbo.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/util.py
Labels: awaiting review

#1236 Fix bug in dist.Delta.expand() type
  pyro/distributions/delta.py
  tests/distributions/test_delta.py
Labels: awaiting review, bug, easy

#1231 Make SVI a TracePosterior subclass
  examples/contrib/oed/ab_test.py
  pyro/contrib/oed/eig.py
  pyro/infer/svi.py
  tests/contrib/oed/test_eig.py
  tests/infer/test_inference.py
Labels: awaiting review, refactor

#1239 Refactor to use generic newton solver in pyro.optim.multi
  pyro/optim/multi.py
  tests/optim/test_multi.py
Labels: awaiting review, refactor

#1245 increase stacklevel of warnings in `warn_if_nan` and `warn_if_inf`
  pyro/util.py
Labels: easy

#1243 Implement TraceEnum_ELBO.differentiable_loss() method
  pyro/infer/traceenum_elbo.py
  tests/infer/test_enum.py
Labels: awaiting review, enhancement

#1240 Expose distribution from `sample_latent` in autoguide
  pyro/contrib/autoguide/__init__.py
Labels: awaiting review

#1247 Add examples of composing inference algorithms (BP, EM, SVI, Adam, Newton)
  pyro/optim/multi.py
  tests/contrib/tracking/test_em.py
Labels: awaiting review, discussion

#1248 Add coercion and overlap checking to MixedMultiOptimizer constructor
  pyro/optim/multi.py
  tests/contrib/tracking/test_em.py
  tests/optim/test_multi.py
Labels: awaiting review, easy

#1251 Refactor Dice class to add an .expected_cost() operator
  pyro/infer/traceenum_elbo.py
  pyro/infer/util.py
Labels: awaiting review, easy

#1254 add vectorized test for BernoulliBeta
  tests/infer/test_inference.py
Labels: easy

#1259 add regex search support for param store
  pyro/params/param_store.py
Labels: awaiting review, easy

#1255 add GaussianScaleMixture distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/diag_normal_mixture_shared_cov.py
  pyro/distributions/gaussian_scale_mixture.py
  tests/distributions/test_gaussian_mixtures.py
Labels: awaiting review

#1252 Add differentiable_loss to Trace_ELBO
  pyro/infer/trace_elbo.py
  tests/infer/test_gradient.py
Labels: awaiting review

#1264 Implement MaskedMixture distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/lowrank_mvn.py
  pyro/distributions/mixture.py
  pyro/distributions/torch.py
  pyro/distributions/torch_distribution.py
  tests/contrib/tracking/test_em.py
  tests/distributions/test_mixture.py
Labels: awaiting review, enhancement

#1274 Use torch.logsumexp when available
  examples/baseball.py
  examples/rsa/search_inference.py
  pyro/distributions/empirical.py
  pyro/distributions/util.py
  pyro/infer/renyi_elbo.py
  tests/distributions/test_mask.py
  tutorial/source/search_inference.py
Labels: awaiting review

#1237 Implement Laplace approximation
  pyro/contrib/autoguide/__init__.py
  tests/contrib/autoguide/test_advi.py
  tests/contrib/autoguide/test_hessian.py
  tests/contrib/autoguide/test_inference.py
Labels: awaiting review, enhancement

#1275 Rename Laplace approximation
  docs/source/contrib.autoguide.rst
  pyro/contrib/autoguide/__init__.py
  tests/contrib/autoguide/test_advi.py
  tests/contrib/autoguide/test_inference.py
Labels: awaiting review, easy

#1266 Added flag to allow loading of CUDA-trained parameters to CPU.
  pyro/params/param_store.py
Labels: awaiting response

#1276 Update JIT usage to PyTorch 0.4.1
  docs/source/primitives.rst
  examples/air/modules.py
  pyro/distributions/torch_patch.py
  pyro/infer/trace_elbo.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/ops/jit.py
  tests/infer/test_gradient.py
  tests/infer/test_jit.py
Labels: awaiting review

#1277 Fix failing CUDA tests on dev
  tests/common.py
  tests/conftest.py
  tests/distributions/test_gaussian_mixtures.py
  tests/ops/test_welford.py
  tests/optim/test_optim.py
Labels: awaiting review

#1249 Marginalize out discrete latent sites in HMC via enumeration
  pyro/distributions/util.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  pyro/infer/mcmc/util.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
  tests/infer/mcmc/test_valid_models.py
Labels: awaiting review
