Repository pyro-ppl/pyro, pull requests merged in 2018-05, with the labels that each got.

#1110 rework bo tutorial
  tutorial/source/bo.ipynb
Labels: awaiting review

#1112 Fix a tiny bug when rendering gp tutorial
  tutorial/source/gp.ipynb
Labels: easy

#1114 Update to NUTS/HMC docstrings
  docs/source/mcmc.rst
  docs/source/pyro.infer.mcmc.txt
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
Labels: awaiting review, documentation

#1117 Relax check for gp kernel active_dims to allow overlap
  pyro/contrib/gp/kernels/kernel.py
  tests/contrib/gp/test_kernels.py
Labels: awaiting review, easy

#1120 Implement TorchDistribution.expand()
  docs/source/distributions.rst
  pyro/distributions/binomial.py
  pyro/distributions/delta.py
  pyro/distributions/half_cauchy.py
  pyro/distributions/lowrank_mvn.py
  pyro/distributions/torch.py
  pyro/distributions/torch_distribution.py
  pyro/distributions/von_mises.py
  tests/distributions/test_distributions.py
Labels: awaiting review

#1123 Use momentum of the same size as the unconstrained sample site in HMC
  pyro/infer/mcmc/hmc.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
Labels: awaiting review

#1122 Expose contrib.gp classes in sphinx toctree
  docs/source/contrib.gp.rst
  docs/source/contrib.rst
  docs/source/index.rst
  pyro/contrib/__init__.py
  pyro/contrib/gp/kernels/__init__.py
  pyro/contrib/gp/likelihoods/__init__.py
  pyro/contrib/gp/likelihoods/binary.py
  pyro/contrib/gp/likelihoods/gaussian.py
  pyro/contrib/gp/likelihoods/multi_class.py
  pyro/contrib/gp/likelihoods/poisson.py
Labels: awaiting review, documentation

#1109 Support torch.jit in ELBO implementations
  docs/source/inference_algos.rst
  pyro/infer/__init__.py
  pyro/infer/trace_elbo.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/tracegraph_elbo.py
  tests/infer/test_gradient.py
  tests/infer/test_inference.py
  tests/infer/test_jit.py
  tests/integration_tests/test_conjugate_gaussian_models.py
Labels: awaiting review

#1007 Add GPLVM for dimensional reduction
  docs/source/contrib.gp.rst
  pyro/contrib/gp/models/__init__.py
  pyro/contrib/gp/models/gplvm.py
  pyro/contrib/gp/util.py
  tests/contrib/gp/test_models.py
Labels: awaiting review

#1126 Add helper decorator for JITing parametrized functions
  docs/source/primitives.rst
  pyro/infer/trace_elbo.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/ops/jit.py
  pyro/poutine/handlers.py
  pyro/poutine/replay_messenger.py
  tests/infer/test_jit.py
  tests/poutine/test_poutines.py
Labels: awaiting review

#1125 Implicitly broadcast sample sites using iarange dim and size information
  docs/source/poutine.rst
  docs/source/pyro.poutine.txt
  pyro/poutine/__init__.py
  pyro/poutine/broadcast_messenger.py
  pyro/poutine/handlers.py
  pyro/util.py
  tests/infer/test_gradient.py
  tests/infer/test_valid_models.py
Labels: awaiting review, discussion

#1134 Implement AutoDelta and AutoLowRankMultivariateNormal
  docs/source/contrib.autoguide.rst
  pyro/contrib/autoguide/__init__.py
  tests/contrib/autoguide/test_advi.py
  tests/contrib/autoguide/test_inference.py
Labels: awaiting review, enhancement

#1138 Fix broken link in tutorial
  tutorial/source/tensor_shapes.ipynb
  tutorial/source/vae.ipynb
Labels: easy

#1139 Add pyro.ops.newton.newton_step_2d
  docs/source/index.rst
  docs/source/ops.rst
  pyro/ops/dual_averaging.py
  pyro/ops/newton.py
  tests/ops/test_newton.py
Labels: awaiting review

#1141 fix broken links on pyro.ai
  tutorial/source/tensor_shapes.ipynb
Labels: easy

#1140 Implement interface for higher-order optimizers
  docs/source/pyro.optim.txt
  pyro/optim/multi.py
  tests/optim/test_multi.py
Labels: awaiting review

#1133 Support dynamic learning rate
  docs/source/pyro.optim.txt
  pyro/optim/__init__.py
  pyro/optim/lr_scheduler.py
  pyro/optim/optim.py
  pyro/optim/pytorch_optimizers.py
  tests/optim/test_optim.py
Labels: awaiting review

#1147 Minor updates to perf tests
  .travis.yml
  tests/perf/test_benchmark.py
  tests/test_examples.py
Labels: awaiting review, easy

#1144 Add custom autoguide prefixes to facilitate composition
  pyro/contrib/autoguide/__init__.py
  pyro/params/param_store.py
  tests/contrib/autoguide/test_advi.py
Labels: awaiting review

#1148 Support decorating methods with handlers
  pyro/poutine/messenger.py
  pyro/poutine/trace_messenger.py
  tests/poutine/test_poutines.py
Labels: awaiting review, bug

#1149 Adding doctest for testing Pyro docstring code
  .travis.yml
  Makefile
  docs/source/conf.py
  pyro/contrib/gp/kernels/kernel.py
  pyro/contrib/gp/models/gplvm.py
  pyro/contrib/gp/models/model.py
  pyro/contrib/named.py
  pyro/distributions/binomial.py
  pyro/distributions/iaf.py
  pyro/distributions/torch_distribution.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  pyro/poutine/block_messenger.py
  pyro/poutine/handlers.py
  pyro/poutine/trace_struct.py
  pyro/primitives.py
  setup.cfg
  tests/doctest_fixtures.py
Labels: awaiting review

#1145 add sparse gamma deep exponential family example
  examples/sparse_gamma_def.py
  setup.py
  tests/test_examples.py
Labels: awaiting review

#1152 Avoid NANs in _compute_dice_elbo()
  pyro/infer/traceenum_elbo.py
  tests/infer/test_enum.py
Labels: awaiting review, bug

#1153 Fix TraceEnum_ELBO to allow use of grad() in guide
  pyro/infer/traceenum_elbo.py
  tests/infer/test_enum.py
Labels: awaiting review, bug

#1154 Adding poutine.broadcast to tensor shapes tutorial
  tutorial/source/tensor_shapes.ipynb
Labels: awaiting review

#1156 Bump to version 0.2.1
  pyro/__init__.py
Labels: awaiting review

#1158 Change test precision for cuda test
  tests/optim/test_multi.py
Labels: awaiting review, easy

#1157 add multivariate normal distribution with avf control variate
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/avf_mvn.py
  pyro/distributions/omt_mvn.py
  tests/distributions/test_omt_mvn.py
Labels: awaiting review

#1162 Add hide_fn parameter to poutine.block
  pyro/poutine/block_messenger.py
  pyro/poutine/handlers.py
  tests/poutine/test_poutines.py
Labels: awaiting review

#1163 Relax broadcasting constraint on scale_tensor
  pyro/distributions/util.py
  tests/distributions/test_util.py
Labels: awaiting review

#1161 Create contrib.autoname and move contrib.named to contrib.autoname.named
  docs/source/contrib.autoname.rst
  docs/source/contrib.named.rst
  docs/source/index.rst
  examples/contrib/autoname/mixture.py
  examples/contrib/autoname/tree_data.py
  pyro/contrib/__init__.py
  pyro/contrib/autoname/__init__.py
  pyro/contrib/autoname/named.py
  tests/contrib/autoname/test_named.py
  tests/doctest_fixtures.py
  tests/test_examples.py
Labels: awaiting review, easy

#1166 Add AutoGuideList.median() method
  pyro/contrib/autoguide/__init__.py
  tests/contrib/autoguide/test_advi.py
Labels: awaiting review, enhancement
