Repository pyro-ppl/pyro, pull requests merged in 2018-03, with the labels that each got.

#830 add brute force comparison for downstream costs test
  tests/infer/test_compute_downstream_costs.py
Labels: awaiting review

#835 Fix node ordering after Trace.copy()
  pyro/poutine/trace.py
  tests/infer/test_enum.py
Labels: awaiting review, bug, easy

#806 Adopt strict batch shape semantics for distributions
  examples/bayesian_regression.py
  examples/dmm/dmm.py
  examples/vae.py
  examples/vae_comparison.py
  pyro/__init__.py
  pyro/contrib/gp/likelihoods/gaussian.py
  pyro/distributions/testing/rejection_gamma.py
  pyro/infer/trace_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/poutine/__init__.py
  pyro/poutine/indep_poutine.py
  pyro/shim.py
  pyro/util.py
  tests/infer/test_elbo_mapdata.py
  tests/infer/test_inference.py
  tests/infer/test_valid_models.py
  tests/integration_tests/test_tracegraph_elbo.py
  tests/test_memory.py
  tutorial/source/bayesian_regression.ipynb
Labels: awaiting review

#837 Improve documentation for distributions
  docs/source/conf.py
  docs/source/distributions.rst
  pyro/distributions/torch.py
  pyro/distributions/torch_distribution.py
Labels: awaiting review, documentation

#838 Minor cleanup to verlet integrator
  pyro/ops/integrator.py
Labels: awaiting review, easy

#843 Replace range with xrange in poutine.queue
  pyro/poutine/__init__.py
Labels: awaiting review, easy

#831 [Ready] Implement composed kernels
  pyro/contrib/gp/__init__.py
  pyro/contrib/gp/kernels/__init__.py
  pyro/contrib/gp/kernels/brownian.py
  pyro/contrib/gp/kernels/dot_product.py
  pyro/contrib/gp/kernels/isotropic.py
  pyro/contrib/gp/kernels/kernel.py
  pyro/contrib/gp/kernels/periodic.py
  pyro/contrib/gp/kernels/static.py
  pyro/contrib/gp/likelihoods/gaussian.py
  pyro/contrib/gp/likelihoods/likelihood.py
  pyro/contrib/gp/models/gpr.py
  pyro/contrib/gp/models/model.py
  pyro/contrib/gp/models/sgpr.py
  pyro/contrib/gp/models/svgp.py
  pyro/contrib/gp/models/vgp.py
  tests/contrib/gp/test_kernels.py
Labels: awaiting review

#841 Remove slow tests resulting in build timeout
  tests/infer/test_sampling.py
Labels: awaiting review

#848 Split TraceEnum_ELBO out of Trace_ELBO
  examples/ss_vae_M2.py
  pyro/infer/elbo.py
  pyro/infer/trace_elbo.py
  pyro/infer/traceenum_elbo.py
  tests/infer/test_enum.py
  tests/infer/test_gradient.py
  tests/infer/test_valid_models.py
  tutorial/source/gmm.ipynb
  tutorial/source/ss-vae.ipynb
Labels: awaiting review

#852 reuse conjugate gaussian chain for gradient tests
  tests/infer/test_conjugate_gradients.py
  tests/integration_tests/test_conjugate_gaussian_models.py
Labels: awaiting review

#854 Make cond_indep_stack a tuple (hence hashable)
  pyro/__init__.py
  pyro/poutine/indep_poutine.py
  pyro/poutine/trace_poutine.py
Labels: awaiting review, easy

#828 Fix enumerate + iarange
  pyro/distributions/torch_distribution.py
  pyro/distributions/util.py
  pyro/infer/enum.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/infer/util.py
  pyro/poutine/trace.py
  tests/common.py
  tests/distributions/test_mask.py
  tests/distributions/test_reshape.py
  tests/infer/test_compute_downstream_costs.py
  tests/infer/test_enum.py
  tests/infer/test_gradient.py
  tests/infer/test_util.py
Labels: awaiting review, bug

#740 Using torch transforms to run HMC on distributions with constrained support
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
Labels: awaiting review

#856 Fix docs links to PyTorch documentation
  docs/source/distributions.rst
  pyro/__init__.py
  pyro/contrib/gp/__init__.py
  pyro/contrib/gp/kernels/isotropic.py
  pyro/distributions/distribution.py
  pyro/distributions/torch.py
  pyro/distributions/torch_distribution.py
  pyro/distributions/util.py
  pyro/infer/util.py
  pyro/ops/integrator.py
  pyro/shim.py
Labels: awaiting review, documentation

#857 Using torch.tensor API in distributions module
  README.md
  pyro/distributions/delta.py
  pyro/distributions/distribution.py
  pyro/distributions/iaf.py
  pyro/distributions/multivariate_normal.py
  pyro/distributions/omt_mvn.py
  pyro/distributions/sparse_multivariate_normal.py
  pyro/distributions/torch.py
  pyro/distributions/torch_distribution.py
  pyro/distributions/util.py
  tests/distributions/dist_fixture.py
  tests/distributions/test_categorical.py
  tests/distributions/test_delta.py
  tests/distributions/test_distributions.py
  tests/distributions/test_iaf.py
  tests/distributions/test_mask.py
  tests/distributions/test_omt_mvn.py
  tests/distributions/test_one_hot_categorical.py
  tests/distributions/test_rejector.py
  tests/distributions/test_reshape.py
  tests/distributions/test_shapes.py
  tests/distributions/test_sparse_multivariate_normal.py
  tests/distributions/test_tensor_type.py
  tests/distributions/test_transformed_distribution.py
  tests/distributions/test_util.py
Labels: awaiting review, easy

#860 Using torch.tensor API in contrib module
  pyro/contrib/gp/__init__.py
  pyro/contrib/gp/kernels/brownian.py
  pyro/contrib/gp/kernels/kernel.py
  pyro/contrib/gp/kernels/static.py
  pyro/contrib/gp/models/gpr.py
  pyro/contrib/gp/models/svgp.py
  pyro/contrib/gp/models/vgp.py
  pyro/contrib/named.py
  tests/contrib/gp/test_kernels.py
  tests/contrib/gp/test_models.py
  tests/contrib/test_named.py
Labels: awaiting review, easy

#859 Cleanup things a bit
  README.md
  pyro/infer/tracegraph_elbo.py
  pyro/infer/util.py
  pyro/optim/optim.py
  pyro/params/param_store.py
  pyro/util.py
  setup.py
Labels: awaiting response

#849 Support dual averaging for HMC and NUTS
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/mcmc.py
  pyro/infer/mcmc/nuts.py
  pyro/infer/mcmc/trace_kernel.py
  pyro/ops/dual_averaging.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
Labels: awaiting review

#863 Make iarange contexts reusable
  examples/vae_comparison.py
  pyro/__init__.py
  pyro/poutine/__init__.py
  pyro/poutine/indep_poutine.py
  pyro/util.py
  tests/infer/test_enum.py
  tests/infer/test_valid_models.py
Labels: awaiting review

#868 Using the torch.tensor API in poutine module
  pyro/poutine/scale_poutine.py
  pyro/poutine/trace.py
  tests/poutine/test_mapdata.py
  tests/poutine/test_poutines.py
  tests/poutine/test_properties.py
Labels: awaiting review, easy

#867 Implement MultiFrameTensor data structure for Trace*_ELBO
  pyro/__init__.py
  pyro/infer/tracegraph_elbo.py
  pyro/infer/util.py
  pyro/poutine/indep_poutine.py
  pyro/util.py
  tests/infer/test_compute_downstream_costs.py
  tests/infer/test_util.py
  tests/infer/test_valid_models.py
Labels: awaiting review

#865 add partial rao-blackwellization to trace_elbo
  pyro/infer/trace_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/infer/util.py
  pyro/poutine/trace_poutine.py
  tests/infer/test_gradient.py
  tests/infer/test_util.py
Labels: awaiting response

#870 Fix EnumerateMessenger dim allocation
  pyro/poutine/enumerate_poutine.py
  tests/poutine/test_poutines.py
Labels: awaiting review, bug

#858 Adding perf regression test utils and profiling scripts for a few models
  .gitignore
  .travis.yml
  Makefile
  scripts/perf_test.sh
  scripts/profile_model.sh
  setup.py
  tests/perf/__init__.py
  tests/perf/conftest.py
  tests/perf/test_benchmark.py
Labels: WIP

#871 miscellaneous trace*_elbo cleanup
  pyro/infer/trace_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/infer/util.py
  pyro/poutine/trace_poutine.py
  tests/infer/test_compute_downstream_costs.py
  tests/infer/test_valid_models.py
Labels: awaiting review

#872 Make irange iterators reusable
  pyro/__init__.py
  tests/infer/test_compute_downstream_costs.py
  tests/infer/test_enum.py
  tests/infer/test_gradient.py
  tests/infer/test_valid_models.py
  tests/integration_tests/test_tracegraph_elbo.py
  tests/poutine/test_mapdata.py
Labels: awaiting review

#869 Using torch.tensor API in other Pyro modules
  pyro/nn/auto_reg_nn.py
  pyro/ops/integrator.py
  pyro/params/param_store.py
  tests/ops/test_integrator.py
  tests/optim/test_optim.py
  tests/params/test_module.py
  tests/params/test_param.py
Labels: awaiting review, easy

#873 Fix brittleness in profiling scripts
  .travis.yml
  scripts/perf_test.sh
  scripts/profile_model.sh
  tests/perf/test_benchmark.py
Labels: awaiting review

#878 Add cleannb script
  Makefile
  setup.py
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/cleannb.py
  tutorial/source/gmm.ipynb
  tutorial/source/intro_part_i.ipynb
Labels: awaiting review

#881 Clean up variable API usage in HMC and NUTS
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  pyro/ops/integrator.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
  tests/perf/test_benchmark.py
Labels: awaiting review

#885 Fix active_dims handling in pyro.contrib.gp
  pyro/contrib/gp/kernels/kernel.py
  tests/contrib/gp/test_kernels.py
Labels: awaiting review, bug, easy

#884 Clean up inference module by using torch.tensor API
  pyro/__init__.py
  pyro/contrib/gp/likelihoods/likelihood.py
  pyro/contrib/gp/models/sgpr.py
  pyro/infer/abstract_infer.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/mcmc.py
  pyro/infer/mcmc/nuts.py
  pyro/infer/tracegraph_elbo.py
  pyro/infer/util.py
  pyro/util.py
  tests/common.py
  tests/infer/mcmc/test_mcmc.py
  tests/infer/test_compute_downstream_costs.py
  tests/infer/test_elbo_mapdata.py
  tests/infer/test_enum.py
  tests/infer/test_gradient.py
  tests/infer/test_inference.py
  tests/infer/test_sampling.py
  tests/infer/test_valid_models.py
  tests/integration_tests/test_conjugate_gaussian_models.py
  tests/integration_tests/test_tracegraph_elbo.py
  tests/test_memory.py
Labels: awaiting review, easy

#886 Fix examples and tutorials to use the updated tensor API
  examples/air/air.py
  examples/air/main.py
  examples/bayesian_regression.py
  examples/contrib/named/mixture.py
  examples/contrib/named/tree_data.py
  examples/dmm/polyphonic_data_loader.py
  examples/inclined_plane.py
  examples/schelling.py
  examples/schelling_false.py
  examples/ss_vae_M2.py
  examples/utils/custom_mlp.py
  examples/utils/vae_plots.py
  examples/vae.py
  examples/vae_comparison.py
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/dmm.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/intro_part_i.ipynb
  tutorial/source/intro_part_ii.ipynb
  tutorial/source/ss-vae.ipynb
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_ii.ipynb
  tutorial/source/svi_part_iii.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review

#890 Upgrade to latest pytorch master
  README.md
  profiler/distributions.py
Labels: awaiting review, easy

#889 Run make test-tutorials in the current environment
  Makefile
Labels: awaiting review, easy

#891 Robustify dev install instructions in README
  README.md
Labels: awaiting review, easy

#892 Implement half-Cauchy distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/half_cauchy.py
  tests/distributions/conftest.py
Labels: awaiting review

#882 Support GP models with multidimensional output
  Makefile
  pyro/contrib/gp/models/gpr.py
  pyro/contrib/gp/models/model.py
  pyro/contrib/gp/models/sgpr.py
  pyro/contrib/gp/models/svgp.py
  pyro/contrib/gp/models/vgp.py
  pyro/distributions/sparse_multivariate_normal.py
  pyro/infer/svi.py
  tests/contrib/gp/test_kernels.py
  tests/contrib/gp/test_models.py
  tutorial/source/gp.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review

#894 Fix enumerate parallel via DiCE
  pyro/infer/enum.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/util.py
  pyro/poutine/replay_poutine.py
  tests/infer/test_enum.py
  tests/infer/test_gradient.py
  tests/poutine/test_properties.py
Labels: awaiting review

#898 Add pytorch installation script for mac and linux
  .travis.yml
  README.md
  scripts/install_pytorch.sh
Labels: awaiting review

#900 Update and clarify GMM tutorial
  pyro/params/param_store.py
  tutorial/source/gmm.ipynb
Labels: Anchor examples, awaiting review

#902 Simplify TraceEnum_ELBO and add more tests
  pyro/infer/enum.py
  tests/infer/test_inference.py
Labels: awaiting review

#907 Demonstrate how to monitor gradients in gmm tutorial
  tutorial/source/gmm.ipynb
Labels: Anchor examples, awaiting review

#908 Implement constraints in pyro.param statements
  pyro/infer/trace_elbo.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/params/param_store.py
  tests/infer/test_inference.py
  tutorial/source/gmm.ipynb
Labels: awaiting review

#911 Exclude some directories from make lint
  setup.cfg
Labels: awaiting review, easy

#909 Delete tagging mechanism from parameter store
  examples/air/air.py
  examples/air/main.py
  pyro/__init__.py
  pyro/optim/optim.py
  pyro/params/param_store.py
  tests/infer/test_inference.py
  tests/integration_tests/test_tracegraph_elbo.py
  tests/optim/test_optim.py
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_iii.ipynb
Labels: awaiting review

#906 Add check for TraceEnum_ELBO requirements
  pyro/infer/traceenum_elbo.py
  pyro/util.py
  tests/infer/test_valid_models.py
Labels: awaiting review

#903 simple automatic guide generation for advi
  docs/source/inference_algos.rst
  docs/source/pyro.infer.txt
  pyro/distributions/torch_distribution.py
  pyro/infer/__init__.py
  pyro/infer/advi.py
  pyro/util.py
  tests/infer/test_valid_models.py
  tests/integration_tests/test_advi.py
Labels: awaiting review

#914 address transform bug in advi
  pyro/distributions/delta.py
  pyro/infer/advi.py
  tests/infer/test_valid_models.py
  tests/integration_tests/test_advi.py
Labels: awaiting review

#917 Upgrading to PyTorch master
  .gitignore
  README.md
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/multivariate_normal.py
  pyro/distributions/omt_mvn.py
  pyro/distributions/torch.py
Labels: awaiting review

#913 Introduce validation toggle flags for pyro.infer module
  pyro/__init__.py
  pyro/infer/__init__.py
  pyro/infer/trace_elbo.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/tracegraph_elbo.py
  tests/conftest.py
  tests/infer/test_valid_models.py
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/gp.ipynb
Labels: awaiting review

#920 Update gmm tutorial to use PyTorch master
  tutorial/source/gmm.ipynb
Labels: awaiting review, easy

#923 Update bayesian regression/tutorial example for 0.2
  examples/bayesian_regression.py
  tutorial/source/bayesian_regression.ipynb
Labels: awaiting response

#926 Remove ng_ones(), ng_zeros() in favor of .new_zeros(), .new_ones()
  examples/air/air.py
  examples/dmm/dmm.py
  examples/dmm/polyphonic_data_loader.py
  pyro/util.py
Labels: awaiting review, easy

#919 Add unit tests with HMMs; weaken checks so enumeration works
  pyro/infer/traceenum_elbo.py
  pyro/util.py
  tests/infer/test_enum.py
Labels: awaiting review

#922 Controlling distribution argument validation via a global flag
  README.md
  pyro/__init__.py
  pyro/distributions/__init__.py
  pyro/distributions/delta.py
  pyro/distributions/half_cauchy.py
  pyro/distributions/sparse_mvn.py
  pyro/distributions/torch_distribution.py
  pyro/distributions/util.py
  pyro/infer/mcmc/nuts.py
  tests/conftest.py
  tests/distributions/conftest.py
  tests/distributions/test_distributions.py
  tests/distributions/test_shapes.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
  tests/perf/test_benchmark.py
  tests/poutine/test_poutines.py
  tutorial/source/gp.ipynb
Labels: awaiting review

#932 Rename analytic_mean, analytic_var, enumerable
  pyro/contrib/gp/util.py
  pyro/distributions/distribution.py
  pyro/distributions/torch_distribution.py
  pyro/infer/abstract_infer.py
  pyro/infer/enum.py
  pyro/poutine/util.py
  tests/distributions/test_transformed_distribution.py
Labels: awaiting review, easy

#935 Add semver compliant build metadata to Pyro version
  .gitignore
  pyro/__init__.py
  setup.py
Labels: awaiting review

#937 automatically get latest pytorch version in docs
  docs/source/conf.py
  scripts/install_pytorch.sh
Labels: awaiting review, easy

#941 fix arg_constraints in omt_mvn
  pyro/distributions/omt_mvn.py
Labels: awaiting review

#939 miscellaneous elbo/test cleanup
  pyro/infer/trace_elbo.py
  pyro/infer/tracegraph_elbo.py
  tests/distributions/test_transformed_distribution.py
  tests/infer/test_elbo_mapdata.py
  tests/infer/test_inference.py
  tests/integration_tests/test_tracegraph_elbo.py
Labels: awaiting review

#940 rename batch_log_pdf and log_pdf
  examples/air/air.py
  profiler/distributions.py
  pyro/__init__.py
  pyro/distributions/distribution.py
  pyro/distributions/rejector.py
  pyro/distributions/score_parts.py
  pyro/distributions/testing/rejection_gamma.py
  pyro/distributions/torch_distribution.py
  pyro/infer/importance.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/search.py
  pyro/infer/trace_elbo.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/infer/util.py
  pyro/poutine/trace.py
  pyro/util.py
  tests/distributions/dist_fixture.py
  tests/distributions/test_categorical.py
  tests/distributions/test_cuda.py
  tests/distributions/test_delta.py
  tests/distributions/test_distributions.py
  tests/distributions/test_one_hot_categorical.py
  tests/distributions/test_rejector.py
  tests/distributions/test_shapes.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
  tests/infer/test_compute_downstream_costs.py
  tests/integration_tests/test_advi.py
  tests/poutine/test_mapdata.py
  tests/poutine/test_poutines.py
  tutorial/source/intro_part_i.ipynb
Labels: awaiting review

#945 Misc fixes to ADVI
  pyro/infer/advi.py
  tests/integration_tests/test_advi.py
Labels: awaiting review

#948 Revise Delta distribution to support ADVI + Transforms
  pyro/distributions/delta.py
  pyro/infer/advi.py
  pyro/infer/trace_elbo.py
  tests/distributions/test_delta.py
  tests/integration_tests/test_advi.py
Labels: awaiting review

#954 refresh dmm ipython notebook
  tutorial/source/dmm.ipynb
Labels: awaiting review, documentation

#952 Updating to PyTorch master with no tensor type casting
  .travis.yml
  Makefile
  README.md
  examples/air/air.py
  examples/contrib/named/mixture.py
  examples/dmm/polyphonic_data_loader.py
  pyro/contrib/gp/kernels/isotropic.py
  pyro/distributions/torch.py
  pyro/infer/mcmc/nuts.py
  tests/contrib/gp/test_conditional.py
  tests/contrib/gp/test_kernels.py
  tests/contrib/gp/test_likelihoods.py
  tests/contrib/gp/test_models.py
  tests/distributions/conftest.py
  tests/distributions/test_categorical.py
  tests/distributions/test_delta.py
  tests/distributions/test_mask.py
  tests/distributions/test_omt_mvn.py
  tests/distributions/test_one_hot_categorical.py
  tests/distributions/test_sparse_mvn.py
  tests/infer/mcmc/test_mcmc.py
  tests/infer/test_elbo_mapdata.py
  tests/infer/test_enum.py
  tests/infer/test_inference.py
  tests/infer/test_valid_models.py
  tests/integration_tests/test_conjugate_gaussian_models.py
  tests/integration_tests/test_tracegraph_elbo.py
  tests/test_examples.py
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/gp.ipynb
Labels: awaiting review

#956 Temporary fix build by disabling smoke test on gp tutorial
  tutorial/source/gp.ipynb
Labels: awaiting review

#959 rename reparameterized => has_rsample in distributions
  pyro/distributions/distribution.py
  pyro/distributions/testing/rejection_gamma.py
  pyro/distributions/torch_distribution.py
  pyro/poutine/trace.py
Labels: awaiting review

#960 update inclined plane example to use scalars everywhere
  examples/inclined_plane.py
Labels: awaiting review

#961 Remove torch distribution wrappers and rename parameters
  examples/air/air.py
  examples/air/modules.py
  examples/bayesian_regression.py
  examples/contrib/named/mixture.py
  examples/contrib/named/tree_data.py
  examples/dmm/dmm.py
  examples/ss_vae_M2.py
  examples/utils/vae_plots.py
  examples/vae.py
  profiler/distributions.py
  pyro/__init__.py
  pyro/contrib/named.py
  pyro/distributions/iaf.py
  pyro/distributions/testing/naive_dirichlet.py
  pyro/distributions/testing/rejection_gamma.py
  pyro/distributions/torch.py
  pyro/distributions/util.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  pyro/ops/dual_averaging.py
  tests/contrib/test_named.py
  tests/distributions/conftest.py
  tests/distributions/dist_fixture.py
  tests/distributions/test_categorical.py
  tests/distributions/test_distributions.py
  tests/distributions/test_omt_mvn.py
  tests/distributions/test_one_hot_categorical.py
  tests/distributions/test_shapes.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_mcmc.py
  tests/infer/mcmc/test_nuts.py
  tests/infer/test_conjugate_gradients.py
  tests/infer/test_elbo_mapdata.py
  tests/infer/test_enum.py
  tests/infer/test_gradient.py
  tests/infer/test_inference.py
  tests/infer/test_sampling.py
  tests/infer/test_valid_models.py
  tests/integration_tests/test_conjugate_gaussian_models.py
  tests/integration_tests/test_tracegraph_elbo.py
  tests/nn/test_clipped_nn.py
  tests/optim/test_optim.py
  tests/poutine/test_mapdata.py
  tests/poutine/test_poutines.py
  tests/poutine/test_properties.py
  tutorial/source/_static/img/dmm.tex
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/dmm.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/intro_part_i.ipynb
  tutorial/source/ss-vae.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review

#962 remove ones and zeros from pyro utils
  examples/air/air.py
  pyro/__init__.py
  pyro/util.py
  tests/infer/test_sampling.py
  tests/poutine/test_poutines.py
Labels: awaiting review

#936 Tutorial on tensor shapes
  tutorial/source/index.rst
  tutorial/source/tensor_shapes.ipynb
Labels: awaiting review
