Repository pyro-ppl/pyro, pull requests merged in 2018-06, with the labels that each got.

#1167 Fix CUDA failure in advi test
  tests/contrib/autoguide/test_advi.py
Labels: easy, testing

#1170 Replace deprecated pytest get_marker invocation
  .travis.yml
  setup.py
  tests/conftest.py
Labels: awaiting review, easy, testing

#1169 fix shape bug in iaf
  pyro/distributions/iaf.py
  tests/distributions/test_iaf.py
Labels: awaiting review

#1172 Accept callables to AutoGuideList.add(-)
  docs/source/contrib.autoguide.rst
  pyro/contrib/autoguide/__init__.py
  tests/contrib/autoguide/test_advi.py
Labels: awaiting review, enhancement

#1171 Allocate rightmost available dim in iaranges by default
  pyro/poutine/runtime.py
  tests/infer/test_valid_models.py
Labels: awaiting review, breaking, discussion

#1179 Improve default handling of logger messages
  pyro/__init__.py
  pyro/infer/mcmc/mcmc.py
  pyro/logger.py
  pyro/primitives.py
  tests/__init__.py
  tests/contrib/gp/test_models.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_mcmc.py
  tests/infer/mcmc/test_nuts.py
Labels: awaiting review

#1181 add .gitattributes so that can be correctly labelled as python project by github linguistic
  .gitattributes
Labels: awaiting response

#1176 Vectorize ELBO computation over num particles
  pyro/infer/elbo.py
  pyro/infer/trace_elbo.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/tracegraph_elbo.py
  tests/infer/test_conjugate_gradients.py
  tests/infer/test_enum.py
  tests/infer/test_gradient.py
  tests/infer/test_valid_models.py
  tests/integration_tests/test_conjugate_gaussian_models.py
Labels: awaiting review, discussion

#1124 adding a straight through estimator for relaxed categorical
  pyro/distributions/__init__.py
  pyro/distributions/relaxed_straight_through.py
  tests/distributions/test_relaxed_straight_through.py
Labels: awaiting review

#1190 Implement flat assignment solvers (exact, bp, sparse)
  pyro/contrib/tracking/assignment.py
  tests/contrib/tracking/test_assignment.py
Labels: awaiting review

#1195 Make the BlockMessenger inside TracePosterior function correctly
  pyro/infer/abstract_infer.py
  tests/infer/test_abstract_infer.py
Labels: awaiting review, bug, easy

#1196 Do not throw NaN warnings during NUTS/HMC adaptation
  pyro/infer/mcmc/hmc.py
  pyro/poutine/__init__.py
  pyro/poutine/trace_struct.py
  pyro/poutine/util.py
  pyro/primitives.py
  pyro/util.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
Labels: awaiting review

#1194 Implement compute_marginals_persistent_bp()
  pyro/contrib/tracking/assignment.py
  tests/contrib/tracking/test_assignment.py
Labels: awaiting review

#1159 Add a crude trace-based scoping mechanism for sample names
  docs/source/contrib.autoname.rst
  examples/contrib/autoname/scoping_mixture.py
  pyro/contrib/autoname/__init__.py
  pyro/contrib/autoname/scoping.py
  pyro/poutine/handlers.py
  pyro/poutine/trace_messenger.py
  pyro/poutine/trace_struct.py
  tests/contrib/autoname/test_scoping.py
  tests/test_examples.py
Labels: awaiting review

#1197 Fix CUDA tests on Pyro dev
  tests/contrib/tracking/test_assignment.py
  tests/distributions/test_relaxed_straight_through.py
  tests/infer/test_gradient.py
Labels: awaiting review, easy, testing

#1188 add relaxed bernoulli with straight through gradient estimator
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/relaxed_straight_through.py
  tests/distributions/test_relaxed_straight_through.py
Labels: awaiting review

#1192 Add eight schools example
  examples/eight_schools/README.md
  examples/eight_schools/data.py
  examples/eight_schools/mcmc.py
  examples/eight_schools/svi.py
  tests/test_examples.py
Labels: awaiting review

#1198 Add RSA examples
  examples/rsa/README.md
  examples/rsa/generics.py
  examples/rsa/hyperbole.py
  examples/rsa/schelling.py
  examples/rsa/schelling_false.py
  examples/rsa/search_inference.py
  examples/rsa/semantic_parsing.py
  setup.py
  tests/test_examples.py
Labels: awaiting review

#1199 Add momentum to compute_marginals_persistent_bp()
  pyro/contrib/tracking/assignment.py
  tests/contrib/tracking/test_assignment.py
Labels: awaiting review

#1205 Fix RNG seed for each replication of benchmark test
  tests/perf/test_benchmark.py
Labels: awaiting review, easy, profiling

#1202 Refactor `warn_if_nan`
  pyro/contrib/tracking/assignment.py
  pyro/ops/newton.py
  pyro/poutine/trace_struct.py
  pyro/util.py
  tests/test_util.py
Labels: awaiting review

#1206 clarify param_store.load() docs
  pyro/params/param_store.py
Labels: easy
