Repository pyro-ppl/pyro, pull requests merged in 2018-10, with the labels that each got.

#1424 Implement cheaper einsum path optimizer
  examples/hmm.py
  pyro/ops/einsum/__init__.py
  pyro/ops/einsum/paths.py
  tests/infer/enum_growth.ipynb
  tests/infer/test_enum.py
  tests/ops/einsum/test_cache.py
  tests/ops/einsum/test_paths.py
Labels: awaiting review

#1428 Xfail flaky assert in test_path
  tests/ops/einsum/test_paths.py
Labels: awaiting review, easy

#1432 Warn if a prior name is misspelled in random_module
  pyro/poutine/lift_messenger.py
  pyro/primitives.py
  tests/poutine/test_poutines.py
Labels: awaiting review

#1430 Update einsum optimizer to match upstream
  pyro/contrib/glmm/__init__.py
  pyro/ops/einsum/paths.py
  tests/infer/enum_growth.ipynb
  tests/ops/einsum/test_paths.py
Labels: awaiting review, easy

#1438 Fix OOM error in CUDA tests
  tests/distributions/test_gaussian_mixtures.py
Labels: awaiting review, easy

#1445 Fix jit error in hmm example
  examples/hmm.py
Labels: WIP, awaiting review

#1442 Add mass matrix adaptation for HMC
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/mcmc.py
  pyro/infer/mcmc/nuts.py
  pyro/infer/mcmc/trace_kernel.py
  pyro/ops/dual_averaging.py
  pyro/ops/integrator.py
  pyro/ops/welford.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_mcmc.py
  tests/infer/mcmc/test_nuts.py
  tests/ops/test_integrator.py
Labels: awaiting review

#1448 Add RSA tutorials to website
  tutorial/source/RSA-hyperbole.ipynb
  tutorial/source/index.rst
Labels: awaiting review, easy, website

#1447 Add partial pooling (no logit) baseball example
  examples/baseball.py
Labels: awaiting review

#1449 Bump networkx version to 2.2
  docs/requirements.txt
  setup.py
Labels: awaiting review, easy

#1441 Update importance.py (new features)
  pyro/infer/importance.py
Labels: awaiting review

#1307 Make iarange and irange into Messengers
  docs/source/poutine.rst
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/util.py
  pyro/poutine/__init__.py
  pyro/poutine/broadcast_messenger.py
  pyro/poutine/handlers.py
  pyro/poutine/indep_messenger.py
  pyro/poutine/plate_messenger.py
  pyro/poutine/subsample_messenger.py
  pyro/primitives.py
  tests/infer/mcmc/test_valid_models.py
Labels: awaiting review, refactor

#1457 Fix HMC tests on CUDA
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
Labels: awaiting review, easy

#1217 Add more tests for probabilistic assignment solvers
  tests/contrib/tracking/test_assignment.py
Labels: awaiting review, testing

#1462 Fix pickling of dynamically imported torch distributions
  pyro/distributions/torch.py
  tests/distributions/test_pickle.py
Labels: awaiting review

#1467 bump CI to python 3.6
  .travis.yml
  setup.py
Labels: easy

#1394 Add Kalman Filter Tutorial
  pyro/contrib/tracking/distributions.py
  pyro/contrib/tracking/dynamic_models.py
  pyro/contrib/tracking/extended_kalman_filter.py
  tests/contrib/tracking/test_distributions.py
  tutorial/source/_static/img/ekf_track.png
  tutorial/source/ekf.ipynb
  tutorial/source/index.rst
Labels: Examples, awaiting review

#1469 Fix non determinism in HMC / NUTS
  examples/baseball.py
  pyro/infer/mcmc/hmc.py
Labels: awaiting review, easy

#1466 Modify turning condition for nuts
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  tests/infer/mcmc/test_nuts.py
Labels: awaiting review

#1471 Guess max_plate_nesting if it is not provided
  pyro/infer/elbo.py
  pyro/infer/traceenum_elbo.py
  pyro/util.py
  tests/infer/test_enum.py
  tests/infer/test_gradient.py
  tests/infer/test_valid_models.py
Labels: Blocked, awaiting review

#1476 Fix RNG seed for all doctest runs
  tests/doctest_fixtures.py
Labels: awaiting review, easy

#1474 Guess max_plate_nesting if it is not provided
  pyro/infer/elbo.py
  pyro/infer/traceenum_elbo.py
  pyro/util.py
  tests/contrib/oed/test_eig.py
  tests/infer/test_enum.py
  tests/infer/test_gradient.py
  tests/infer/test_valid_models.py
  tutorial/source/tensor_shapes.ipynb
Labels: awaiting review

#1477 Fix failing CUDA test in test_nuts
  tests/infer/mcmc/test_nuts.py
Labels: awaiting review, easy

#1439 Implementation of Inference Compilation
  pyro/infer/__init__.py
  pyro/infer/csis.py
  pyro/poutine/__init__.py
  pyro/poutine/handlers.py
  pyro/poutine/uncondition_messenger.py
  tests/infer/test_csis.py
  tests/poutine/test_poutines.py
Labels: awaiting review

#1472 Multinomial sampling for NUTS
  pyro/infer/mcmc/nuts.py
  tests/infer/mcmc/test_nuts.py
Labels: awaiting review

#1443 Support parallel chains in HMC
  examples/baseball.py
  examples/eight_schools/mcmc.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/logger.py
  pyro/infer/mcmc/mcmc.py
  tests/test_examples.py
Labels: awaiting review

#1478 Make HMC try to find a valid initial trace
  pyro/infer/mcmc/hmc.py
Labels: awaiting review

#1485 Fix skip marker in test_pickle
  tests/distributions/test_pickle.py
Labels: awaiting review, easy

#1484 Fix CUDA tests on dev
  pyro/infer/mcmc/nuts.py
  tests/infer/mcmc/test_nuts.py
  tests/infer/test_enum.py
Labels: awaiting review, easy

#1468 Inference Compilation example
  tutorial/source/csis.ipynb
  tutorial/source/index.rst
Labels: Examples, awaiting review

#1496 Fix flake8 errors W605 due to lack of r prefix on docstrings
  examples/baseball.py
  pyro/contrib/autoguide/__init__.py
  pyro/contrib/gp/kernels/dot_product.py
  pyro/contrib/gp/kernels/kernel.py
  pyro/contrib/gp/kernels/static.py
  pyro/contrib/gp/likelihoods/gaussian.py
  pyro/contrib/gp/models/model.py
  pyro/contrib/gp/models/sgpr.py
  pyro/contrib/gp/util.py
  pyro/contrib/tracking/hashing.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/trace_kernel.py
  tests/distributions/dist_fixture.py
  tests/infer/test_valid_models.py
Labels: awaiting review, easy

#1492 PermutationFlow
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/permute.py
  pyro/distributions/torch_distribution.py
  tests/distributions/test_flows.py
  tests/nn/__init__.py
  tests/nn/test_autoregressive.py
Labels: awaiting review

#1493 add citation to README
  README.md
Labels: easy

#1446 Allow other operation labels in Poutine
  pyro/poutine/lift_messenger.py
  pyro/poutine/messenger.py
  pyro/poutine/runtime.py
  pyro/primitives.py
Labels: awaiting review

#1498 New version of IAF and inversion operator
  docs/source/distributions.rst
  pyro/contrib/autoguide/__init__.py
  pyro/distributions/__init__.py
  pyro/distributions/iaf.py
  tests/distributions/test_flows.py
Labels: awaiting review

#1500 Refactor sum_dims to be a set rather than dict
  pyro/infer/mcmc/util.py
  pyro/infer/traceenum_elbo.py
  pyro/ops/contract.py
  tests/ops/test_contract.py
Labels: awaiting review, easy

#1501 Use outer product instead of matmul in welford algorithm
  pyro/ops/welford.py
Labels: easy

#1503 remove numpy usage in main package
  pyro/contrib/oed/eig.py
  pyro/contrib/oed/util.py
  pyro/ops/einsum/paths.py
  setup.py
Labels: awaiting review
