Repository pyro-ppl/pyro, pull requests merged in 2018-09, with the labels that each got.

#1350 Add pytest.raises(match=_) patterns in test_valid_models.py
  tests/infer/test_valid_models.py
Labels: awaiting review, easy, testing

#1322 Use einsum for trace log prob evaluation in HMC
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  pyro/infer/mcmc/util.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
Labels: awaiting review

#1343 Fix model enumeration across iaranges
  pyro/infer/contract.py
  pyro/infer/traceenum_elbo.py
  tests/infer/test_contract.py
  tests/infer/test_enum.py
  tests/infer/test_valid_models.py
Labels: awaiting review

#1356 Detect invalid guide structure in model-guide enumeration
  pyro/infer/traceenum_elbo.py
  tests/infer/test_enum.py
  tests/infer/test_valid_models.py
Labels: awaiting review

#1357 Implement contract_to_tensor() helper for querying marginals
  pyro/infer/contract.py
  tests/infer/test_contract.py
Labels: awaiting review

#1360 Fix warning in gmm tutorial
  tutorial/source/gmm.ipynb
Labels: awaiting review, bug, easy

#1349 Add mixture of diag normals
  pyro/distributions/__init__.py
  pyro/distributions/diag_normal_mixture.py
  pyro/distributions/diag_normal_mixture_shared_cov.py
  pyro/distributions/gaussian_scale_mixture.py
  tests/distributions/test_gaussian_mixtures.py
  tests/infer/test_enum.py
Labels: awaiting review

#1366 disable codecov comments
  .codecov.yml
Labels: easy

#1344 Update GMM tutorial to discuss model enumeration
  tutorial/source/gmm.ipynb
Labels: Anchor examples, awaiting review

#1362 Add LDA example to demonstrate model-side enumeration
  examples/lda.py
  tests/test_examples.py
Labels: Anchor examples, awaiting review

#1369 Pin to pytest 3.7
  setup.py
Labels: awaiting review, easy

#1361 Barber-Agakov, and OED refactoring
  examples/contrib/oed/ab_test.py
  examples/contrib/oed/dv/neural.py
  examples/contrib/oed/eig_estimation_benchmarking.py
  examples/contrib/oed/guides/__init__.py
  examples/contrib/oed/guides/amort.py
  examples/contrib/oed/item_response.py
  examples/contrib/oed/models/bayes_linear.py
  pyro/contrib/autoguide/__init__.py
  pyro/contrib/oed/eig.py
  tests/contrib/autoguide/test_mean_field_guide_entropy.py
  tests/contrib/oed/test_eig.py
  tests/test_examples.py
Labels: awaiting review

#1367 Add an implementation of forward filtering / backward sampling
  pyro/infer/traceenum_elbo.py
  pyro/poutine/enumerate_messenger.py
  tests/infer/test_enum.py
Labels: awaiting review

#1377 Updating distributions module with PyTorch master
  pyro/distributions/__init__.py
  pyro/distributions/lowrank_mvn.py
  pyro/distributions/torch.py
  pyro/distributions/torch_distribution.py
  pyro/distributions/torch_patch.py
  pyro/infer/traceenum_elbo.py
  tests/distributions/conftest.py
  tests/distributions/test_distributions.py
Labels: WIP

#1378 Move einsum character remapping upstream
  pyro/distributions/torch_patch.py
  pyro/ops/einsum/torch_log.py
Labels: awaiting review, easy

#1382 Unit test fixes for CUDA
  pyro/distributions/torch_patch.py
  tests/common.py
  tests/contrib/oed/test_eig.py
  tests/contrib/oed/test_ewma.py
  tests/contrib/tracking/test_ekf.py
  tests/infer/test_enum.py
Labels: awaiting review

#1384 Allow for device kwarg in sumproduct
  pyro/infer/util.py
  pyro/ops/sumproduct.py
Labels: awaiting review, easy

#1387 Disable documentation inheritance in sphinx
  docs/source/conf.py
  pyro/docutil.py
Labels: discussion, easy

#1372 Add example: Sequential OED with sigmoid-transformed linear model
  examples/contrib/oed/sequential_oed_sigmoid_lm.py
  tests/test_examples.py
Labels: Anchor examples

#1390 Fix CUDA tests in test_eig.py
  tests/contrib/oed/test_eig.py
Labels: awaiting review, easy

#1191 Make trace a subclass of networkx.DiGraph again
  docs/requirements.txt
  pyro/poutine/trace_struct.py
  setup.py
  tests/infer/test_compute_downstream_costs.py
Labels: awaiting review, refactor

#1392 Work-around to allow JIT compiler to infer batch size in iarange
  examples/air/main.py
  pyro/distributions/util.py
  pyro/infer/elbo.py
  pyro/infer/enum.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  pyro/infer/trace_elbo.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/ops/jit.py
  pyro/ops/sumproduct.py
  pyro/poutine/broadcast_messenger.py
  pyro/poutine/indep_messenger.py
  pyro/primitives.py
  pyro/util.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
  tests/infer/test_enum.py
  tests/infer/test_jit.py
Labels: awaiting review

#1395 Add device keyword for iarange and irange
  examples/air/air.py
  pyro/primitives.py
  tests/poutine/test_mapdata.py
Labels: awaiting review

#1396 Remove duplicate set_seed function
  examples/vae/ss_vae_M2.py
  pyro/contrib/examples/util.py
Labels: awaiting review, easy

#1401 fix make docs in py3
  pyro/contrib/glmm/glmm.py
Labels: easy

#1398 Remove tensor constructors that use existing tensors
  examples/bayesian_regression.py
  examples/contrib/oed/gp_bayes_opt.py
  pyro/contrib/gp/models/sgpr.py
  pyro/distributions/delta.py
  pyro/distributions/iaf.py
  pyro/distributions/omt_mvn.py
  pyro/ops/newton.py
  tests/contrib/autoguide/test_hessian.py
  tests/contrib/gp/test_likelihoods.py
  tests/contrib/gp/test_models.py
  tests/distributions/test_gaussian_mixtures.py
  tests/distributions/test_omt_mvn.py
  tests/distributions/test_rejector.py
  tests/infer/test_elbo_mapdata.py
  tests/infer/test_enum.py
  tests/infer/test_inference.py
  tests/infer/test_valid_models.py
  tests/integration_tests/test_conjugate_gaussian_models.py
  tests/params/test_param.py
Labels: awaiting review

#1405 Refactor towards packed tensor representations
  docs/source/ops.rst
  pyro/infer/contract.py
  pyro/infer/traceenum_elbo.py
  pyro/ops/einsum/__init__.py
  pyro/ops/sumproduct.py
  pyro/poutine/indep_messenger.py
  tests/infer/test_contract.py
Labels: awaiting review, refactor

#1403 Use contract_to_tensor in HMC for discrete site enumeration
  pyro/distributions/torch_patch.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/util.py
  tests/infer/mcmc/test_nuts.py
  tests/infer/mcmc/test_valid_models.py
Labels: awaiting review

#1410 Minor testing related fixes
  Makefile
  examples/baseball.py
  pyro/infer/mcmc/logger.py
  pyro/ops/einsum/__init__.py
Labels: awaiting review, easy

#1412 CUDA fix for IAF
  pyro/distributions/iaf.py
Labels: awaiting review, easy

#1411 Use logging instead of print in tests
  tests/__init__.py
  tests/contrib/autoname/test_scoping.py
  tests/contrib/oed/test_eig.py
  tests/contrib/tracking/test_assignment.py
  tests/contrib/tracking/test_em.py
  tests/contrib/tracking/test_hashing.py
  tests/distributions/test_gaussian_mixtures.py
  tests/infer/test_enum.py
  tests/infer/test_jit.py
  tests/ops/einsum/test_shared.py
  tests/ops/test_newton.py
  tests/ops/test_sumproduct.py
  tests/poutine/test_nesting.py
Labels: awaiting review, easy, testing

#1408 Relax diamond restriction on iarange nesting for enumeration
  pyro/infer/contract.py
  tests/infer/test_contract.py
  tests/infer/test_enum.py
Labels: awaiting review

#1413 Move pyro.infer.contract into pyro.ops
  docs/source/ops.rst
  pyro/infer/mcmc/util.py
  pyro/infer/traceenum_elbo.py
  pyro/ops/contract.py
  tests/ops/test_contract.py
Labels: awaiting review, easy, refactor

#1416 Test fixes for compatibility with PyTorch master
  examples/air/main.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
  tests/infer/test_inference.py
  tests/integration_tests/test_conjugate_gaussian_models.py
  tests/integration_tests/test_tracegraph_elbo.py
Labels: awaiting review, easy, testing

#1420 Fix incompatible dependency between jupyter-console and ipython
  setup.py
Labels: easy

#1417 Add naive_ubersum reference implementation + tests
  pyro/ops/contract.py
  pyro/ops/einsum/__init__.py
  pyro/ops/einsum/torch_log.py
  tests/infer/test_enum.py
  tests/ops/einsum/test_torch_log.py
  tests/ops/test_contract.py
Labels: awaiting review

#1423 clarify some language in the tensor shapes tutorial
  tutorial/source/tensor_shapes.ipynb
Labels: documentation, easy
