Repository pyro-ppl/pyro, pull requests merged in 2018-08, with the labels that each got.

#1283 Minor fixes to the VAE tutorial
  .gitignore
  .travis.yml
  Makefile
  examples/dmm/dmm.py
  examples/vae/vae.py
  tutorial/source/vae.ipynb
Labels: awaiting review, easy

#1284 bump travis docs version
  .travis.yml
  pyro/contrib/tracking/hashing.py
Labels: awaiting review

#1279 Add expand kwarg to .enumerate_support()
  pyro/distributions/binomial.py
  pyro/distributions/distribution.py
  pyro/distributions/empirical.py
  pyro/distributions/torch.py
  pyro/distributions/torch_distribution.py
  tests/distributions/test_distributions.py
  tests/distributions/test_mask.py
  tests/distributions/test_one_hot_categorical.py
  tests/distributions/test_reshape.py
Labels: awaiting review

#1291 Fix bug in TransformedDistribution.expand
  pyro/distributions/torch.py
  pyro/distributions/torch_distribution.py
  tests/distributions/test_distributions.py
Labels: awaiting review, bug, easy

#1292 ignores for code coverage
  .codecov.yml
  .travis.yml
Labels: WIP

#1289 Support .enumerate_support(expand=False) in SVI
  pyro/infer/enum.py
  pyro/poutine/broadcast_messenger.py
  pyro/poutine/enumerate_messenger.py
  tests/distributions/test_relaxed_straight_through.py
  tests/infer/test_enum.py
  tests/infer/test_valid_models.py
  tests/test_examples.py
Labels: awaiting review

#1295 Refactor test_examples.py to allow xfailing examples
  tests/test_examples.py
Labels: awaiting review, easy, testing

#1296 Add xfailing jit tests to many anchor examples
  examples/air/air.py
  examples/air/main.py
  examples/bayesian_regression.py
  examples/contrib/autoname/mixture.py
  examples/contrib/gp/sv-dkl.py
  examples/dmm/dmm.py
  examples/eight_schools/svi.py
  examples/vae/ss_vae_M2.py
  examples/vae/vae.py
  examples/vae/vae_comparison.py
  tests/test_examples.py
Labels: Anchor examples, awaiting review, testing

#1297 add coverage config file
  .codecov.yml
  .coveragerc
  .travis.yml
Labels: awaiting review, easy

#1298 Fix doctests to pass on Python 2.7
  pyro/contrib/tracking/hashing.py
Labels: awaiting review, easy, testing

#1301 Use expand=False while enumerating discrete sites in HMC
  pyro/infer/mcmc/hmc.py
  tests/infer/mcmc/test_nuts.py
Labels: awaiting review

#1300 Update dev branch for compatibility with PyTorch release
  examples/air/modules.py
  examples/dmm/dmm.py
  examples/vae/vae.py
  examples/vae/vae_comparison.py
  pyro/contrib/gp/likelihoods/binary.py
  pyro/distributions/gaussian_scale_mixture.py
  pyro/distributions/torch.py
  tests/common.py
  tests/contrib/gp/test_models.py
  tests/contrib/tracking/test_em.py
  tests/distributions/conftest.py
  tests/distributions/test_delta.py
  tests/distributions/test_von_mises.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
  tests/infer/mcmc/test_valid_models.py
  tests/infer/test_enum.py
  tests/infer/test_gradient.py
  tutorial/source/gp.ipynb
  tutorial/source/tensor_shapes.ipynb
  tutorial/source/tracking_1d.ipynb
Labels: awaiting review

#1262 More flexibility in MADE
  pyro/nn/auto_reg_nn.py
  tests/distributions/test_iaf.py
Labels: WIP

#1299 Use JIT traced potential energy computation in HMC
  Makefile
  examples/baseball.py
  examples/eight_schools/mcmc.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
  tests/test_examples.py
Labels: awaiting review

#1308 Fix AutoRegNN when default tensor type is CUDA
  pyro/nn/auto_reg_nn.py
  tests/distributions/test_iaf.py
Labels: awaiting review, easy

#1281 Add EKF NCV/NCP continuous implementation
  docs/source/contrib.tracking.rst
  pyro/contrib/tracking/dynamic_models.py
  pyro/contrib/tracking/extended_kalman_filter.py
  pyro/contrib/tracking/measurements.py
  pyro/distributions/util.py
  tests/common.py
  tests/contrib/tracking/test_dynamic_models.py
  tests/contrib/tracking/test_ekf.py
  tests/contrib/tracking/test_measurements.py
Labels: awaiting review

#1302 Implement local num_particles for TraceEnum_ELBO
  docs/source/poutine.rst
  pyro/infer/enum.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/util.py
  pyro/poutine/enumerate_messenger.py
  tests/infer/test_enum.py
  tests/infer/test_gradient.py
  tests/infer/test_valid_models.py
Labels: awaiting review, enhancement

#1313 Use opt_einsum for message passing in SVI
  docs/requirements.txt
  pyro/infer/traceenum_elbo.py
  pyro/infer/util.py
  pyro/ops/einsum/__init__.py
  pyro/ops/einsum/deferred.py
  pyro/ops/sumproduct.py
  setup.py
  tests/infer/test_enum.py
  tests/ops/einsum/conftest.py
  tests/ops/einsum/test_deferred.py
  tests/ops/test_sumproduct.py
Labels: awaiting review

#1314 Implement logsumexp backend for opt_einsum
  pyro/ops/einsum/torch_log.py
  tests/ops/einsum/test_torch_log.py
Labels: awaiting review

#1315 Add support for iarange in einsum-based Dice
  pyro/infer/util.py
  pyro/ops/sumproduct.py
  tests/ops/test_sumproduct.py
Labels: awaiting review

#1316 Refactor einsum sharing to be eager, composable
  docs/source/conf.py
  docs/source/ops.rst
  pyro/distributions/torch_patch.py
  pyro/infer/util.py
  pyro/ops/einsum/__init__.py
  pyro/ops/einsum/deferred.py
  pyro/ops/einsum/shared.py
  pyro/ops/sumproduct.py
  setup.cfg
  tests/infer/test_enum.py
  tests/ops/einsum/test_shared.py
  tests/ops/einsum/test_torch_log.py
  tests/ops/test_sumproduct.py
Labels: awaiting review

#1319 Handle float args to sumproduct with log backend
  pyro/ops/sumproduct.py
  tests/ops/einsum/test_torch_log.py
Labels: awaiting review

#1321 Make einsum inputs deterministic to increase sharing
  pyro/infer/traceenum_elbo.py
  pyro/infer/util.py
  tests/infer/test_enum.py
Labels: awaiting review

#1323 Work around performance issues in torch.einsum
  pyro/distributions/torch_patch.py
  tests/ops/test_sumproduct.py
Labels: awaiting review

#1324 Simplify einsum shared
  pyro/infer/util.py
  pyro/ops/einsum/__init__.py
  pyro/ops/einsum/shared.py
  tests/infer/test_enum.py
  tests/ops/einsum/test_shared.py
Labels: awaiting review

#1310 Implement discrete NCV/NCP models
  pyro/contrib/tracking/dynamic_models.py
  tests/contrib/tracking/test_dynamic_models.py
Labels: awaiting review

#1329 Implement logsumproductexp()
  pyro/infer/traceenum_elbo.py
  pyro/ops/sumproduct.py
  tests/ops/einsum/test_torch_log.py
  tests/ops/test_sumproduct.py
Labels: awaiting review

#1333 Speed up pickling of dmm; use pickling in einsum
  examples/dmm/__init__.py
  examples/dmm/dmm.py
  examples/dmm/polyphonic_data_loader.py
  pyro/ops/einsum/__init__.py
  tests/common.py
  tests/ops/einsum/test_cache.py
Labels: awaiting review

#1334 Separate poutine.mask() from poutine.scale()
  docs/source/poutine.rst
  pyro/contrib/autoname/scoping.py
  pyro/distributions/score_parts.py
  pyro/distributions/torch_distribution.py
  pyro/distributions/util.py
  pyro/poutine/__init__.py
  pyro/poutine/handlers.py
  pyro/poutine/mask_messenger.py
  pyro/poutine/scale_messenger.py
  pyro/poutine/trace_struct.py
  pyro/primitives.py
  tests/contrib/tracking/test_em.py
  tests/distributions/test_mask.py
  tests/distributions/test_util.py
  tutorial/source/tracking_1d.ipynb
Labels: awaiting review

#1335 Fix enumeration inside model (wrt scale, mask)
  pyro/infer/traceenum_elbo.py
  pyro/poutine/trace_struct.py
  tests/infer/test_enum.py
Labels: awaiting review

#1340 Set expand=False by default in discrete enumeration
  examples/vae/ss_vae_M2.py
  pyro/infer/enum.py
  pyro/infer/mcmc/hmc.py
  pyro/poutine/enumerate_messenger.py
  tests/infer/test_enum.py
  tests/infer/test_valid_models.py
  tutorial/source/tensor_shapes.ipynb
Labels: awaiting review

#1346 Deprecate use of unexposed field from opt-einsum=2.1.3
  pyro/ops/einsum/torch_log.py
Labels: awaiting review, easy
