Repository pyro-ppl/pyro, pull requests merged in 2018-02, with the labels that each got.

#759 Remove RandomPrimitive from profiler scripts
  profiler/distributions.py
Labels: awaiting review, easy

#757 Remove RandomPrimitive from most tests
  tests/contrib/test_named.py
  tests/distributions/test_categorical.py
  tests/distributions/test_delta.py
  tests/distributions/test_one_hot_categorical.py
  tests/distributions/test_tensor_type.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_mcmc.py
  tests/infer/test_elbo_mapdata.py
  tests/infer/test_gradient.py
  tests/infer/test_inference.py
  tests/infer/test_valid_models.py
  tests/integration_tests/test_conjugate_gaussian_models.py
  tests/integration_tests/test_tracegraph_elbo.py
  tests/poutine/test_mapdata.py
  tests/poutine/test_poutines.py
  tests/poutine/test_properties.py
Labels: awaiting review, testing

#761 Remove RandomPrimitive usage from examples/
  examples/air/air.py
  examples/contrib/named/mixture.py
  examples/contrib/named/tree_data.py
  examples/dmm/dmm.py
  examples/ss_vae_M2.py
  examples/vae.py
Labels: awaiting review

#762 Remove RandomPrimitive from distribution test fixture
  tests/distributions/conftest.py
  tests/distributions/dist_fixture.py
  tests/distributions/test_cuda.py
  tests/distributions/test_distributions.py
  tests/distributions/test_transformed_distribution.py
  tests/infer/test_valid_models.py
Labels: awaiting review, testing

#766 Wrap baseline dict in an infer dict
  examples/air/air.py
  pyro/__init__.py
  pyro/infer/tracegraph_elbo.py
  pyro/poutine/lift_poutine.py
  tests/integration_tests/test_conjugate_gaussian_models.py
  tests/integration_tests/test_tracegraph_elbo.py
  tutorial/source/air.ipynb
  tutorial/source/svi_part_iii.ipynb
Labels: awaiting review

#760 add score parts logic to trace_graph
  pyro/infer/trace_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/infer/util.py
  tests/infer/test_inference.py
Labels: awaiting review, enhancement

#755 Update tutorials for #752
  CONTRIBUTING.md
  tutorial/source/air.ipynb
  tutorial/source/dmm.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/intro_part_i.ipynb
  tutorial/source/intro_part_ii.ipynb
  tutorial/source/ss-vae.ipynb
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_ii.ipynb
  tutorial/source/svi_part_iii.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review

#764 Remove RandomPrimitive entirely
  examples/schelling.py
  examples/schelling_false.py
  pyro/distributions/__init__.py
  pyro/distributions/random_primitive.py
  pyro/distributions/testing/fakes.py
  pyro/distributions/torch/__init__.py
  pyro/distributions/torch/transformed_distribution.py
  pyro/infer/mcmc/hmc.py
  pyro/util.py
Labels: awaiting review

#768 Remove log_pdf_mask in favor of poutine.scale
  examples/air/air.py
  examples/dmm/dmm.py
  pyro/distributions/score_parts.py
  pyro/distributions/torch/bernoulli.py
  pyro/distributions/torch_wrapper.py
  pyro/distributions/util.py
  pyro/infer/trace_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/infer/util.py
  pyro/poutine/trace.py
  tests/distributions/test_distributions.py
  tests/distributions/test_shapes.py
  tutorial/source/air.ipynb
  tutorial/source/dmm.ipynb
  tutorial/source/ss-vae.ipynb
Labels: awaiting review

#763 Thin-out the Pyro wrappers around torch distributions
  pyro/distributions/delta.py
  pyro/distributions/torch/dirichlet.py
  pyro/distributions/torch/log_normal.py
  pyro/distributions/torch/transformed_distribution.py
  pyro/distributions/torch_wrapper.py
Labels: awaiting review, easy

#770 Remove unused PyTorch helpers
  pyro/distributions/util.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/trace_elbo.py
  tests/distributions/test_transformed_distribution.py
  tests/infer/mcmc/test_hmc.py
Labels: awaiting review, easy

#767 Refactor GP module
  docs/source/contrib.gp.rst
  pyro/contrib/gp/__init__.py
  pyro/contrib/gp/kernels/__init__.py
  pyro/contrib/gp/kernels/kernel.py
  pyro/contrib/gp/kernels/rbf.py
  pyro/contrib/gp/models/__init__.py
  pyro/contrib/gp/models/gpr.py
  pyro/contrib/gp/models/model.py
  pyro/contrib/gp/models/sgpr.py
  pyro/infer/trace_elbo.py
  tests/contrib/gp/test_models.py
  tutorial/source/gp.ipynb
Labels: awaiting review

#769 Replace Distribution+TorchDistribution with a thin Distribution mixin
  Makefile
  docs/source/distributions.rst
  docs/source/primitive_dist.rst
  docs/source/pyro.distributions.transformed_distribution.txt
  docs/source/pyro.distributions.txt
  docs/source/transformed_dist.rst
  examples/air/air.py
  examples/ss_vae_M2.py
  pyro/__init__.py
  pyro/contrib/gp/__init__.py
  pyro/distributions/__init__.py
  pyro/distributions/delta.py
  pyro/distributions/distribution.py
  pyro/distributions/rejector.py
  pyro/distributions/testing/fakes.py
  pyro/distributions/testing/naive_dirichlet.py
  pyro/distributions/testing/rejection_gamma.py
  pyro/distributions/torch/__init__.py
  pyro/distributions/torch/bernoulli.py
  pyro/distributions/torch/beta.py
  pyro/distributions/torch/binomial.py
  pyro/distributions/torch/categorical.py
  pyro/distributions/torch/cauchy.py
  pyro/distributions/torch/dirichlet.py
  pyro/distributions/torch/exponential.py
  pyro/distributions/torch/gamma.py
  pyro/distributions/torch/log_normal.py
  pyro/distributions/torch/multinomial.py
  pyro/distributions/torch/multivariate_normal.py
  pyro/distributions/torch/normal.py
  pyro/distributions/torch/one_hot_categorical.py
  pyro/distributions/torch/poisson.py
  pyro/distributions/torch/sparse_multivariate_normal.py
  pyro/distributions/torch/transformed_distribution.py
  pyro/distributions/torch/uniform.py
  pyro/distributions/torch_distribution.py
  pyro/distributions/torch_wrapper.py
  pyro/distributions/util.py
  pyro/infer/abstract_infer.py
  pyro/poutine/trace.py
  pyro/util.py
  tests/distributions/test_rejector.py
  tests/distributions/test_shapes.py
  tests/distributions/test_sparse_multivariate_normal.py
  tests/infer/test_enum.py
  tests/infer/test_inference.py
  tests/infer/test_valid_models.py
  tests/integration_tests/test_tracegraph_elbo.py
  tutorial/source/air.ipynb
Labels: awaiting review

#775 Cleaning up enumeration-related things in poutine
  pyro/infer/enum.py
  pyro/poutine/__init__.py
  pyro/poutine/escape_poutine.py
  pyro/poutine/util.py
  pyro/util.py
  tests/poutine/test_poutines.py
Labels: awaiting review

#747 [Done] Implement sparse variational GP
  docs/source/contrib.gp.rst
  pyro/contrib/gp/likelihoods/__init__.py
  pyro/contrib/gp/likelihoods/gaussian.py
  pyro/contrib/gp/likelihoods/likelihood.py
  pyro/contrib/gp/models/__init__.py
  pyro/contrib/gp/models/gpr.py
  pyro/contrib/gp/models/model.py
  pyro/contrib/gp/models/sgpr.py
  pyro/contrib/gp/models/svgp.py
  pyro/contrib/gp/models/vgp.py
  tutorial/source/gp.ipynb
Labels: awaiting review

#777 add omt mvn distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/omt_mvn.py
  pyro/distributions/util.py
  tests/distributions/test_omt_mvn.py
  tests/distributions/test_util.py
Labels: awaiting review

#778 Simplify ELBO plumbing
  pyro/infer/elbo.py
  pyro/infer/svi.py
  pyro/infer/trace_elbo.py
  pyro/infer/tracegraph_elbo.py
Labels: awaiting review

#784 Add instructions on installing dev branch
  README.md
Labels: awaiting review, documentation

#785 Correct diagnostic behavior of hmc
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/mcmc.py
  pyro/infer/mcmc/trace_kernel.py
  pyro/ops/integrator.py
  pyro/poutine/trace_poutine.py
  tests/infer/mcmc/test_hmc.py
Labels: awaiting review

#789 cleanup and fix omtmvn
  pyro/distributions/omt_mvn.py
  tests/distributions/test_omt_mvn.py
Labels: awaiting review

#787 Implement No-U-turn sampler
  docs/source/pyro.infer.mcmc.txt
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  tests/infer/mcmc/test_nuts.py
Labels: awaiting review

#794 Automatically import all standard torch distributions
  docs/source/contrib.gp.rst
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/torch/__init__.py
Labels: awaiting review

#792 Infer config poutine
  pyro/__init__.py
  pyro/poutine/__init__.py
  pyro/poutine/infer_config_poutine.py
  tests/poutine/test_poutines.py
Labels: awaiting review

#800 Skip slow NUTS tests for local runs
  tests/infer/mcmc/test_nuts.py
Labels: easy

#801 Work around memory leak in networkx
  pyro/poutine/trace.py
  tests/test_memory.py
Labels: awaiting review, bug

#795 Reuse grad calculation for NUTS
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  pyro/ops/integrator.py
Labels: awaiting review

#797 Resolve code breakage due to PyTorch scalar introduction
  README.md
  examples/bayesian_regression.py
  pyro/infer/abstract_infer.py
  pyro/infer/trace_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/util.py
  tests/distributions/test_categorical.py
  tests/distributions/test_distributions.py
  tests/distributions/test_omt_mvn.py
  tutorial/source/bayesian_regression.ipynb
Labels: awaiting review

#808 make docs work
  docs/source/conf.py
Labels: documentation, high priority

#810 Add docs badge to readme
  README.md
Labels: easy

#776 Implement parallel enumeration over discrete sample sites
  docs/source/installation.rst
  examples/ss_vae_M2.py
  pyro/distributions/util.py
  pyro/infer/__init__.py
  pyro/infer/elbo.py
  pyro/infer/enum.py
  pyro/infer/trace_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/poutine/__init__.py
  pyro/poutine/enumerate_poutine.py
  pyro/poutine/trace.py
  tests/distributions/test_util.py
  tests/infer/test_enum.py
  tests/infer/test_valid_models.py
  tests/poutine/test_mapdata.py
  tests/test_examples.py
  tutorial/source/gmm.ipynb
  tutorial/source/ss-vae.ipynb
Labels: awaiting review

#820 Add stage marker to test_memory
  tests/test_memory.py
Labels: easy, testing

#821 Implement TorchDistribution.mask() for dependent masks
  examples/dmm/dmm.py
  pyro/distributions/torch_distribution.py
  tests/distributions/test_mask.py
Labels: awaiting review

#780 working towards nested iarange in tracegraph_elbo
  pyro/infer/tracegraph_elbo.py
  pyro/infer/util.py
  pyro/poutine/trace_poutine.py
  tests/infer/test_compute_downstream_costs.py
  tests/infer/test_util.py
  tests/infer/test_valid_models.py
  tests/integration_tests/test_tracegraph_elbo.py
Labels: awaiting review

#824 Resolve changes in tensor/variable API with PyTorch master
  README.md
  examples/air/viz.py
  examples/contrib/named/mixture.py
  examples/contrib/named/tree_data.py
  examples/dmm/dmm.py
  examples/inclined_plane.py
  examples/ss_vae_M2.py
  examples/utils/vae_plots.py
  examples/vae.py
  examples/vae_comparison.py
  pyro/__init__.py
  pyro/infer/abstract_infer.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  pyro/infer/svi.py
  pyro/nn/auto_reg_nn.py
  pyro/poutine/trace.py
  tests/common.py
  tests/contrib/gp/test_kernels.py
  tests/contrib/gp/test_models.py
  tests/distributions/dist_fixture.py
  tests/distributions/test_categorical.py
  tests/distributions/test_delta.py
  tests/distributions/test_distributions.py
  tests/distributions/test_iaf.py
  tests/distributions/test_one_hot_categorical.py
  tests/distributions/test_rejector.py
  tests/distributions/test_tensor_type.py
  tests/distributions/test_transformed_distribution.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_mcmc.py
  tests/infer/mcmc/test_nuts.py
  tests/infer/test_elbo_mapdata.py
  tests/infer/test_enum.py
  tests/infer/test_gradient.py
  tests/infer/test_inference.py
  tests/infer/test_sampling.py
  tests/integration_tests/test_conjugate_gaussian_models.py
  tests/integration_tests/test_tracegraph_elbo.py
  tests/nn/test_clipped_nn.py
  tests/ops/test_integrator.py
  tests/params/test_param.py
  tests/poutine/test_poutines.py
  tests/poutine/test_properties.py
  tutorial/source/air.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/intro_part_i.ipynb
  tutorial/source/intro_part_ii.ipynb
  tutorial/source/svi_part_ii.ipynb
Labels: awaiting review, easy

#805 [Done] Add various kernels for GP module
  docs/source/contrib.gp.rst
  pyro/contrib/gp/kernels/__init__.py
  pyro/contrib/gp/kernels/brownian.py
  pyro/contrib/gp/kernels/dot_product.py
  pyro/contrib/gp/kernels/isotropic.py
  pyro/contrib/gp/kernels/kernel.py
  pyro/contrib/gp/kernels/periodic.py
  pyro/contrib/gp/kernels/rbf.py
  pyro/contrib/gp/kernels/static.py
  tests/contrib/gp/test_kernels.py
Labels: awaiting review
