Repository pyro-ppl/pyro, pull requests merged in 2018-11, with the labels that each got.

#1506 Return a deterministic trace generator when using HMC with parallel chains
  pyro/infer/mcmc/mcmc.py
Labels: awaiting review

#1510 Minor optimizations to pyro.ops.contract
  pyro/ops/contract.py
  pyro/ops/sumproduct.py
Labels: awaiting review

#1509 Add site information for possible exception thrown when calculating logp
  pyro/poutine/trace_struct.py
  tests/poutine/test_poutines.py
Labels: awaiting review, warnings & errors

#1516 Cache potential energy and gradient of last trace in HMC/NUTS
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  pyro/ops/integrator.py
  tests/ops/test_integrator.py
Labels: awaiting review

#1518 Drop support for LBFGS
  pyro/contrib/autoguide/__init__.py
  pyro/contrib/util.py
  pyro/optim/pytorch_optimizers.py
  pyro/poutine/handlers.py
  tests/contrib/autoguide/test_hessian.py
  tests/contrib/autoguide/test_inference.py
  tests/contrib/test_util.py
Labels: awaiting review, easy

#1522 Abstract out HMC adaptation into its own class
  pyro/infer/mcmc/adaptation.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  tests/infer/mcmc/test_adaptation.py
Labels: awaiting review, discussion, refactor

#1521 Implement pyro.markov to recycle enum dims
  docs/source/poutine.rst
  examples/hmm.py
  pyro/__init__.py
  pyro/distributions/util.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  pyro/infer/mcmc/util.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/util.py
  pyro/ops/contract.py
  pyro/ops/packed.py
  pyro/poutine/__init__.py
  pyro/poutine/enumerate_messenger.py
  pyro/poutine/handlers.py
  pyro/poutine/markov_messenger.py
  pyro/poutine/reentrant_messenger.py
  pyro/poutine/runtime.py
  pyro/poutine/trace_struct.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
  tests/infer/mcmc/test_valid_models.py
  tests/infer/test_enum.py
  tests/infer/test_jit.py
  tests/infer/test_valid_models.py
  tests/ops/test_packed.py
  tests/poutine/test_poutines.py
  tests/test_examples.py
  tutorial/source/tracking_1d.ipynb
Labels: awaiting review

#1530 Small test fixes for CI
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
  tests/nn/conftest.py
  tests/test_memory.py
  tests/test_util.py
Labels: easy, testing

#1524 update intro tutorial (part ii)
  tutorial/source/intro_part_ii.ipynb
Labels: Examples, awaiting review, documentation

#1534 Add pretty printing of trace shapes on error
  pyro/poutine/trace_messenger.py
  pyro/poutine/trace_struct.py
  tests/poutine/test_poutines.py
Labels: awaiting review, warnings & errors

#1536 Switch to packed tensors in MCMC for pyro.markov
  pyro/infer/mcmc/util.py
  pyro/infer/traceenum_elbo.py
  tests/infer/mcmc/test_nuts.py
  tests/ops/test_contract.py
Labels: awaiting review

#1537 Remove obsolete unpacked contraction code
  pyro/infer/mcmc/util.py
  pyro/infer/traceenum_elbo.py
  pyro/ops/contract.py
  pyro/ops/packed.py
  pyro/ops/sumproduct.py
  tests/ops/einsum/test_torch_log.py
  tests/ops/test_contract.py
  tests/ops/test_packed.py
  tests/ops/test_sumproduct.py
Labels: awaiting review, refactor

#1528 Implement diagnostic stats
  pyro/ops/stats.py
  tests/ops/test_stats.py
Labels: awaiting review

#1541 Fix test_memory to ignore UserWarning with gc.getobjects()
  tests/test_memory.py
Labels: awaiting review, easy, testing

#1539 Print time taken by slowest examples in travis
  .travis.yml
Labels: awaiting review, easy, testing

#1538 Refactoring HMC class to set initial trace
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/mcmc.py
  pyro/infer/mcmc/trace_kernel.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
Labels: awaiting review

#1546 Refactor pyro.ops.contract to prepare for MAP algorithm
  pyro/ops/contract.py
  tests/ops/test_contract.py
Labels: awaiting review, easy, refactor

#1542 Fix CUDA tests on master
  pyro/ops/contract.py
  tests/infer/test_valid_models.py
Labels: awaiting review, testing

#1543 added limited support for analytic kl divergences for elbos
  docs/source/inference_algos.rst
  pyro/distributions/torch.py
  pyro/distributions/torch_distribution.py
  pyro/infer/__init__.py
  pyro/infer/trace_mean_field_elbo.py
  tests/contrib/autoguide/test_inference.py
  tests/distributions/test_mask.py
  tests/infer/test_gradient.py
  tests/infer/test_inference.py
  tests/infer/test_valid_models.py
Labels: awaiting review, enhancement

#1545 Revise baseball example with diagnostics info
  examples/baseball.py
  pyro/infer/abstract_infer.py
  pyro/infer/mcmc/logger.py
  pyro/infer/mcmc/mcmc.py
  pyro/ops/stats.py
  setup.py
  tests/ops/test_stats.py
Labels: awaiting review

#1550 Replace irange by plate in docs, examples, tests
  docs/source/primitives.rst
  pyro/__init__.py
  pyro/contrib/autoguide/__init__.py
  pyro/infer/tracegraph_elbo.py
  pyro/ops/contract.py
  pyro/poutine/indep_messenger.py
  pyro/poutine/subsample_messenger.py
  pyro/primitives.py
  pyro/util.py
  tests/contrib/autoguide/test_advi.py
  tests/infer/test_compute_downstream_costs.py
  tests/infer/test_elbo_mapdata.py
  tests/infer/test_enum.py
  tests/infer/test_jit.py
  tests/infer/test_valid_models.py
  tests/integration_tests/test_tracegraph_elbo.py
  tests/ops/test_stats.py
  tests/poutine/test_mapdata.py
  tests/poutine/test_poutines.py
  tutorial/source/svi_part_ii.ipynb
  tutorial/source/svi_part_iii.ipynb
Labels: awaiting review, refactor

#1553 Sketch mini-pyro implementation
  examples/mini_pyro.py
  tests/test_examples.py
Labels: awaiting review, documentation

#1556 Move nonstrict name functionality into contrib.autoname
  pyro/contrib/autoname/__init__.py
  pyro/contrib/autoname/scoping.py
  pyro/poutine/handlers.py
  pyro/poutine/trace_messenger.py
  tests/contrib/autoname/test_scoping.py
Labels: awaiting review

#1555 Deprecate get_all_param_names(), replace_param()
  examples/contrib/autoname/mixture.py
  examples/contrib/autoname/scoping_mixture.py
  examples/contrib/autoname/tree_data.py
  examples/eight_schools/svi.py
  examples/hmm.py
  pyro/contrib/oed/eig.py
  pyro/params/param_store.py
  tests/contrib/tracking/test_em.py
  tests/infer/test_enum.py
  tests/params/test_module.py
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/gp.ipynb
Labels: awaiting review, refactor

#1526 seed contrib.bnn with a hiddenlayer distribution
  docs/source/contrib.bnn.rst
  docs/source/index.rst
  pyro/contrib/__init__.py
  pyro/contrib/bnn/__init__.py
  pyro/contrib/bnn/hidden_layer.py
  pyro/contrib/bnn/utils.py
  tests/contrib/bnn/test_hidden_layer.py
Labels: awaiting review, enhancement

#1564 Implement ubersum adjoint algorithms: map, sample, marginal
  pyro/infer/traceenum_elbo.py
  pyro/infer/util.py
  pyro/ops/contract.py
  pyro/ops/einsum/adjoint.py
  pyro/ops/einsum/torch_log.py
  pyro/ops/einsum/torch_map.py
  pyro/ops/einsum/torch_marginal.py
  pyro/ops/einsum/torch_sample.py
  pyro/ops/einsum/util.py
  pyro/ops/packed.py
  pyro/ops/rings.py
  tests/ops/einsum/test_adjoint.py
  tests/ops/test_contract.py
Labels: awaiting review

#1569 add auto-guide support to sparse gamma def example
  examples/sparse_gamma_def.py
  pyro/contrib/autoguide/__init__.py
  tests/test_examples.py
Labels: awaiting review

#1573 Cache dataset directory on CI build
  .gitignore
  .travis.yml
  examples/air/main.py
  examples/contrib/gp/sv-dkl.py
  examples/dmm/polyphonic_data_loader.py
  examples/sparse_gamma_def.py
  examples/vae/utils/mnist_cached.py
  pyro/contrib/examples/util.py
Labels: awaiting review

#1515 PlanarFlow
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/iaf.py
  pyro/distributions/planar.py
  tests/distributions/test_flows.py
Labels: awaiting review

#1431 Update to using pytorch-1.0-rc
  .travis.yml
  Makefile
  README.md
  docs/source/conf.py
  docs/source/distributions.rst
  docs/source/primitives.rst
  examples/baseball.py
  examples/eight_schools/mcmc.py
  examples/hmm.py
  examples/vae/utils/mnist_cached.py
  pyro/contrib/autoguide/__init__.py
  pyro/contrib/examples/util.py
  pyro/contrib/gp/models/gplvm.py
  pyro/contrib/gp/models/gpr.py
  pyro/contrib/gp/models/sgpr.py
  pyro/contrib/gp/models/vgp.py
  pyro/contrib/gp/models/vsgp.py
  pyro/contrib/gp/util.py
  pyro/contrib/oed/eig.py
  pyro/distributions/__init__.py
  pyro/distributions/binomial.py
  pyro/distributions/delta.py
  pyro/distributions/diag_normal_mixture.py
  pyro/distributions/diag_normal_mixture_shared_cov.py
  pyro/distributions/half_cauchy.py
  pyro/distributions/lowrank_mvn.py
  pyro/distributions/omt_mvn.py
  pyro/distributions/relaxed_straight_through.py
  pyro/distributions/testing/rejection_gamma.py
  pyro/distributions/torch.py
  pyro/distributions/torch_distribution.py
  pyro/distributions/torch_patch.py
  pyro/distributions/util.py
  pyro/infer/elbo.py
  pyro/infer/enum.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  pyro/infer/trace_elbo.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/ops/jit.py
  pyro/poutine/broadcast_messenger.py
  pyro/poutine/indep_messenger.py
  pyro/poutine/subsample_messenger.py
  pyro/util.py
  setup.py
  tests/contrib/gp/test_conditional.py
  tests/contrib/oed/test_eig.py
  tests/contrib/oed/test_ewma.py
  tests/distributions/conftest.py
  tests/distributions/test_distributions.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
  tests/infer/test_enum.py
  tests/infer/test_jit.py
  tests/ops/test_packed.py
  tests/perf/test_benchmark.py
  tests/test_examples.py
Labels: awaiting review

#1575 Add tutorial on enumeration
  tutorial/source/enumeration.ipynb
  tutorial/source/index.rst
Labels: awaiting review, documentation

#1578 Split minipyro into contrib + example
  docs/source/contrib.minipyro.rst
  docs/source/index.rst
  examples/minipyro.py
  pyro/contrib/minipyro.py
  tests/test_examples.py
Labels: awaiting review, discussion, documentation

#1580 Speed up Dice operator using adjoint algorithms
  pyro/infer/util.py
  pyro/ops/einsum/torch_marginal.py
  tests/infer/enum_growth.ipynb
  tests/infer/test_enum.py
Labels: awaiting review

#1579 Update tensor shapes tutorial
  tests/test_examples.py
  tutorial/source/intro_part_ii.ipynb
  tutorial/source/tensor_shapes.ipynb
  tutorial/source/tracking_1d.ipynb
Labels: awaiting review, documentation

#1585 Update readme to reflect pytorch-1.0 merge into dev
  README.md
Labels: awaiting review, easy

#1583 add comments to mini-pyro
  examples/minipyro.py
  pyro/contrib/minipyro.py
Labels: awaiting review

#1587 Bump Pyro version to 0.3.0; enable version checks
  examples/air/main.py
  examples/baseball.py
  examples/bayesian_regression.py
  examples/contrib/autoname/mixture.py
  examples/contrib/autoname/scoping_mixture.py
  examples/contrib/autoname/tree_data.py
  examples/contrib/gp/sv-dkl.py
  examples/contrib/oed/ab_test.py
  examples/contrib/oed/item_response.py
  examples/contrib/oed/sequential_oed_sigmoid_lm.py
  examples/dmm/dmm.py
  examples/eight_schools/mcmc.py
  examples/eight_schools/svi.py
  examples/hmm.py
  examples/inclined_plane.py
  examples/lda.py
  examples/minipyro.py
  examples/rsa/generics.py
  examples/rsa/hyperbole.py
  examples/rsa/schelling.py
  examples/rsa/schelling_false.py
  examples/rsa/semantic_parsing.py
  examples/sparse_gamma_def.py
  examples/vae/ss_vae_M2.py
  examples/vae/vae.py
  examples/vae/vae_comparison.py
  pyro/__init__.py
  pyro/distributions/torch_patch.py
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/bo.ipynb
  tutorial/source/ekf.ipynb
  tutorial/source/enumeration.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_iii.ipynb
  tutorial/source/tensor_shapes.ipynb
  tutorial/source/tracking_1d.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review, warnings & errors

#1557 Add diagnostics method to TracePosterior class
  examples/baseball.py
  examples/eight_schools/mcmc.py
  pyro/distributions/empirical.py
  pyro/infer/abstract_infer.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/mcmc.py
  pyro/infer/mcmc/nuts.py
  tests/distributions/test_empirical.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_mcmc.py
  tests/infer/mcmc/test_nuts.py
  tests/infer/test_abstract_infer.py
  tests/perf/test_benchmark.py
Labels: awaiting review, breaking, discussion

#1589 Implement a minimal pyro.plate in minipyro.py
  examples/minipyro.py
  pyro/contrib/minipyro.py
Labels: awaiting review, easy

#1591 add fix for torch 1.0 on RTD
  pyro/distributions/torch_patch.py
Labels: documentation

#1590 Fix TraceEnum_ELBO jit tests, etc.
  pyro/distributions/torch_patch.py
  pyro/infer/util.py
  pyro/ops/einsum/paths.py
  pyro/ops/packed.py
  tests/infer/test_jit.py
  tests/ops/einsum/test_paths.py
  tests/ops/test_packed.py
Labels: awaiting review, bug, jit

#1593 Fix handling of enumerated scales when jitting
  pyro/infer/traceenum_elbo.py
  tests/test_examples.py
Labels: awaiting review, jit

#1525 Add ops stats for statistical functions
  pyro/infer/abstract_infer.py
  pyro/ops/stats.py
  tests/infer/test_abstract_infer.py
  tests/ops/test_stats.py
Labels: awaiting review, low priority

#1592 add custom objective tutorial
  tutorial/source/custom_objectives.ipynb
Labels: awaiting review

#1596 Fix jit compilation of HMM examples
  examples/hmm.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/util.py
  pyro/ops/einsum/__init__.py
  pyro/poutine/enumerate_messenger.py
  pyro/poutine/mask_messenger.py
  pyro/poutine/subsample_messenger.py
  tests/test_examples.py
Labels: awaiting review, jit
