Repository pyro-ppl/pyro, pull requests merged in 2018-12, with the labels that each got.

#1597 Modify custom objectives tutorial
  tutorial/source/custom_objectives.ipynb
  tutorial/source/index.rst
Labels: Examples, awaiting review

#1598 More jit fixes, e.g. baseball and eight_schools/svi
  examples/lda.py
  pyro/distributions/util.py
  pyro/infer/mcmc/mcmc.py
  pyro/infer/traceenum_elbo.py
  tests/infer/test_jit.py
  tests/test_examples.py
Labels: awaiting review, jit

#1602 independent -> to_event
  examples/air/air.py
  examples/baseball.py
  examples/bayesian_regression.py
  examples/contrib/oed/sequential_oed_sigmoid_lm.py
  examples/dmm/dmm.py
  examples/hmm.py
  examples/sparse_gamma_def.py
  examples/vae/ss_vae_M2.py
  examples/vae/vae.py
  examples/vae/vae_comparison.py
  pyro/contrib/autoguide/__init__.py
  pyro/contrib/glmm/glmm.py
  pyro/contrib/gp/likelihoods/binary.py
  pyro/contrib/gp/likelihoods/gaussian.py
  pyro/contrib/gp/likelihoods/multi_class.py
  pyro/contrib/gp/likelihoods/poisson.py
  pyro/contrib/gp/models/gplvm.py
  pyro/contrib/gp/models/gpr.py
  pyro/contrib/gp/models/sgpr.py
  pyro/contrib/gp/models/vgp.py
  pyro/contrib/gp/models/vsgp.py
  pyro/distributions/torch_distribution.py
  pyro/util.py
  tests/contrib/autoguide/test_advi.py
  tests/contrib/glmm/test_glmm.py
  tests/distributions/test_distributions.py
  tests/distributions/test_independent.py
  tests/distributions/test_mask.py
  tests/distributions/test_mixture.py
  tests/distributions/test_reshape.py
  tests/distributions/test_shapes.py
  tests/infer/test_elbo_mapdata.py
  tests/infer/test_enum.py
  tests/infer/test_inference.py
  tests/infer/test_jit.py
  tests/infer/test_valid_models.py
  tests/integration_tests/test_tracegraph_elbo.py
  tests/test_memory.py
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/dmm.ipynb
  tutorial/source/ss-vae.ipynb
  tutorial/source/svi_part_iii.ipynb
  tutorial/source/tensor_shapes.ipynb
  tutorial/source/tracking_1d.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review, discussion

#1601 0.3 cleanup
  pyro/infer/util.py
  tests/contrib/tracking/test_assignment.py
  tests/contrib/tracking/test_em.py
  tests/distributions/test_rejector.py
  tests/infer/test_jit.py
  tests/ops/test_contract.py
Labels: awaiting review, easy

#1599 Add block to minipyro and a few comments
  pyro/contrib/minipyro.py
  pyro/poutine/messenger.py
  pyro/poutine/runtime.py
Labels: awaiting review, documentation

#1600 rename terms in low rank mvn autoguide
  pyro/contrib/autoguide/__init__.py
Labels: awaiting review, easy

#1603 small edits to custom loss tutorial
  tutorial/source/custom_objectives.ipynb
Labels: awaiting review

#1604 Upgrade to opt_einsum 2.3
  docs/requirements.txt
  pyro/ops/einsum/__init__.py
  pyro/ops/einsum/paths.py
  setup.py
  tests/infer/test_jit.py
  tests/ops/einsum/test_paths.py
  tests/ops/einsum/test_shared.py
Labels: awaiting review, refactor

#1608 Make shape[0] -> size(0) in gp module
  pyro/contrib/gp/kernels/brownian.py
  pyro/contrib/gp/kernels/coregionalize.py
  pyro/contrib/gp/kernels/dot_product.py
  pyro/contrib/gp/kernels/isotropic.py
  pyro/contrib/gp/kernels/periodic.py
  pyro/contrib/gp/kernels/static.py
  pyro/contrib/gp/likelihoods/binary.py
  pyro/contrib/gp/likelihoods/multi_class.py
  pyro/contrib/gp/likelihoods/poisson.py
  pyro/contrib/gp/models/gplvm.py
  pyro/contrib/gp/models/gpr.py
  pyro/contrib/gp/models/model.py
  pyro/contrib/gp/models/vgp.py
  pyro/contrib/gp/models/vsgp.py
  pyro/contrib/gp/util.py
Labels: easy

#1607 Remove duplicated functional of gp
  examples/contrib/gp/sv-dkl.py
  pyro/contrib/gp/kernels/kernel.py
  pyro/contrib/gp/models/sgpr.py
  tests/contrib/gp/test_kernels.py
  tests/perf/test_benchmark.py
Labels: easy

#1610 Fix CUDA tests on dev
  tests/contrib/oed/test_eig.py
  tests/distributions/test_flows.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
  tests/infer/test_enum.py
  tests/infer/test_inference.py
  tests/infer/test_jit.py
  tests/ops/test_stats.py
Labels: awaiting review, easy

#1613 miscellaneous formatting gpmodule
  examples/contrib/gp/sv-dkl.py
  pyro/contrib/gp/kernels/__init__.py
  pyro/contrib/gp/kernels/brownian.py
  pyro/contrib/gp/kernels/coregionalize.py
  pyro/contrib/gp/kernels/dot_product.py
  pyro/contrib/gp/kernels/isotropic.py
  pyro/contrib/gp/kernels/kernel.py
  pyro/contrib/gp/kernels/periodic.py
  pyro/contrib/gp/kernels/static.py
  pyro/contrib/gp/likelihoods/__init__.py
  pyro/contrib/gp/likelihoods/gaussian.py
  pyro/contrib/gp/models/gplvm.py
  pyro/contrib/gp/models/gpr.py
  pyro/contrib/gp/models/sgpr.py
  pyro/contrib/gp/models/vgp.py
  pyro/contrib/gp/models/vsgp.py
Labels: awaiting review, easy

#1615 Modify slow running HMC unit tests to run faster
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
Labels: awaiting review, easy

#1606 Make noise is GPR/SGPR constraints.positive by default
  pyro/contrib/gp/models/gpr.py
  pyro/contrib/gp/models/sgpr.py
  tests/contrib/gp/test_models.py
Labels: awaiting review

#1618 Use pyro.plate in baseball example
  examples/baseball.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
Labels: awaiting review, easy

#1605 Add Parameterized class to `pyro.contrib.gp`
  docs/source/contrib.gp.rst
  pyro/contrib/gp/parameterized.py
  tests/contrib/gp/test_parameterized.py
Labels: awaiting review

#1619 Support varying kwargs in jit, etc.
  examples/hmm.py
  pyro/infer/__init__.py
  pyro/infer/mcmc/mcmc.py
  pyro/infer/trace_elbo.py
  pyro/infer/trace_mean_field_elbo.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/ops/jit.py
  tests/infer/test_gradient.py
  tests/infer/test_jit.py
  tests/ops/test_jit.py
  tests/test_examples.py
Labels: awaiting review, jit

#1625 Add unbatched model to hmm example
  examples/hmm.py
  tests/test_examples.py
Labels: Examples, awaiting review, documentation

#1624 Fix bug with num chain initialization in MCMC
  pyro/infer/mcmc/mcmc.py
  tests/infer/mcmc/test_mcmc.py
Labels: awaiting review

#1621 Update GP use the new Parameterized class
  examples/contrib/gp/sv-dkl.py
  examples/contrib/oed/ab_test.py
  examples/contrib/oed/gp_bayes_opt.py
  pyro/contrib/gp/kernels/brownian.py
  pyro/contrib/gp/kernels/coregionalize.py
  pyro/contrib/gp/kernels/dot_product.py
  pyro/contrib/gp/kernels/isotropic.py
  pyro/contrib/gp/kernels/kernel.py
  pyro/contrib/gp/kernels/periodic.py
  pyro/contrib/gp/kernels/static.py
  pyro/contrib/gp/likelihoods/binary.py
  pyro/contrib/gp/likelihoods/gaussian.py
  pyro/contrib/gp/likelihoods/likelihood.py
  pyro/contrib/gp/likelihoods/multi_class.py
  pyro/contrib/gp/likelihoods/poisson.py
  pyro/contrib/gp/models/gplvm.py
  pyro/contrib/gp/models/gpr.py
  pyro/contrib/gp/models/model.py
  pyro/contrib/gp/models/sgpr.py
  pyro/contrib/gp/models/vgp.py
  pyro/contrib/gp/models/vsgp.py
  pyro/contrib/gp/parameterized.py
  pyro/contrib/gp/util.py
  tests/contrib/gp/test_models.py
  tests/perf/test_benchmark.py
  tutorial/source/bo.ipynb
  tutorial/source/gp.ipynb
Labels: awaiting review, breaking

#1627 Add short tutorial on using the jit compiler
  pyro/contrib/autoguide/__init__.py
  pyro/distributions/delta.py
  tutorial/source/custom_objectives.ipynb
  tutorial/source/index.rst
  tutorial/source/jit.ipynb
Labels: awaiting review, documentation

#1628 Minor updates to the docker scripts
  docker/Dockerfile
  docker/install.sh
Labels: awaiting review

#1626 Update pytorch nightly wheel for CI
  .travis.yml
  setup.py
Labels: awaiting review

#1623 bayesian regression tutorial part i
  setup.py
  tutorial/source/bayesian_regression.ipynb
Labels: awaiting review

#1632 Tiny attempt to overcome a jit error in GP
  pyro/contrib/gp/kernels/kernel.py
  pyro/contrib/gp/models/model.py
Labels: awaiting review, easy

#1633 Minor fixes to tqdm progress bars used for MCMC logging
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/logger.py
  pyro/infer/mcmc/mcmc.py
Labels: awaiting review, easy

#1629 Add effect handler tutorial
  pyro/poutine/runtime.py
  tutorial/source/effect_handlers.ipynb
  tutorial/source/index.rst
Labels: awaiting review, documentation

#1637 Make scrub to clean up tutorials
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/bo.ipynb
  tutorial/source/effect_handlers.ipynb
  tutorial/source/gp.ipynb
Labels: awaiting review, documentation, easy

#1635 Further edits to the intro tutorials
  tutorial/source/intro_part_i.ipynb
  tutorial/source/intro_part_ii.ipynb
Labels: awaiting review, documentation

#1634 Add HMC run to the JIT tutorial
  pyro/infer/mcmc/logger.py
  tutorial/source/jit.ipynb
Labels: awaiting review

#1639 Update torch wheel on travis CI
  .travis.yml
  setup.py
Labels: easy

#1642 Update effect handler tutorial
  pyro/contrib/minipyro.py
  tutorial/source/effect_handlers.ipynb
Labels: awaiting review, documentation

#1636 Implement forward-filter backward-sample poutine
  docs/source/inference_algos.rst
  pyro/infer/__init__.py
  pyro/infer/discrete.py
  pyro/ops/contract.py
  tests/infer/test_discrete.py
  tutorial/source/enumeration.ipynb
Labels: awaiting review, enhancement

#1643 Fix an important bug in gp likelihood
  examples/contrib/gp/sv-dkl.py
  pyro/contrib/gp/likelihoods/binary.py
  pyro/contrib/gp/likelihoods/gaussian.py
  pyro/contrib/gp/likelihoods/multi_class.py
  pyro/contrib/gp/likelihoods/poisson.py
  pyro/contrib/gp/models/sgpr.py
  tutorial/source/gp.ipynb
Labels: awaiting review, bug

#1645 Fix the flakiness of oed example
  examples/contrib/oed/ab_test.py
  examples/contrib/oed/gp_bayes_opt.py
  tests/test_examples.py
Labels: awaiting review

#1646 Fix infer_discrete to work under the PyTorch jit
  pyro/distributions/torch_patch.py
  pyro/infer/discrete.py
  pyro/ops/einsum/adjoint.py
  pyro/ops/einsum/torch_sample.py
  pyro/util.py
  tests/infer/test_jit.py
Labels: awaiting review, jit

#1649 Use consistent marginal implementation for all TracePosterior subclasses
  pyro/infer/abstract_infer.py
  pyro/infer/mcmc/mcmc.py
Labels: awaiting review, discussion

#1650 Provide arg in MCMC to turn off progress bar and diagnostics
  pyro/infer/mcmc/logger.py
  pyro/infer/mcmc/mcmc.py
  tests/infer/mcmc/test_hmc.py
Labels: awaiting review, easy

#1651 Fix eight schools example with num_chains > 1
  examples/eight_schools/mcmc.py
Labels: awaiting review, easy

#1630 Bayesian Regression Part II
  tutorial/source/bayesian_regression_ii.ipynb
  tutorial/source/index.rst
Labels: awaiting review

#1653 Switch config_enumerate default from sequential to parallel
  examples/contrib/autoname/scoping_mixture.py
  pyro/contrib/autoguide/__init__.py
  pyro/infer/discrete.py
  pyro/infer/enum.py
  pyro/infer/mcmc/hmc.py
  tests/infer/mcmc/test_valid_models.py
  tests/infer/test_discrete.py
  tests/infer/test_enum.py
  tests/infer/test_gradient.py
  tests/infer/test_valid_models.py
  tutorial/source/enumeration.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/tensor_shapes.ipynb
Labels: awaiting review, breaking

#1652 Add infer_discrete section to GMM tutorial
  tutorial/source/gmm.ipynb
Labels: Examples, awaiting review, documentation

#1654 Enable test_jit.py under CUDA, which now passes
  tests/infer/test_jit.py
Labels: awaiting review, easy, jit

#1655 Update setup and README to use PyTorch 1.0
  .travis.yml
  README.md
  setup.py
Labels: awaiting review

#1658 readme edits
  README.md
Labels: awaiting review, easy

#1657 Minor fixes to tutorials
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/jit.ipynb
Labels: awaiting review

#1659 Fix the warning on dropout
  examples/dmm/dmm.py
Labels: awaiting review, easy

#1660 Bump opt_einsum to 2.3.2, remove patch
  docs/requirements.txt
  pyro/distributions/torch_patch.py
  setup.py
Labels: awaiting review, easy

#1662 remove bad notes from hmm example
  examples/hmm.py
Labels: awaiting review

#1661 fix html rendering for ekf tutorial
  tutorial/source/ekf.ipynb
Labels: awaiting review, easy

#1631 Tutorial on using GPLVM in single-cell dataset
  pyro/contrib/gp/__init__.py
  pyro/contrib/gp/parameterized.py
  tutorial/source/gplvm.ipynb
  tutorial/source/index.rst
Labels: Examples, awaiting review, help wanted

#1663 Enable all slow hmc jit tests
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
  tests/test_examples.py
Labels: awaiting review

#1664 improve discussion in gplvm tutorial
  tutorial/source/bayesian_regression_ii.ipynb
  tutorial/source/gplvm.ipynb
Labels: awaiting review

#1669 Switch to torch.finfo now that it is released
  pyro/ops/rings.py
Labels: awaiting review, easy

#1667 Refactor polyphonic data loader to load other music datasets
  examples/dmm/dmm.py
  examples/dmm/polyphonic_data_loader.py
  examples/hmm.py
Labels: awaiting review

#1666 Add option to use sv-dkl for Binary MNIST
  examples/contrib/gp/sv-dkl.py
  tests/test_examples.py
  tutorial/source/dkl.rst
Labels: awaiting review

#1670 Use native inverse for large matrices in rinverse
  pyro/ops/linalg.py
Labels: awaiting response

#1672 clarify args in custom loss tutorial
  tutorial/source/RSA-hyperbole.ipynb
  tutorial/source/RSA-implicature.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/custom_objectives.ipynb
  tutorial/source/effect_handlers.ipynb
  tutorial/source/ekf.ipynb
  tutorial/source/enumeration.ipynb
  tutorial/source/intro_part_i.ipynb
  tutorial/source/intro_part_ii.ipynb
  tutorial/source/jit.ipynb
Labels: awaiting review, easy

#1680 Minor CUDA related fixes
  examples/dmm/polyphonic_data_loader.py
  tests/test_examples.py
Labels: awaiting review

#1678 Resolve the slowness of HMC during init adaptation phase
  pyro/infer/mcmc/adaptation.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  tests/infer/mcmc/test_hmc.py
Labels: awaiting review
