Repository pyro-ppl/pyro, pull requests merged in 2018-04, with the labels that each got.

#965 Add contextlib2 to docs dependency on travis
  docs/requirements.txt
Labels: awaiting review

#968 refresh dmm.py
  examples/dmm/dmm.py
  examples/dmm/polyphonic_data_loader.py
Labels: awaiting review

#969 Adding implementation for EmpiricalDistribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/empirical.py
  pyro/distributions/util.py
  pyro/infer/abstract_infer.py
  pyro/util.py
  tests/distributions/test_empirical.py
Labels: awaiting review

#970 Fix bayesian regression example and re-enable testing
  examples/bayesian_regression.py
  tests/test_examples.py
Labels: awaiting review, easy

#972 Add links to PyTorch optimizers in sphinx docs
  docs/source/pyro.optim.txt
  pyro/optim/__init__.py
Labels: awaiting review, easy

#974 Add .median(), .quantiles() to ADVI implementations
  pyro/infer/advi.py
  tests/infer/test_advi.py
Labels: awaiting review

#975 Programmatically wrap all PyTorch optimizers
  docs/source/pyro.optim.txt
  pyro/optim/__init__.py
  tests/optim/test_optim.py
Labels: awaiting review

#976 Update some tutorials to use new PyTorch semantics
  examples/bayesian_regression.py
  examples/vae.py
  examples/vae_comparison.py
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/vae.ipynb
Labels: easy

#967 Refactor Dice towards support for message passing
  pyro/infer/traceenum_elbo.py
  pyro/infer/util.py
Labels: awaiting review

#955 Revise GP docs
  docs/source/contrib.gp.rst
  docs/source/primitives.rst
  pyro/contrib/__init__.py
  pyro/contrib/gp/kernels/__init__.py
  pyro/contrib/gp/kernels/brownian.py
  pyro/contrib/gp/kernels/dot_product.py
  pyro/contrib/gp/kernels/isotropic.py
  pyro/contrib/gp/kernels/kernel.py
  pyro/contrib/gp/kernels/periodic.py
  pyro/contrib/gp/kernels/static.py
  pyro/contrib/gp/likelihoods/binary.py
  pyro/contrib/gp/likelihoods/gaussian.py
  pyro/contrib/gp/likelihoods/likelihood.py
  pyro/contrib/gp/likelihoods/multi_class.py
  pyro/contrib/gp/models/gpr.py
  pyro/contrib/gp/models/model.py
  pyro/contrib/gp/models/sgpr.py
  pyro/contrib/gp/models/svgp.py
  pyro/contrib/gp/models/vgp.py
  pyro/contrib/gp/util.py
  pyro/infer/advi.py
  tests/contrib/gp/test_kernels.py
Labels: awaiting review

#978 Add BO tutorial
  pyro/contrib/gp/kernels/isotropic.py
  tutorial/source/bo.ipynb
  tutorial/source/index.rst
Labels: awaiting review

#984 refresh svi part i tutorial
  tutorial/source/svi_part_i.ipynb
Labels: awaiting review

#985 use .mask in air
  examples/air/air.py
Labels: awaiting review

#989 refresh svi iii tutorial
  tutorial/source/svi_part_iii.ipynb
Labels: awaiting review

#992 Update contrib.named examples
  examples/contrib/named/mixture.py
  examples/contrib/named/tree_data.py
Labels: awaiting review

#998 AIR example fixes
  examples/air/air.py
  examples/air/main.py
Labels: awaiting review

#994 Enable HMC tests on constrained distributions with step size adaptation
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
Labels: awaiting review

#993 Move example utils into Pyro pip package
  .gitignore
  examples/air/viz.py
  examples/bayesian_regression.py
  examples/dmm/dmm.py
  examples/schelling.py
  examples/schelling_false.py
  examples/vae/ss_vae_M2.py
  examples/vae/utils/__init__.py
  examples/vae/utils/custom_mlp.py
  examples/vae/utils/mnist_cached.py
  examples/vae/utils/vae_plots.py
  examples/vae/vae.py
  examples/vae/vae_comparison.py
  pyro/contrib/examples/__init__.py
  pyro/contrib/examples/util.py
  setup.py
Labels: Anchor examples, awaiting review

#1000 Add a decorator interface to poutine
  docs/source/poutine.rst
  docs/source/pyro.poutine.txt
  pyro/infer/search.py
  pyro/infer/traceenum_elbo.py
  pyro/poutine/__init__.py
  pyro/poutine/block_poutine.py
  pyro/poutine/condition_poutine.py
  pyro/poutine/enumerate_poutine.py
  pyro/poutine/escape_poutine.py
  pyro/poutine/indep_poutine.py
  pyro/poutine/infer_config_poutine.py
  pyro/poutine/lift_poutine.py
  pyro/poutine/poutine.py
  pyro/poutine/replay_poutine.py
  pyro/poutine/trace_poutine.py
  pyro/poutine/util.py
  tests/poutine/test_poutines.py
Labels: awaiting review, usability

#1006 Rename pyro.infer.advi -> pyro.contrib.autoguide
  docs/source/contrib.autoguide.rst
  docs/source/contrib.rst
  docs/source/inference_algos.rst
  pyro/contrib/autoguide/__init__.py
  pyro/contrib/autoguide/advi.py
  pyro/infer/__init__.py
  tests/contrib/autoguide/test_advi.py
  tests/contrib/autoguide/test_inference.py
  tests/infer/test_valid_models.py
Labels: awaiting review

#1008 Fix setup.py packages list
  .travis.yml
  setup.py
Labels: bug, high priority

#1011 Updating docker file to build latest PyTorch master
  docker/Dockerfile
  docker/Makefile
  docker/install.sh
Labels: awaiting review

#990 update svi i example
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_iii.ipynb
Labels: awaiting response

#1015 Clean up _DIM_ALLOCATOR in case of error inside iarange.__enter__
  pyro/__init__.py
  tests/poutine/test_poutines.py
Labels: awaiting review

#987 Use GP to classify MNIST dataset
  examples/contrib/gp/sv-dkl.py
  pyro/contrib/gp/likelihoods/binary.py
  pyro/contrib/gp/likelihoods/gaussian.py
  pyro/contrib/gp/likelihoods/likelihood.py
  pyro/contrib/gp/likelihoods/multi_class.py
  pyro/contrib/gp/models/gpr.py
  pyro/contrib/gp/models/model.py
  pyro/contrib/gp/models/sgpr.py
  pyro/contrib/gp/models/svgp.py
  pyro/contrib/gp/models/vgp.py
  pyro/contrib/gp/util.py
  pyro/distributions/delta.py
  pyro/distributions/iaf.py
  tests/contrib/gp/test_conditional.py
  tests/contrib/gp/test_likelihoods.py
  tests/contrib/gp/test_models.py
Labels: awaiting review, documentation

#1016 Rename .reshape(s,n) -> .expand_by(s).independent(n)
  examples/air/air.py
  examples/bayesian_regression.py
  examples/dmm/dmm.py
  examples/vae/ss_vae_M2.py
  examples/vae/vae.py
  examples/vae/vae_comparison.py
  pyro/__init__.py
  pyro/contrib/autoguide/advi.py
  pyro/contrib/gp/likelihoods/binary.py
  pyro/contrib/gp/likelihoods/gaussian.py
  pyro/contrib/gp/likelihoods/multi_class.py
  pyro/contrib/gp/models/gpr.py
  pyro/contrib/gp/models/sgpr.py
  pyro/contrib/gp/models/svgp.py
  pyro/contrib/gp/models/vgp.py
  pyro/distributions/torch_distribution.py
  pyro/util.py
  tests/contrib/autoguide/test_advi.py
  tests/contrib/autoguide/test_inference.py
  tests/distributions/test_mask.py
  tests/distributions/test_reshape.py
  tests/distributions/test_shapes.py
  tests/infer/test_compute_downstream_costs.py
  tests/infer/test_elbo_mapdata.py
  tests/infer/test_enum.py
  tests/infer/test_gradient.py
  tests/infer/test_inference.py
  tests/infer/test_util.py
  tests/infer/test_valid_models.py
  tests/integration_tests/test_tracegraph_elbo.py
  tests/test_memory.py
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/dmm.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/svi_part_iii.ipynb
  tutorial/source/tensor_shapes.ipynb
Labels: awaiting review

#1018 Add support for ELBO object as loss arg to SVI
  pyro/infer/__init__.py
  pyro/infer/svi.py
  pyro/infer/trace_elbo.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/infer/util.py
  tests/infer/test_enum.py
  tests/infer/test_inference.py
Labels: awaiting review

#1020 Update tests to use SVI(loss=Trace*_ELBO())
  tests/contrib/autoguide/test_advi.py
  tests/contrib/autoguide/test_inference.py
  tests/contrib/gp/test_models.py
  tests/infer/test_elbo_mapdata.py
  tests/infer/test_gradient.py
  tests/infer/test_inference.py
  tests/infer/test_valid_models.py
  tests/integration_tests/test_conjugate_gaussian_models.py
  tests/integration_tests/test_tracegraph_elbo.py
  tests/optim/test_optim.py
  tests/perf/test_benchmark.py
  tests/test_memory.py
Labels: awaiting review

#1021 Update examples to use SVI(..., loss=Trace*_ELBO())
  examples/air/main.py
  examples/bayesian_regression.py
  examples/contrib/gp/sv-dkl.py
  examples/contrib/named/mixture.py
  examples/contrib/named/tree_data.py
  examples/dmm/dmm.py
  examples/vae/ss_vae_M2.py
  examples/vae/vae.py
  examples/vae/vae_comparison.py
Labels: awaiting review

#1022 Update tutorials to use SVI(..., Trace*_ELBO(...))
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/dmm.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/intro_part_ii.ipynb
  tutorial/source/ss-vae.ipynb
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_iii.ipynb
  tutorial/source/tensor_shapes.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review

#1025 Update 0.2 logo
  README.md
  docs/source/_static/img/pyro_logo_with_text.png
Labels: easy

#1012 Add Poisson likelihood to GP module
  docs/source/contrib.gp.rst
  pyro/contrib/gp/likelihoods/__init__.py
  pyro/contrib/gp/likelihoods/binary.py
  pyro/contrib/gp/likelihoods/poisson.py
  tests/contrib/gp/test_likelihoods.py
Labels: awaiting review, enhancement

#1024 update ss-vae
  examples/vae/ss_vae_M2.py
  examples/vae/utils/custom_mlp.py
  examples/vae/utils/mnist_cached.py
  examples/vae/utils/vae_plots.py
  tests/test_examples.py
Labels: Anchor examples, awaiting review

#1029 Use `mask` rather than `poutine.scale` in AIR tutorial.
  tutorial/source/air.ipynb
Labels: awaiting review

#1031 Avoid namespace pollution in top level module
  docs/source/primitives.rst
  pyro/__init__.py
  pyro/contrib/gp/likelihoods/likelihood.py
  pyro/contrib/gp/models/gpr.py
  pyro/contrib/gp/models/model.py
  pyro/contrib/gp/models/sgpr.py
  pyro/contrib/gp/models/svgp.py
  pyro/contrib/gp/models/vgp.py
  pyro/contrib/gp/util.py
  pyro/infer/__init__.py
  pyro/params/__init__.py
  pyro/params/param_store.py
  pyro/primitives.py
  tests/contrib/gp/test_models.py
Labels: awaiting review

#1032 Upgrade to latest PyTorch master
  README.md
  pyro/__init__.py
  pyro/params/__init__.py
  pyro/primitives.py
Labels: awaiting review

#1035 regression tutorial tweak
  tutorial/source/bayesian_regression.ipynb
Labels: easy

#1017 Add mean function for GP models
  pyro/contrib/gp/models/gpr.py
  pyro/contrib/gp/models/model.py
  pyro/contrib/gp/models/sgpr.py
  pyro/contrib/gp/models/svgp.py
  pyro/contrib/gp/models/vgp.py
  tests/contrib/gp/test_likelihoods.py
  tests/contrib/gp/test_models.py
Labels: awaiting review

#1005 Add regression test for GP
  pyro/contrib/gp/likelihoods/binary.py
  pyro/contrib/gp/likelihoods/gaussian.py
  pyro/contrib/gp/likelihoods/multi_class.py
  pyro/contrib/gp/likelihoods/poisson.py
  pyro/distributions/iaf.py
  pyro/distributions/util.py
  tests/perf/test_benchmark.py
Labels: awaiting review, testing

#1038 Add circular von Mises distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/von_mises.py
  tests/distributions/conftest.py
  tests/distributions/test_von_mises.py
Labels: awaiting review

#1027 Allow auxiliary sites in guide but not model; simplify ADVI
  pyro/contrib/autoguide/advi.py
  pyro/infer/trace_elbo.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/infer/util.py
  pyro/util.py
  tests/contrib/autoguide/test_advi.py
Labels: awaiting review

#1034 Refactor examples testing
  tests/test_examples.py
Labels: awaiting review

#1036 Simplify ADVI interface (part 2)
  docs/source/contrib.autoguide.rst
  pyro/contrib/autoguide/__init__.py
  pyro/contrib/autoguide/advi.py
  tests/contrib/autoguide/test_advi.py
  tests/contrib/autoguide/test_inference.py
Labels: awaiting review

#1046 fix a few failures in make test-cuda
  tests/infer/test_enum.py
Labels: awaiting review

#1049 fix ctx usage in omt mvn
  pyro/distributions/omt_mvn.py
Labels: awaiting review, easy

#1039 update gp tutorial
  tutorial/source/gp.ipynb
Labels: awaiting review

#1004 Update poutine aliases to be usable as decorators and context managers
  examples/air/main.py
  examples/dmm/dmm.py
  examples/vae/ss_vae_M2.py
  pyro/__init__.py
  pyro/infer/enum.py
  pyro/infer/importance.py
  pyro/infer/trace_elbo.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/poutine/__init__.py
  pyro/poutine/replay_poutine.py
  tests/infer/test_compute_downstream_costs.py
  tests/integration_tests/test_tracegraph_elbo.py
  tests/poutine/test_mapdata.py
  tests/poutine/test_poutines.py
  tests/test_memory.py
Labels: awaiting review, usability

#1053 Patch torch to implement cpu->cuda->cpu workarounds
  pyro/distributions/__init__.py
  pyro/distributions/torch_patch.py
  tests/common.py
  tests/distributions/test_cuda.py
Labels: awaiting review

#1052 Testing for CUDA compatibility
  Makefile
  pyro/infer/mcmc/nuts.py
  pyro/nn/auto_reg_nn.py
  pyro/primitives.py
  pyro/util.py
  tests/contrib/autoguide/test_inference.py
  tests/contrib/gp/test_models.py
  tests/distributions/test_omt_mvn.py
  tests/distributions/test_rejector.py
  tests/distributions/test_von_mises.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
  tests/infer/test_gradient.py
  tests/infer/test_inference.py
  tests/test_examples.py
Labels: awaiting review

#1055 Binomial distribution with vectorized total_count
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/binomial.py
  pyro/distributions/torch.py
  tests/distributions/conftest.py
Labels: awaiting review

#1054 Drop support for string value of loss arg to SVI
  pyro/contrib/autoguide/advi.py
  pyro/contrib/gp/models/model.py
  pyro/infer/elbo.py
  pyro/infer/svi.py
  tests/infer/test_inference.py
Labels: awaiting review

#1056 Update to PyTorch 0.4
  README.md
Labels: awaiting review

#1050 Updating the VAE tutorial
  examples/vae/vae.py
  tutorial/source/_static/img/vae_plots/test_elbo_vae.png
  tutorial/source/vae.ipynb
Labels: awaiting review

#1057 Update GP related for 0.2
  docs/source/contrib.gp.rst
  docs/source/distributions.rst
  examples/contrib/gp/sv-dkl.py
  pyro/contrib/gp/kernels/kernel.py
  pyro/contrib/gp/models/__init__.py
  pyro/contrib/gp/models/gpr.py
  pyro/contrib/gp/models/model.py
  pyro/contrib/gp/models/sgpr.py
  pyro/contrib/gp/models/vgp.py
  pyro/contrib/gp/models/vsgp.py
  pyro/distributions/__init__.py
  pyro/distributions/lowrank_mvn.py
  pyro/distributions/util.py
  tests/contrib/gp/test_likelihoods.py
  tests/contrib/gp/test_models.py
  tests/distributions/conftest.py
  tests/distributions/test_distributions.py
  tests/distributions/test_lowrank_mvn.py
  tutorial/source/bo.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_ii.ipynb
  tutorial/source/svi_part_iii.ipynb
Labels: awaiting review

#1060 Improve support for custom losses in SVI
  pyro/infer/svi.py
  pyro/infer/trace_elbo.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/params/param_store.py
  pyro/poutine/__init__.py
  pyro/poutine/trace_poutine.py
  tests/poutine/test_poutines.py
Labels: awaiting review

#1064 Rename all remaining poutine files and modules to messenger
  docs/source/pyro.poutine.txt
  pyro/poutine/__init__.py
  pyro/poutine/block_messenger.py
  pyro/poutine/condition_messenger.py
  pyro/poutine/enumerate_messenger.py
  pyro/poutine/escape_messenger.py
  pyro/poutine/indep_messenger.py
  pyro/poutine/infer_config_messenger.py
  pyro/poutine/lift_messenger.py
  pyro/poutine/messenger.py
  pyro/poutine/replay_messenger.py
  pyro/poutine/scale_messenger.py
  pyro/poutine/trace_messenger.py
  pyro/poutine/util.py
  pyro/primitives.py
  pyro/util.py
  tests/poutine/test_poutines.py
Labels: awaiting review, easy

#1065 Remove unused utilities
  pyro/shim.py
  pyro/util.py
Labels: awaiting review

#1070 Make poutine aliases appear in sphinx
  docs/source/advanced.rst
  docs/source/index.rst
  docs/source/poutine.rst
  docs/source/pyro.poutine.txt
  pyro/poutine/__init__.py
Labels: awaiting review, documentation, easy

#1066 Move some pyro internals into poutine.runtime
  pyro/params/__init__.py
  pyro/params/param_store.py
  pyro/poutine/__init__.py
  pyro/poutine/escape_messenger.py
  pyro/poutine/indep_messenger.py
  pyro/poutine/messenger.py
  pyro/poutine/runtime.py
  pyro/poutine/util.py
  pyro/primitives.py
  pyro/util.py
  tests/poutine/test_poutines.py
Labels: awaiting review, easy

#1062 add clipped nn to docs
  docs/source/pyro.nn.txt
  pyro/nn/clipped_nn.py
Labels: documentation

#1073 fix tutorials so they render properly in html
  tutorial/source/bo.ipynb
  tutorial/source/dmm.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/svi_part_ii.ipynb
  tutorial/source/svi_part_iii.ipynb
Labels: awaiting review

#1061 Update API usage in language intro tutorials
  pyro/__init__.py
  pyro/infer/svi.py
  tutorial/source/intro_part_i.ipynb
  tutorial/source/intro_part_ii.ipynb
Labels: awaiting review, documentation

#1068 Rename pyro.contrib.autoguide.advi to pyro.contrib.autoguide
  docs/source/contrib.autoguide.rst
  docs/source/contrib.rst
  pyro/contrib/autoguide/__init__.py
  pyro/contrib/autoguide/advi.py
  tests/contrib/autoguide/test_advi.py
  tests/contrib/autoguide/test_inference.py
Labels: awaiting review

#1078 Fix sphinx links to pyro primitives
  docs/source/primitives.rst
Labels: awaiting review, documentation, easy

#1077 Minor cleanups for HMC
  pyro/infer/mcmc/__init__.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
Labels: awaiting review, usability

#1075 Update documentation of Trace
  docs/source/conf.py
  pyro/poutine/trace.py
Labels: awaiting review, documentation

#1074 Sort imports via isort
  Makefile
  docs/source/conf.py
  examples/air/air.py
  examples/air/main.py
  examples/dmm/polyphonic_data_loader.py
  examples/inclined_plane.py
  examples/vae/ss_vae_M2.py
  examples/vae/utils/custom_mlp.py
  examples/vae/utils/mnist_cached.py
  examples/vae/vae_comparison.py
  profiler/distributions.py
  pyro/__init__.py
  pyro/contrib/__init__.py
  pyro/contrib/gp/__init__.py
  pyro/contrib/gp/kernels/__init__.py
  pyro/contrib/gp/kernels/kernel.py
  pyro/contrib/gp/kernels/periodic.py
  pyro/contrib/gp/models/__init__.py
  pyro/contrib/gp/models/sgpr.py
  pyro/distributions/__init__.py
  pyro/distributions/binomial.py
  pyro/distributions/empirical.py
  pyro/distributions/testing/rejection_exponential.py
  pyro/distributions/util.py
  pyro/docutil.py
  pyro/infer/abstract_infer.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  pyro/optim/__init__.py
  pyro/optim/optim.py
  pyro/poutine/__init__.py
  pyro/poutine/escape_messenger.py
  pyro/poutine/messenger.py
  pyro/poutine/runtime.py
  pyro/poutine/trace.py
  pyro/poutine/trace_messenger.py
  pyro/primitives.py
  setup.cfg
  setup.py
  tests/contrib/gp/test_conditional.py
  tests/contrib/gp/test_kernels.py
  tests/contrib/gp/test_likelihoods.py
  tests/contrib/gp/test_models.py
  tests/distributions/test_lowrank_mvn.py
  tests/distributions/test_omt_mvn.py
  tests/distributions/test_rejector.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_nuts.py
  tests/infer/test_enum.py
  tests/perf/test_benchmark.py
Labels: awaiting review

#1085 fix docstring in primitives.py
  pyro/primitives.py
Labels: easy

#1076 ss-vae tutorial updates
  tutorial/source/ss-vae.ipynb
Labels: Anchor examples, awaiting review, documentation

#1081 custom css for rtd
  docs/source/conf.py
Labels: awaiting review, easy, website

#1079 Add posterior predictive class to AbstractInfer
  pyro/infer/__init__.py
  pyro/infer/abstract_infer.py
  tests/infer/test_abstract_infer.py
Labels: awaiting review

#1083 Fix many links warned/broken in tutorials
  setup.py
  tutorial/Makefile
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/bo.ipynb
  tutorial/source/conf.py
  tutorial/source/dmm.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/intro_part_i.ipynb
  tutorial/source/intro_part_ii.ipynb
  tutorial/source/ss-vae.ipynb
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_ii.ipynb
  tutorial/source/svi_part_iii.ipynb
  tutorial/source/tensor_shapes.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review, documentation

#1086 Add docstring for validation check
  pyro/primitives.py
Labels: awaiting review, easy

#1087 Move handlers into their own file and clean up poutine namespace
  docs/source/poutine.rst
  docs/source/pyro.poutine.txt
  pyro/infer/enum.py
  pyro/poutine/__init__.py
  pyro/poutine/condition_messenger.py
  pyro/poutine/handlers.py
  pyro/poutine/runtime.py
  pyro/poutine/trace_messenger.py
  pyro/poutine/trace_struct.py
  pyro/primitives.py
  tests/test_memory.py
Labels: awaiting review, documentation, usability

#1091 Add sphinx docs for Rejector; fix distributions links
  docs/source/distributions.rst
  pyro/distributions/torch.py
Labels: awaiting review, documentation, easy

#1090 Point to PyTorch official release in CI
  .travis.yml
  README.md
Labels: awaiting review

#1089 Removing clipped{sigmoid|softmax} since baseline pytorch primitives are stable enough
  docs/source/pyro.nn.txt
  examples/vae/ss_vae_M2.py
  examples/vae/utils/custom_mlp.py
  pyro/nn/__init__.py
  pyro/nn/clipped_nn.py
  tests/nn/__init__.py
  tests/nn/conftest.py
  tests/nn/test_clipped_nn.py
Labels: Anchor examples, awaiting review

#1092 Update Poutine docs
  docs/source/poutine.rst
  pyro/poutine/block_messenger.py
  pyro/poutine/handlers.py
  pyro/poutine/messenger.py
  pyro/poutine/runtime.py
Labels: awaiting review, documentation

#1095 Fix broken tutorial links
  docs/source/installation.rst
  tutorial/source/ss-vae.ipynb
  tutorial/source/vae.ipynb
Labels: easy

#1101 small miscellaneous doc/tutoria/etc edits
  README.md
  docker/Dockerfile
  docker/README.md
  docs/source/parameters.rst
  docs/source/pyro.optim.txt
  examples/vae/utils/mnist_cached.py
  examples/vae/vae_comparison.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  pyro/infer/util.py
  pyro/poutine/block_messenger.py
  pyro/poutine/handlers.py
  pyro/poutine/messenger.py
  pyro/poutine/trace_messenger.py
  pyro/poutine/trace_struct.py
  pyro/poutine/util.py
  tests/common.py
  tutorial/source/intro_part_i.ipynb
Labels: awaiting review, easy

#1102 Correct caption for image in VAE tutorial
  tutorial/source/vae.ipynb
Labels: awaiting review, bug

#1107 rm tag+commit versioning in docs
  docs/source/conf.py
Labels: easy

#1105 Use internally hosted baseball dataset for example
  examples/baseball.py
Labels: awaiting review

#1108 fix broken rtd
  docs/source/conf.py
Labels: bug
