Repository pyro-ppl/pyro, pull requests merged in 2019-09, with the labels that each got.

#2027 add IMQSteinKernel
  pyro/infer/__init__.py
  pyro/infer/svgd.py
  tests/infer/test_svgd.py
Labels: awaiting review

#1917 Improve numerical stability of MixtureOfDiagNormals using logsumexp
  pyro/distributions/diag_normal_mixture.py
  pyro/distributions/diag_normal_mixture_shared_cov.py
  pyro/distributions/gaussian_scale_mixture.py
Labels: awaiting review

#2030 Update cloudfront link for new S3 bucket
  examples/baseball.py
  examples/dmm/polyphonic_data_loader.py
  examples/mixed_hmm/seal_data.py
  examples/sparse_gamma_def.py
  pyro/contrib/examples/util.py
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/bayesian_regression_ii.ipynb
Labels: awaiting review, easy

#2032 Use functools.update_wrapper in torch_patch
  pyro/distributions/torch_patch.py
Labels: awaiting review, easy

#2029 fix docstring in lr schedulers
  pyro/optim/lr_scheduler.py
Labels: awaiting review, documentation, easy

#2036 Add ops module to pyro.generic interface
  examples/minipyro.py
  pyro/generic.py
  tests/contrib/test_minipyro.py
Labels: awaiting review

#2039 Use torch.jit.script in DiscreteHMM
  examples/hmm.py
  pyro/distributions/hmm.py
Labels: awaiting review, easy

#2043 Implement KL divergence for delta and independent distributions
  pyro/distributions/__init__.py
  pyro/distributions/kl.py
  pyro/distributions/torch.py
  tests/distributions/test_kl.py
Labels: awaiting review

#2044 Avoid in-place ops in a few places
  examples/hmm.py
  pyro/distributions/util.py
  pyro/distributions/zero_inflated_poisson.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/util.py
  pyro/ops/packed.py
  pyro/ops/rings.py
Labels: awaiting review, refactor

#1919 Conditional MADE Autoregressive Network
  pyro/nn/__init__.py
  pyro/nn/auto_reg_nn.py
  pyro/nn/dense_nn.py
  tests/nn/test_autoregressive.py
Labels: awaiting review

#1937 Transform and TransformedDistribution that can forward optional keyword args
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/conditional.py
  pyro/distributions/torch_transform.py
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/permute.py
  pyro/distributions/transforms/planar.py
  tests/distributions/test_flows.py
Labels: awaiting review

#2045 Implement CRPS for empirical distributions
  pyro/ops/stats.py
  tests/ops/test_stats.py
Labels: awaiting review
