Repository pyro-ppl/pyro, pull requests merged in 2019-03, with the labels that each got.

#1783 elbo with tail adaptive f-divergence
  docs/source/inference_algos.rst
  pyro/infer/__init__.py
  pyro/infer/elbo.py
  pyro/infer/trace_mean_field_elbo.py
  pyro/infer/trace_tail_adaptive_elbo.py
  pyro/infer/util.py
  tests/infer/test_inference.py
  tests/infer/test_valid_models.py
Labels: awaiting review, enhancement

#1785 Fix shape issue with JITed masked distributions
  pyro/distributions/util.py
  pyro/ops/packed.py
  tests/infer/test_jit.py
Labels: awaiting review

#1790 Add a pyro.generic module to enable backend-agnostic Pyro models
  docs/source/index.rst
  docs/source/pyro.generic.rst
  examples/minipyro.py
  pyro/generic.py
  tests/test_examples.py
Labels: awaiting review, discussion

#1794 Add a Trace_ELBO wrapper to minipyro
  examples/minipyro.py
  pyro/contrib/minipyro.py
  pyro/generic.py
Labels: awaiting review, easy

#1796 Subsample pyro.param inside plate if event_dim is given
  pyro/params/param_store.py
  pyro/poutine/subsample_messenger.py
  pyro/primitives.py
  tests/infer/test_gradient.py
  tests/infer/test_valid_models.py
Labels: awaiting review
