Repository pyro-ppl/pyro, pull requests merged in 2019-02, with the labels that each got.

#1731 fix missing docstring
  docs/source/distributions.rst
Labels: awaiting review

#1724 Add assert_close to tests.common
  tests/common.py
  tests/distributions/test_conjugate.py
  tests/distributions/test_zip.py
Labels: awaiting review, easy, testing

#1732 Add mixed-effect HMM example with seal data
  .gitignore
  examples/mixed_hmm/README.md
  examples/mixed_hmm/__init__.py
  examples/mixed_hmm/experiment.py
  examples/mixed_hmm/model.py
  examples/mixed_hmm/seal_data.py
  tests/test_examples.py
Labels: Examples, awaiting review

#1734 Implement Dirichlet-Multinomial distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/conjugate.py
  pyro/distributions/torch_patch.py
  tests/distributions/conftest.py
  tests/distributions/test_conjugate.py
Labels: awaiting review

#1735 Update mixed HMM readme
  examples/mixed_hmm/README.md
Labels: awaiting review, easy

#1736 Remove networkx dependency from trace
  docs/requirements.txt
  docs/source/conf.py
  pyro/infer/trace_mean_field_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/poutine/trace_struct.py
  setup.py
  tests/infer/test_compute_downstream_costs.py
  tests/integration_tests/test_conjugate_gaussian_models.py
  tests/integration_tests/test_tracegraph_elbo.py
  tests/poutine/test_poutines.py
  tests/poutine/test_trace_struct.py
  tests/test_memory.py
Labels: awaiting review, easy, refactor

#1739 Minor fixes for progress bar for MCMC diagnostics
  pyro/infer/mcmc/logger.py
  pyro/infer/mcmc/mcmc.py
Labels: awaiting review

#1740 Implement sparse computation for DirichletMultinomial.log_prob()
  pyro/distributions/conjugate.py
  tests/distributions/test_conjugate.py
Labels: awaiting review

#1729 Implement sampling for von Mises distribution based on Best-Fisher algorithm
  pyro/distributions/von_mises.py
  tests/distributions/test_von_mises.py
Labels: awaiting review

#1741 Fix unit tests failing on CUDA
  tests/distributions/test_conjugate.py
  tests/distributions/test_empirical.py
  tests/test_examples.py
Labels: awaiting review

#1738 Use pytorch 1.0.1 in travis CI
  .travis.yml
Labels: awaiting review

#1743 Improve sparse DirichletMultinomial.log_prob()
  pyro/distributions/conjugate.py
Labels: awaiting review, easy

#1748 add paper ref to hmm
  examples/hmm.py
Labels: awaiting review

#1747 Fix failing von mises tests on CUDA
  tests/distributions/test_von_mises.py
Labels: awaiting review

#1749 Update README with links to the new repo
  README.md
Labels: awaiting review, easy

#1751 Fix version string for release tagged commits
  setup.py
Labels: awaiting review, discussion

#1750 Bump to version 0.3.1
  examples/air/main.py
  examples/baseball.py
  examples/bayesian_regression.py
  examples/contrib/autoname/mixture.py
  examples/contrib/autoname/scoping_mixture.py
  examples/contrib/autoname/tree_data.py
  examples/contrib/gp/sv-dkl.py
  examples/contrib/oed/ab_test.py
  examples/contrib/oed/item_response.py
  examples/contrib/oed/sequential_oed_sigmoid_lm.py
  examples/dmm/dmm.py
  examples/eight_schools/mcmc.py
  examples/eight_schools/svi.py
  examples/hmm.py
  examples/inclined_plane.py
  examples/lda.py
  examples/minipyro.py
  examples/rsa/generics.py
  examples/rsa/hyperbole.py
  examples/rsa/schelling.py
  examples/rsa/schelling_false.py
  examples/rsa/semantic_parsing.py
  examples/sparse_gamma_def.py
  examples/vae/ss_vae_M2.py
  examples/vae/vae.py
  examples/vae/vae_comparison.py
  pyro/__init__.py
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/bayesian_regression_ii.ipynb
  tutorial/source/bo.ipynb
  tutorial/source/ekf.ipynb
  tutorial/source/enumeration.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/gplvm.ipynb
  tutorial/source/jit.ipynb
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_iii.ipynb
  tutorial/source/tensor_shapes.ipynb
  tutorial/source/tracking_1d.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review, easy

#1758 Fix setup.py and long_description rendering
  README.md
  setup.py
Labels: awaiting review, easy

#1757 update docs urls
  pyro/contrib/minipyro.py
  tutorial/source/bo.ipynb
Labels: easy

#1760 Fix Pypi deploy
  setup.py
Labels: awaiting review

#1762 Fix EmpiricalMarginal with multiple GPUs
  pyro/infer/abstract_infer.py
Labels: awaiting review

#1767 Add guide for running test in cuda mode
  CONTRIBUTING.md
Labels: easy

#1765 Ignore ipynb_checkpoints for flake8 and isort
  setup.cfg
Labels: awaiting response, easy

#1768 Clean up requirements
  docs/requirements.txt
  setup.py
Labels: awaiting review

#1746 Distribution for Cholesky Factor of LKJ Prior
  examples/lkj.py
  pyro/distributions/__init__.py
  pyro/distributions/lkj.py
  tests/distributions/conftest.py
  tests/distributions/test_distributions.py
  tests/distributions/test_lkj.py
  tests/test_examples.py
Labels: awaiting review

#1638 Using cache from Transform and event_dim=1
  examples/dmm/dmm.py
  pyro/contrib/autoguide/__init__.py
  pyro/distributions/iaf.py
  pyro/distributions/permute.py
  pyro/distributions/planar.py
  pyro/distributions/torch_transform.py
  tests/distributions/test_flows.py
Labels: awaiting review

#1770 Change how `TracePredictive` works, so it resets plates on resampling
  pyro/infer/abstract_infer.py
  tests/infer/test_abstract_infer.py
Labels: awaiting review
