Repository pyro-ppl/pyro, pull requests merged in 2019-01, with the labels that each got.

#1688 Fix various docs format
  docs/source/ops.rst
  pyro/contrib/autoguide/__init__.py
  pyro/distributions/gaussian_scale_mixture.py
  pyro/infer/abstract_infer.py
  pyro/infer/elbo.py
  pyro/infer/importance.py
  pyro/infer/renyi_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/nn/auto_reg_nn.py
  pyro/ops/stats.py
  pyro/poutine/block_messenger.py
  pyro/poutine/handlers.py
  pyro/poutine/messenger.py
  pyro/poutine/runtime.py
  pyro/primitives.py
Labels: awaiting review

#1691 Add docs for Abstract Infer classes
  docs/source/pyro.infer.mcmc.txt
  pyro/contrib/gp/kernels/dot_product.py
  pyro/infer/abstract_infer.py
  pyro/infer/mcmc/__init__.py
  pyro/infer/mcmc/mcmc.py
  pyro/infer/mcmc/nuts.py
Labels: awaiting review

#1695 Reduce running time for nuts tests in Travis
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_mcmc.py
  tests/infer/mcmc/test_nuts.py
Labels: awaiting review, easy

#1701 Add check for pyro.markov history size
  pyro/util.py
  tests/infer/test_valid_models.py
Labels: awaiting review, warnings & errors

#1702 Make lda example more numerically stable; enable validation
  examples/lda.py
Labels: Examples, awaiting review

#1704 Import pyro.optim in gp_bayes_opt
  examples/contrib/oed/gp_bayes_opt.py
Labels: awaiting review

#1709 add second-order hmm to hmm example
  examples/hmm.py
  tests/test_examples.py
Labels: Examples, awaiting review

#1708 Implement BetaBinomial distributions
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/conjugate.py
  tests/distributions/conftest.py
  tests/distributions/test_conjugate.py
Labels: awaiting review, enhancement

#1694 Supporting multi-chain mcmc with cuda tensors
  examples/baseball.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/mcmc.py
  pyro/infer/mcmc/nuts.py
  tests/infer/mcmc/test_mcmc.py
  tests/test_examples.py
Labels: awaiting review

#1713 Adding Gamma-Poisson distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/conjugate.py
  tests/distributions/conftest.py
  tests/distributions/test_conjugate.py
Labels: awaiting review

#1718 Add adjoint ubersum script to examples/
  examples/ubersum.py
  tests/test_examples.py
  tutorial/source/index.rst
  tutorial/source/ubersum.rst
Labels: Examples, awaiting review

#1720 Rename ubersum -> einsum
  docs/source/ops.rst
  examples/einsum.py
  pyro/ops/contract.py
  pyro/ops/rings.py
  tests/ops/test_contract.py
  tests/test_examples.py
  tutorial/source/einsum.rst
  tutorial/source/index.rst
  tutorial/source/ubersum.rst
Labels: awaiting review

#1721 Fix bug in vectorized empirical.sample()
  pyro/distributions/empirical.py
  tests/distributions/test_empirical.py
Labels: awaiting review
