Repository pyro-ppl/pyro, pull requests merged in 2019-08, with the labels that each got.

#1984 Implement GaussianHMM distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/hmm.py
  pyro/ops/gaussian.py
  tests/distributions/test_hmm.py
  tests/ops/test_gaussian.py
Labels: awaiting review

#1989 move autoguide to core
  docs/source/index.rst
  docs/source/infer.autoguide.rst
  docs/source/inference.rst
  examples/capture_recapture/cjs.py
  examples/hmm.py
  examples/sparse_gamma_def.py
  examples/sparse_regression.py
  pyro/contrib/__init__.py
  pyro/contrib/autoguide.py
  pyro/contrib/easyguide/easyguide.py
  pyro/contrib/gp/parameterized.py
  pyro/contrib/oed/eig.py
  pyro/contrib/oed/util.py
  pyro/contrib/util.py
  pyro/infer/autoguide/__init__.py
  pyro/infer/autoguide/guides.py
  pyro/infer/autoguide/initialization.py
  pyro/infer/autoguide/utils.py
  pyro/ops/hessian.py
  tests/contrib/autoguide/test_inference.py
  tests/contrib/autoguide/test_mean_field_entropy.py
  tests/contrib/easyguide/test_easyguide.py
  tests/contrib/test_hessian.py
  tests/contrib/test_util.py
  tests/infer/mcmc/test_nuts.py
  tests/infer/test_abstract_infer.py
  tests/infer/test_autoguide.py
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/bayesian_regression_ii.ipynb
  tutorial/source/easyguide.ipynb
  tutorial/source/ekf.ipynb
  tutorial/source/enumeration.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/jit.ipynb
Labels: awaiting review, refactor

#1990 Fix broken readthedocs
  .readthedocs.yml
  docs/source/conf.py
Labels: documentation

#1985 basic SVGD implementation
  docs/source/inference_algos.rst
  pyro/infer/__init__.py
  pyro/infer/svgd.py
  tests/infer/test_svgd.py
Labels: awaiting review

#1994 Warn if importing pyro.contrib.autoguide rather than pyro.infer.autoguide
  pyro/contrib/autoguide.py
Labels: awaiting review, easy

#1998 Swallow exceptions in mcmc.summary if mkl not installed
  pyro/infer/mcmc/util.py
Labels: awaiting review, easy

#1997 Add sequential=True option to mcmc.predictive
  examples/baseball.py
  pyro/infer/mcmc/util.py
  tests/infer/mcmc/test_mcmc_util.py
Labels: awaiting review

#1991 upgrade SVGD to allow use of Kernelized Complete Conditional Stein Discrepancies
  pyro/infer/svgd.py
  tests/infer/test_svgd.py
Labels: awaiting review, enhancement

#1999 add conjugate poisson test for SVGD
  tests/infer/test_svgd.py
Labels: awaiting review, easy, testing

#2000 Fix *HMM.expand() methods
  pyro/distributions/hmm.py
  tests/distributions/test_hmm.py
Labels: awaiting review, bug

#2001 Fixes to enable dev branch to move to pytorch-1.2
  .travis.yml
  docs/source/conf.py
  examples/capture_recapture/cjs.py
  examples/sparse_regression.py
  pyro/distributions/mixture.py
  pyro/distributions/rejector.py
  pyro/distributions/score_parts.py
  pyro/distributions/spanning_tree.py
  pyro/distributions/torch_distribution.py
  pyro/distributions/transforms/block_autoregressive.py
  pyro/distributions/util.py
  pyro/distributions/von_mises.py
  pyro/distributions/zero_inflated_poisson.py
  pyro/ops/indexing.py
  pyro/ops/packed.py
  pyro/poutine/handlers.py
  pyro/poutine/mask_messenger.py
  tests/contrib/tracking/test_assignment.py
  tests/contrib/tracking/test_em.py
  tests/distributions/test_lkj.py
  tests/distributions/test_mask.py
  tests/distributions/test_mixture.py
  tests/distributions/test_pickle.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/test_enum.py
  tests/infer/test_jit.py
  tutorial/source/tracking_1d.ipynb
Labels: awaiting review

#1988 Make Loss negative (#1982)
  pyro/infer/trace_elbo.py
  pyro/infer/tracegraph_elbo.py
  tests/infer/test_valid_models.py
Labels: bug

#2002 strengthen svgd shape test
  tests/infer/test_svgd.py
Labels: awaiting review, easy

#2003 Remove obsolete torch patches
  pyro/distributions/torch.py
  pyro/distributions/torch_patch.py
  tests/distributions/test_torch_patch.py
Labels: awaiting review

#2006 Add docs for ZeroInflatedPoisson
  docs/source/distributions.rst
Labels: awaiting review, easy

#2007 Vectorize LowerCholeskyTransform
  pyro/distributions/torch_patch.py
  tests/distributions/test_torch_patch.py
Labels: awaiting review, easy

#2008 Bump up Pyro version to 0.4.0
  examples/air/main.py
  examples/baseball.py
  examples/bayesian_regression.py
  examples/contrib/autoname/mixture.py
  examples/contrib/autoname/scoping_mixture.py
  examples/contrib/autoname/tree_data.py
  examples/contrib/gp/sv-dkl.py
  examples/contrib/oed/ab_test.py
  examples/dmm/dmm.py
  examples/eight_schools/mcmc.py
  examples/eight_schools/svi.py
  examples/hmm.py
  examples/inclined_plane.py
  examples/lda.py
  examples/lkj.py
  examples/minipyro.py
  examples/rsa/generics.py
  examples/rsa/hyperbole.py
  examples/rsa/schelling.py
  examples/rsa/schelling_false.py
  examples/rsa/semantic_parsing.py
  examples/sparse_gamma_def.py
  examples/sparse_regression.py
  examples/vae/ss_vae_M2.py
  examples/vae/vae.py
  examples/vae/vae_comparison.py
  pyro/__init__.py
  setup.py
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/bayesian_regression_ii.ipynb
  tutorial/source/bo.ipynb
  tutorial/source/easyguide.ipynb
  tutorial/source/ekf.ipynb
  tutorial/source/enumeration.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/gplvm.ipynb
  tutorial/source/jit.ipynb
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_iii.ipynb
  tutorial/source/tensor_shapes.ipynb
  tutorial/source/tracking_1d.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review

#2004 Add option for lax testing that ignores AssertionError
  Makefile
  tests/conftest.py
Labels: awaiting review, discussion

#2005 Support Independent(Normal) observations in GaussianHMM
  pyro/distributions/hmm.py
  pyro/ops/gaussian.py
  tests/distributions/test_hmm.py
  tests/ops/test_gaussian.py
Labels: awaiting review, enhancement

#2010 Implement *HMM.filter() methods for forecasting
  pyro/distributions/hmm.py
  tests/distributions/test_hmm.py
Labels: awaiting review

#2013 Update links in README to point to the correct org
  README.md
Labels: awaiting review, easy

#2014 Address cholesky issue for potential function
  .gitignore
  pyro/ops/integrator.py
  tests/infer/mcmc/test_hmc.py
Labels: awaiting review

#2020 Update to version 0.4.1
  examples/air/main.py
  examples/baseball.py
  examples/bayesian_regression.py
  examples/contrib/autoname/mixture.py
  examples/contrib/autoname/scoping_mixture.py
  examples/contrib/autoname/tree_data.py
  examples/contrib/gp/sv-dkl.py
  examples/contrib/oed/ab_test.py
  examples/dmm/dmm.py
  examples/eight_schools/mcmc.py
  examples/eight_schools/svi.py
  examples/hmm.py
  examples/inclined_plane.py
  examples/lda.py
  examples/lkj.py
  examples/minipyro.py
  examples/rsa/generics.py
  examples/rsa/hyperbole.py
  examples/rsa/schelling.py
  examples/rsa/schelling_false.py
  examples/rsa/semantic_parsing.py
  examples/sparse_gamma_def.py
  examples/sparse_regression.py
  examples/vae/ss_vae_M2.py
  examples/vae/vae.py
  examples/vae/vae_comparison.py
  pyro/__init__.py
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/bayesian_regression_ii.ipynb
  tutorial/source/bo.ipynb
  tutorial/source/easyguide.ipynb
  tutorial/source/ekf.ipynb
  tutorial/source/enumeration.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/gplvm.ipynb
  tutorial/source/jit.ipynb
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_iii.ipynb
  tutorial/source/tensor_shapes.ipynb
  tutorial/source/tracking_1d.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review

#2021 Fix RuntimeException in MCMC when number of cores is less than num_chains
  pyro/infer/mcmc/api.py
  tests/infer/mcmc/test_mcmc_api.py
Labels: awaiting review

#2023 Add CII Best Practices Badge
  README.md
Labels: awaiting review

#2022 Add a pyro.factor primitive
  docs/source/distributions.rst
  docs/source/primitives.rst
  examples/rsa/generics.py
  examples/rsa/hyperbole.py
  examples/rsa/search_inference.py
  examples/rsa/semantic_parsing.py
  pyro/__init__.py
  pyro/contrib/gp/models/sgpr.py
  pyro/distributions/__init__.py
  pyro/distributions/unit.py
  pyro/primitives.py
  tests/distributions/test_unit.py
  tests/infer/test_autoguide.py
  tutorial/source/RSA-hyperbole.ipynb
  tutorial/source/RSA-implicature.ipynb
Labels: awaiting review, enhancement
