Repository pyro-ppl/pyro, pull requests merged in 2019-07, with the labels that each got.

#1936 Repopulate HMC cache after clearing
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
Labels: awaiting review, easy

#1939 Add docs for MCMC utility functions
  docs/source/pyro.infer.mcmc.txt
  pyro/distributions/lkj.py
  pyro/infer/mcmc/util.py
Labels: awaiting review, easy

#1925 Add OED estimators and accompanying tests
  examples/contrib/oed/ab_test.py
  examples/contrib/oed/eig_estimation_benchmarking.py
  examples/contrib/oed/item_response.py
  examples/contrib/oed/sequential_oed_sigmoid_lm.py
  pyro/contrib/autoguide/__init__.py
  pyro/contrib/glmm/glmm.py
  pyro/contrib/glmm/guides.py
  pyro/contrib/oed/__init__.py
  pyro/contrib/oed/eig.py
  pyro/contrib/oed/util.py
  pyro/contrib/util.py
  tests/contrib/autoguide/test_mean_field_entropy.py
  tests/contrib/glmm/test_glmm.py
  tests/contrib/oed/test_eig.py
  tests/contrib/oed/test_finite_spaces_eig.py
  tests/contrib/oed/test_linear_models_eig.py
  tests/contrib/oed/test_xexpx.py
  tests/test_examples.py
Labels: awaiting response

#1938 Add @weakmethod decorator to avoid memory leaks
  pyro/distributions/testing/rejection_exponential.py
  pyro/distributions/testing/rejection_gamma.py
  pyro/distributions/util.py
  tests/distributions/test_util.py
Labels: awaiting review

#1940 Allow for pickling of poutine wrapped models
  pyro/distributions/torch_patch.py
  pyro/infer/enum.py
  pyro/infer/mcmc/util.py
  pyro/poutine/block_messenger.py
  pyro/poutine/messenger.py
  pyro/util.py
  tests/infer/mcmc/test_valid_models.py
  tests/poutine/test_poutines.py
Labels: awaiting review, discussion

#1943 Fix some numerical/shape issues in GP
  pyro/contrib/gp/models/sgpr.py
  pyro/contrib/gp/util.py
Labels: awaiting review

#1945 Use pyro.enable_validation(__debug__) in examples
  examples/baseball.py
  examples/capture_recapture/cjs.py
  examples/contrib/autoname/mixture.py
  examples/contrib/autoname/tree_data.py
  examples/eight_schools/mcmc.py
  examples/hmm.py
  examples/lda.py
  examples/lkj.py
  examples/sparse_gamma_def.py
Labels: awaiting review, easy

#1946 Use ClippedAdam in LDA example; add references
  examples/lda.py
  tutorial/source/index.rst
Labels: Examples, awaiting review, easy

#1941 Using new MCMC API in existing examples
  docs/source/pyro.infer.mcmc.txt
  examples/baseball.py
  examples/eight_schools/mcmc.py
  examples/lkj.py
  pyro/contrib/gp/models/model.py
  pyro/distributions/torch_patch.py
  pyro/infer/abstract_infer.py
  pyro/infer/mcmc/api.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/mcmc.py
  pyro/infer/mcmc/nuts.py
  pyro/infer/mcmc/util.py
  pyro/util.py
  tests/contrib/gp/test_models.py
  tests/doctest_fixtures.py
  tests/infer/mcmc/test_mcmc_api.py
  tests/infer/mcmc/test_mcmc_util.py
  tests/infer/mcmc/test_valid_models.py
  tests/infer/test_abstract_infer.py
  tests/perf/test_benchmark.py
  tutorial/source/bayesian_regression_ii.ipynb
  tutorial/source/gmm.ipynb
Labels: awaiting review

#1950 Performance tweaks: Trace.__contains__ and ignore_jit_warnings
  pyro/infer/mcmc/util.py
  pyro/ops/jit.py
  pyro/poutine/trace_struct.py
  pyro/util.py
Labels: awaiting review

#1942 Add diverging diagnostics for HMC/NUTS
  pyro/infer/abstract_infer.py
  pyro/infer/mcmc/api.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/mcmc.py
  pyro/infer/mcmc/mcmc_kernel.py
  pyro/infer/mcmc/nuts.py
  pyro/ops/stats.py
  tests/infer/mcmc/test_mcmc.py
  tests/infer/mcmc/test_mcmc_api.py
Labels: awaiting review

#1951 add docs for custom pyro optimizers
  docs/source/pyro.optim.txt
  pyro/optim/adagrad_rmsprop.py
  pyro/optim/optim.py
Labels: documentation, easy

#1952 Minor change to the MCMC interface
  examples/baseball.py
  examples/eight_schools/mcmc.py
  pyro/contrib/gp/models/model.py
  pyro/infer/mcmc/api.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  pyro/infer/mcmc/util.py
  tests/contrib/gp/test_models.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_mcmc_api.py
  tests/infer/mcmc/test_mcmc_util.py
  tests/infer/mcmc/test_nuts.py
  tests/perf/test_benchmark.py
  tutorial/source/bayesian_regression_ii.ipynb
  tutorial/source/gmm.ipynb
Labels: awaiting review

#1953 Add summary method to MCMC
  examples/eight_schools/mcmc.py
  pyro/infer/mcmc/api.py
  pyro/infer/mcmc/util.py
  tests/infer/mcmc/test_mcmc.py
  tests/infer/mcmc/test_mcmc_api.py
Labels: awaiting review

#1954 CUDA fixes for MCMC
  examples/baseball.py
  pyro/infer/mcmc/api.py
  pyro/infer/mcmc/util.py
  pyro/ops/integrator.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/mcmc/test_mcmc.py
  tests/infer/mcmc/test_mcmc_api.py
  tests/infer/mcmc/test_nuts.py
Labels: awaiting review

#1957 Replace acceptance rate by mean accept prob for hmc logging
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
Labels: awaiting review

#1818 Add Trace_MMD class, add tests that MMD correctly fits distributions
  pyro/infer/__init__.py
  pyro/infer/trace_mmd.py
  tests/infer/test_inference.py
Labels: awaiting review

#1956 Fix memory issue of MCMC for multiple chains
  examples/baseball.py
  pyro/infer/mcmc/api.py
Labels: awaiting review

#1958 Implement parallelized DiscreteHMM distribution
  docs/source/distributions.rst
  examples/hmm.py
  pyro/distributions/__init__.py
  pyro/distributions/hmm.py
  tests/distributions/test_hmm.py
  tests/test_examples.py
Labels: awaiting review, enhancement

#1961 Fix autoguide latent shape mismatch
  pyro/contrib/autoguide/__init__.py
  tests/contrib/autoguide/test_advi.py
Labels: awaiting review

#1959 Bump Pyro version to 0.3.4
  examples/air/main.py
  examples/baseball.py
  examples/bayesian_regression.py
  examples/contrib/autoname/mixture.py
  examples/contrib/autoname/scoping_mixture.py
  examples/contrib/autoname/tree_data.py
  examples/contrib/gp/sv-dkl.py
  examples/contrib/oed/ab_test.py
  examples/dmm/dmm.py
  examples/eight_schools/mcmc.py
  examples/eight_schools/svi.py
  examples/hmm.py
  examples/inclined_plane.py
  examples/lda.py
  examples/lkj.py
  examples/minipyro.py
  examples/rsa/generics.py
  examples/rsa/hyperbole.py
  examples/rsa/schelling.py
  examples/rsa/schelling_false.py
  examples/rsa/semantic_parsing.py
  examples/sparse_gamma_def.py
  examples/vae/ss_vae_M2.py
  examples/vae/vae.py
  examples/vae/vae_comparison.py
  pyro/__init__.py
  setup.py
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/bayesian_regression_ii.ipynb
  tutorial/source/bo.ipynb
  tutorial/source/easyguide.ipynb
  tutorial/source/ekf.ipynb
  tutorial/source/enumeration.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/gplvm.ipynb
  tutorial/source/jit.ipynb
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_iii.ipynb
  tutorial/source/tensor_shapes.ipynb
  tutorial/source/tracking_1d.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review

#1962 Drop Python2.7 tests from ci grid
  .travis.yml
  profiler/profiling_utils.py
  setup.py
Labels: awaiting review

#1965 drop six dependency
  examples/baseball.py
  examples/dmm/polyphonic_data_loader.py
  examples/mixed_hmm/seal_data.py
  examples/rsa/search_inference.py
  examples/vae/vae_comparison.py
  pyro/contrib/easyguide/easyguide.py
  pyro/contrib/oed/search.py
  pyro/contrib/tracking/dynamic_models.py
  pyro/contrib/tracking/measurements.py
  pyro/distributions/distribution.py
  pyro/infer/abstract_infer.py
  pyro/infer/elbo.py
  pyro/infer/enum.py
  pyro/infer/mcmc/api.py
  pyro/infer/mcmc/mcmc.py
  pyro/infer/mcmc/mcmc_kernel.py
  pyro/infer/traceenum_elbo.py
  pyro/ops/contract.py
  pyro/ops/einsum/adjoint.py
  pyro/ops/einsum/torch_map.py
  pyro/ops/einsum/torch_sample.py
  pyro/ops/rings.py
  pyro/poutine/handlers.py
  pyro/poutine/trace_messenger.py
  pyro/poutine/trace_struct.py
  pyro/util.py
  setup.py
  tests/distributions/test_pickle.py
  tests/ops/test_contract.py
  tests/poutine/test_poutines.py
  tutorial/source/search_inference.py
Labels: refactor

#1966 Add profiler script for examples/hmm.py
  .gitignore
  examples/hmm.py
  profiler/hmm.py
Labels: awaiting review, easy

#1971 use more conservative default hyperparameters in dmm.py
  examples/dmm/dmm.py
Labels: awaiting review, easy

#1972 drop remaining python 2 references
  README.md
  docker/Makefile
  docs/source/installation.rst
Labels: easy

#1975 Profile compilation time in profiler.hmm
  examples/hmm.py
  profiler/hmm.py
  pyro/ops/jit.py
  pyro/util.py
Labels: awaiting review, discussion

#1974 fix doc rendering for autodelta
  pyro/contrib/autoguide/__init__.py
Labels: awaiting review, easy

#1947 Add SMCFilter class; Add simple model example that uses SMC Filter
  docs/source/inference_algos.rst
  examples/smcfilter.py
  pyro/infer/__init__.py
  pyro/infer/smcfilter.py
  tests/infer/test_smcfilter.py
  tests/test_examples.py
  tutorial/source/index.rst
  tutorial/source/smcfilter.rst
Labels: awaiting review

#1978 Patch Categorical.sample() to fix bug
  pyro/distributions/torch.py
  tests/distributions/test_categorical.py
Labels: awaiting review, bug

#1980 Implement Gaussian ops
  docs/source/ops.rst
  pyro/ops/gaussian.py
  tests/ops/test_gaussian.py
Labels: awaiting review, enhancement

#1981 Implement GaussianMRF distribution
  docs/source/distributions.rst
  docs/source/ops.rst
  pyro/distributions/__init__.py
  pyro/distributions/hmm.py
  pyro/ops/gaussian.py
  tests/distributions/test_hmm.py
  tests/ops/gaussian.py
  tests/ops/test_gaussian.py
Labels: awaiting review

#1979 add sparse regression example
  examples/sparse_regression.py
  tests/test_examples.py
Labels: awaiting review

#1987 remove einsum perf patch
  pyro/distributions/torch_patch.py
Labels: awaiting review, easy
