Repository pyro-ppl/pyro, pull requests merged in 2019-12, with the labels that each got.

#2197 Add a to_pyro_module_() helper
  pyro/nn/module.py
  tests/common.py
  tests/nn/test_module.py
Labels: awaiting review, bug, usability

#2178 Implement EnergyDistance likelihood-free inference algorithm
  docs/source/inference_algos.rst
  pyro/distributions/stable.py
  pyro/infer/__init__.py
  pyro/infer/energy_distance.py
  pyro/infer/svi.py
  pyro/infer/util.py
  pyro/poutine/uncondition_messenger.py
  tests/infer/test_inference.py
  tests/infer/test_valid_models.py
Labels: awaiting review, discussion

#2151 Add a causal effect vae example
  examples/cevae.py
  tests/test_examples.py
  tutorial/source/cevae.rst
  tutorial/source/index.rst
Labels: Examples, awaiting review

#2200 Update all links github.com/uber -> github.com/pyro-ppl
  docs/source/getting_started.rst
  docs/source/index.rst
  docs/source/installation.rst
  pyro/contrib/autoname/named.py
  pyro/infer/mcmc/nuts.py
  pyro/infer/renyi_elbo.py
  tests/infer/test_enum.py
  tutorial/source/air.ipynb
  tutorial/source/capture_recapture.rst
  tutorial/source/custom_objectives.ipynb
  tutorial/source/dkl.rst
  tutorial/source/dmm.ipynb
  tutorial/source/effect_handlers.ipynb
  tutorial/source/einsum.rst
  tutorial/source/enumeration.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/hmm.rst
  tutorial/source/jit.ipynb
  tutorial/source/lda.rst
  tutorial/source/mcmc.rst
  tutorial/source/minipyro.rst
  tutorial/source/smcfilter.rst
  tutorial/source/sparse_gamma.rst
  tutorial/source/ss-vae.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review, documentation, easy

#2191 Reweighted Wake-Sleep
  docs/source/inference_algos.rst
  pyro/infer/__init__.py
  pyro/infer/enum.py
  pyro/infer/rws.py
  pyro/infer/svi.py
  pyro/poutine/trace_struct.py
  tests/infer/test_inference.py
Labels: awaiting review

#2192 Corrections to planar flow implementation
  pyro/distributions/transforms/planar.py
Labels: awaiting review

#2145 Add Tensor Monte Carlo support to more existing examples
  examples/capture_recapture/cjs.py
  examples/hmm.py
  tests/test_examples.py
Labels: Examples, awaiting review

#2203 Do not use varargs in internal functions / methods in pyro.infer
  pyro/infer/discrete.py
  pyro/infer/elbo.py
  pyro/infer/energy_distance.py
  pyro/infer/enum.py
  pyro/infer/importance.py
  pyro/infer/renyi_elbo.py
  pyro/infer/rws.py
  pyro/infer/trace_elbo.py
  pyro/infer/trace_mean_field_elbo.py
  pyro/infer/trace_mmd.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/infer/tracetmc_elbo.py
  tests/infer/test_inference.py
Labels: awaiting review, discussion

#2208 Add MultivariateStudentT distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/multivariate_studentt.py
  pyro/ops/gaussian.py
  tests/distributions/conftest.py
  tests/distributions/test_mvt.py
Labels: awaiting review

#2209 Add default TorchDistribution.expand method
  pyro/distributions/torch_distribution.py
  tests/distributions/test_distributions.py
Labels: awaiting review

#2196 Add deterministic primitive
  docs/source/primitives.rst
  pyro/__init__.py
  pyro/primitives.py
  tests/infer/test_predictive.py
Labels: awaiting review

#2210 Automatically generate handlers from Messengers
  pyro/infer/discrete.py
  pyro/infer/enum.py
  pyro/infer/traceenum_elbo.py
  pyro/infer/tracetmc_elbo.py
  pyro/poutine/block_messenger.py
  pyro/poutine/broadcast_messenger.py
  pyro/poutine/condition_messenger.py
  pyro/poutine/enum_messenger.py
  pyro/poutine/handlers.py
  pyro/poutine/infer_config_messenger.py
  pyro/poutine/lift_messenger.py
  pyro/poutine/markov_messenger.py
  pyro/poutine/mask_messenger.py
  pyro/poutine/replay_messenger.py
  pyro/poutine/scale_messenger.py
  pyro/poutine/trace_messenger.py
  tests/poutine/test_poutines.py
Labels: awaiting review, warnings & errors

#2211 fix guide_trace and model_trace in bayesian regression tutorial
  tutorial/source/bayesian_regression.ipynb
Labels: bug

#2212 Update pyro.poutine docs generation
  docs/source/poutine.rst
  docs/source/pyro.poutine.txt
  pyro/poutine/block_messenger.py
  pyro/poutine/handlers.py
  pyro/poutine/seed_messenger.py
Labels: awaiting review, documentation

#2207 add LowerCholeskyAffine transform
  docs/source/distributions.rst
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/lower_cholesky_affine.py
  tests/distributions/test_distributions.py
  tests/distributions/test_transforms.py
Labels: awaiting review

#2199 Implement uniform mixture sampling in TraceTMC_ELBO
  pyro/infer/enum.py
  pyro/infer/tracetmc_elbo.py
  pyro/poutine/enum_messenger.py
  tests/infer/test_tmc.py
Labels: awaiting review

#2202 Add a pyro.contrib.cevae module
  .travis.yml
  docs/source/conf.py
  docs/source/contrib.cevae.rst
  docs/source/index.rst
  examples/cevae.py
  examples/contrib/cevae/synthetic.py
  pyro/contrib/cevae/__init__.py
  tests/contrib/cevae/test_cevae.py
  tests/test_examples.py
Labels: awaiting review

#2215 Bump to version 1.1.0
  docs/source/inference_algos.rst
  examples/air/main.py
  examples/baseball.py
  examples/contrib/autoname/mixture.py
  examples/contrib/autoname/scoping_mixture.py
  examples/contrib/autoname/tree_data.py
  examples/contrib/cevae/synthetic.py
  examples/contrib/gp/sv-dkl.py
  examples/contrib/oed/ab_test.py
  examples/contrib/timeseries/gp_models.py
  examples/dmm/dmm.py
  examples/eight_schools/mcmc.py
  examples/eight_schools/svi.py
  examples/hmm.py
  examples/inclined_plane.py
  examples/lda.py
  examples/lkj.py
  examples/minipyro.py
  examples/rsa/generics.py
  examples/rsa/hyperbole.py
  examples/rsa/schelling.py
  examples/rsa/schelling_false.py
  examples/rsa/semantic_parsing.py
  examples/sparse_gamma_def.py
  examples/sparse_regression.py
  examples/vae/ss_vae_M2.py
  examples/vae/vae.py
  examples/vae/vae_comparison.py
  pyro/__init__.py
  pyro/util.py
  setup.py
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/bayesian_regression_ii.ipynb
  tutorial/source/bo.ipynb
  tutorial/source/easyguide.ipynb
  tutorial/source/ekf.ipynb
  tutorial/source/enumeration.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/gplvm.ipynb
  tutorial/source/jit.ipynb
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_iii.ipynb
  tutorial/source/tensor_shapes.ipynb
  tutorial/source/tracking_1d.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review

#2222 Implement poutine.reparam with aux variable support
  docs/source/distributions.rst
  docs/source/pyro.poutine.txt
  pyro/distributions/__init__.py
  pyro/distributions/reparameterize.py
  pyro/distributions/stable.py
  pyro/poutine/__init__.py
  pyro/poutine/handlers.py
  pyro/poutine/reparam_messenger.py
  tests/distributions/test_reparameterize.py
  tests/infer/mcmc/test_valid_models.py
  tests/infer/test_inference.py
  tests/infer/test_valid_models.py
Labels: awaiting review, enhancement

#2230 Fix torch==1.3.1+cpu segfault on import on travis
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/bayesian_regression_ii.ipynb
  tutorial/source/gmm.ipynb
Labels: awaiting review, easy, high priority

#2228 Fix df coercion in MultivariateStudentT
  pyro/distributions/multivariate_studentt.py
Labels: awaiting review, easy

#2225 Fix docs requirements and cevae link
  docs/source/conf.py
  tutorial/source/cevae.rst
Labels: awaiting review, documentation, easy

#2184 Adding a tutorial on Dirichlet process mixture modeling
  tutorial/source/dirichlet_process_mixture.ipynb
  tutorial/source/index.rst
Labels: Examples, awaiting review

#2226 Pyro enum bugfix [WIP]
  pyro/infer/traceenum_elbo.py
  tests/infer/test_enum.py
Labels: awaiting review, bug

#2025 Implement GaussianGamma op
  pyro/ops/gamma_gaussian.py
  tests/ops/gamma_gaussian.py
  tests/ops/test_gamma_gaussian.py
Labels: awaiting review

#2213 Implement GammaGaussianHMM
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/hmm.py
  pyro/ops/gamma_gaussian.py
  tests/distributions/test_hmm.py
Labels: awaiting review

#2236 Implement StableHMM for robust time series analysis
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/hmm.py
  tests/distributions/test_hmm.py
Labels: awaiting review, enhancement

#2238 Implement GaussianHMM.rsample()
  pyro/distributions/hmm.py
  tests/distributions/test_hmm.py
Labels: awaiting review, enhancement
