Repository pyro-ppl/pyro, pull requests merged in 2019-04, with the labels that each got.

#1799 Run without raising exceptions when HMC contains no stochastic site
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  tests/infer/mcmc/test_mcmc.py
Labels: awaiting review

#1800 helper function for fitting generalized pareto distributions
  pyro/ops/stats.py
  tests/ops/test_stats.py
Labels: awaiting review

#1801 RadialFlow
  pyro/distributions/__init__.py
  pyro/distributions/radial.py
  tests/distributions/test_flows.py
Labels: awaiting review

#1803 Batchnorm transform
  pyro/distributions/__init__.py
  pyro/distributions/batch_norm.py
  tests/distributions/test_flows.py
Labels: awaiting review

#1806 Adding support for exact inference in HMC with conjugate pairs
  pyro/contrib/conjugate/__init__.py
  pyro/contrib/conjugate/infer.py
  tests/infer/mcmc/test_nuts.py
Labels: awaiting review

#1805 fix bug in gradient computation for tail adaptive loss
  pyro/infer/trace_tail_adaptive_elbo.py
Labels: awaiting review

#1804 Add vectorized importance weight helper
  pyro/infer/importance.py
  tests/infer/test_enum.py
Labels: awaiting review

#1809 add first CJS ecological model
  examples/cjs/cjs.py
  examples/cjs/dipper_capture_histories.csv
  tests/test_examples.py
  tutorial/source/index.rst
Labels: awaiting review

#1810 add 4 more CSJ models
  examples/capture_recapture/cjs.py
  examples/capture_recapture/dipper_capture_histories.csv
  examples/capture_recapture/dipper_capture_history.csv
  examples/capture_recapture/dipper_sex.csv
  examples/cjs/cjs.py
  tests/test_examples.py
  tutorial/source/capture_recapture.rst
  tutorial/source/index.rst
Labels: awaiting review

#1815 add meadow voles dataset to cjs models
  examples/capture_recapture/cjs.py
  examples/capture_recapture/meadow_voles_capture_history.csv
Labels: awaiting review

#1820 Implement constraints in minipyro
  examples/minipyro.py
  pyro/contrib/minipyro.py
  tests/contrib/test_minipyro.py
Labels: awaiting review

#1822 torchify fit_generalized_pareto
  pyro/ops/stats.py
  tests/ops/test_stats.py
Labels: awaiting review

#1821 Implement a SpanningTree distribution
  .travis.yml
  MANIFEST.in
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/spanning_tree.cpp
  pyro/distributions/spanning_tree.py
  tests/distributions/test_spanning_tree.py
Labels: awaiting review, enhancement

#1826 add psis diagnostic
  pyro/infer/importance.py
  tests/infer/test_util.py
Labels: awaiting review

#1827 Fix infer_discrete handling of plate of size 1
  pyro/infer/discrete.py
  tests/infer/test_discrete.py
Labels: awaiting review, bug

#1812 fixed typo in deferred_conditioned_scale
  tutorial/source/intro_part_ii.ipynb
Labels: awaiting review

#1828 Add ops.indexing module with a broadcast-friendly getitem
  docs/source/ops.rst
  examples/hmm.py
  pyro/ops/indexing.py
  tests/infer/test_enum.py
  tests/infer/test_valid_models.py
  tests/ops/test_indexing.py
Labels: awaiting review

#1831 Optimize Categorical.log_prob() of enumerated support
  pyro/distributions/torch.py
  pyro/poutine/enumerate_messenger.py
Labels: awaiting review

#1832 Discuss Vindex in tutorials
  tutorial/source/enumeration.ipynb
  tutorial/source/tensor_shapes.ipynb
Labels: awaiting review, documentation

#1833 Fix MNIST dataloader with newer torchvision package
  examples/vae/utils/mnist_cached.py
  setup.py
Labels: awaiting review

#1834 Fix tests failing on CUDA
  pyro/distributions/lkj.py
  pyro/ops/stats.py
  setup.py
  tests/contrib/gp/test_models.py
  tests/distributions/test_lkj.py
  tests/distributions/test_spanning_tree.py
  tests/infer/mcmc/test_mcmc.py
  tests/infer/mcmc/test_nuts.py
  tests/infer/test_enum.py
  tests/infer/test_gradient.py
Labels: awaiting review

#1836 Switch to using Vindex in mixed-effect HMMs
  examples/mixed_hmm/model.py
Labels: Examples, awaiting review, easy

#1835 Update to version 0.3.2
  docs/source/distributions.rst
  examples/air/main.py
  examples/baseball.py
  examples/bayesian_regression.py
  examples/contrib/autoname/mixture.py
  examples/contrib/autoname/scoping_mixture.py
  examples/contrib/autoname/tree_data.py
  examples/contrib/gp/sv-dkl.py
  examples/contrib/oed/ab_test.py
  examples/contrib/oed/item_response.py
  examples/contrib/oed/sequential_oed_sigmoid_lm.py
  examples/dmm/dmm.py
  examples/eight_schools/mcmc.py
  examples/eight_schools/svi.py
  examples/hmm.py
  examples/inclined_plane.py
  examples/lda.py
  examples/lkj.py
  examples/minipyro.py
  examples/rsa/generics.py
  examples/rsa/hyperbole.py
  examples/rsa/schelling.py
  examples/rsa/schelling_false.py
  examples/rsa/semantic_parsing.py
  examples/sparse_gamma_def.py
  examples/vae/ss_vae_M2.py
  examples/vae/vae.py
  examples/vae/vae_comparison.py
  pyro/__init__.py
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/bayesian_regression_ii.ipynb
  tutorial/source/bo.ipynb
  tutorial/source/ekf.ipynb
  tutorial/source/enumeration.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/gplvm.ipynb
  tutorial/source/jit.ipynb
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_iii.ipynb
  tutorial/source/tensor_shapes.ipynb
  tutorial/source/tracking_1d.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review, easy

#1838 Add JitTrace_ELBO class to minipyro
  examples/minipyro.py
  pyro/contrib/minipyro.py
  tests/contrib/test_minipyro.py
  tests/test_examples.py
Labels: awaiting review

#1842 Avoid using legacy constructors Tensor.new_*()
  examples/air/air.py
  examples/baseball.py
  examples/bayesian_regression.py
  examples/contrib/oed/gp_bayes_opt.py
  examples/dmm/polyphonic_data_loader.py
  examples/hmm.py
  examples/lkj.py
  examples/vae/ss_vae_M2.py
  examples/vae/vae.py
  pyro/contrib/autoguide/__init__.py
  pyro/contrib/minipyro.py
  pyro/contrib/tracking/assignment.py
  pyro/contrib/tracking/distributions.py
  pyro/contrib/tracking/dynamic_models.py
  pyro/contrib/tracking/extended_kalman_filter.py
  pyro/contrib/tracking/measurements.py
  pyro/distributions/avf_mvn.py
  pyro/distributions/conjugate.py
  pyro/distributions/delta.py
  pyro/distributions/diag_normal_mixture.py
  pyro/distributions/diag_normal_mixture_shared_cov.py
  pyro/distributions/lkj.py
  pyro/distributions/omt_mvn.py
  pyro/distributions/relaxed_straight_through.py
  pyro/distributions/spanning_tree.py
  pyro/distributions/testing/rejection_gamma.py
  pyro/distributions/util.py
  pyro/infer/abstract_infer.py
  pyro/infer/mcmc/adaptation.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/mcmc.py
  pyro/infer/mcmc/nuts.py
  pyro/infer/renyi_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/infer/util.py
  pyro/ops/contract.py
  pyro/ops/linalg.py
  pyro/ops/packed.py
  pyro/ops/stats.py
  pyro/optim/clipped_adam.py
  tests/infer/test_jit.py
Labels: awaiting review, refactor
