Repository pyro-ppl/pyro, pull requests merged in 2019-10, with the labels that each got.

#2052 Reorganize constraints and transforms modules
  docs/source/distributions.rst
  examples/dmm/dmm.py
  pyro/distributions/__init__.py
  pyro/distributions/constraints.py
  pyro/distributions/lkj.py
  pyro/distributions/torch.py
  pyro/distributions/torch_distribution.py
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/batch_norm.py
  pyro/distributions/transforms/cholesky.py
  pyro/distributions/transforms/permute.py
  pyro/infer/autoguide/guides.py
  tests/distributions/test_lkj.py
  tests/infer/mcmc/test_mcmc_api.py
Labels: awaiting review, refactor

#2049 Add some models for generic testing of MCMC
  docs/source/poutine.rst
  docs/source/primitives.rst
  docs/source/pyro.generic.rst
  pyro/generic/__init__.py
  pyro/generic/dispatch.py
  pyro/generic/testing.py
  pyro/infer/__init__.py
  pyro/poutine/__init__.py
  pyro/poutine/handlers.py
  pyro/util.py
  tests/test_generic.py
Labels: awaiting review

#2055 Raise NotImplementedError on missing backend functionality
  pyro/generic/dispatch.py
  tests/test_generic.py
Labels: awaiting review

#2056 Remove deprecated MCMC code for next release
  pyro/infer/mcmc/__init__.py
  pyro/infer/mcmc/api.py
  pyro/infer/mcmc/mcmc.py
  pyro/infer/mcmc/util.py
  tests/infer/mcmc/test_mcmc.py
  tests/infer/mcmc/test_mcmc_api.py
  tests/infer/test_abstract_infer.py
Labels: WIP

#2057 Add some features to minipyro for generic API coverage
  pyro/contrib/minipyro.py
  pyro/generic/testing.py
  tests/test_generic.py
Labels: awaiting review

#2059 Improve U-turn condition
  pyro/infer/mcmc/nuts.py
  tests/infer/mcmc/test_nuts.py
Labels: awaiting review

#2061 Exclude seed handler from the PYRO_STACK
  pyro/contrib/minipyro.py
  pyro/poutine/handlers.py
  pyro/util.py
  tests/test_generic.py
Labels: awaiting review

#2060 Make some gp likelihoods more stable
  examples/contrib/gp/sv-dkl.py
  pyro/contrib/gp/likelihoods/binary.py
  pyro/contrib/gp/likelihoods/multi_class.py
Labels: awaiting review

#2062 Deprecate pyro.generic in favor of pyroapi
  docs/source/index.rst
  docs/source/pyro.generic.rst
  pyro/contrib/minipyro.py
  pyro/generic.py
  pyro/generic/__init__.py
  pyro/generic/dispatch.py
  pyro/generic/testing.py
  setup.py
  tests/pyroapi/conftest.py
  tests/pyroapi/test_pyroapi.py
  tests/test_generic.py
Labels: awaiting review

#2065 Handle -inf in einsum torch_log backend
  pyro/ops/einsum/torch_log.py
  tests/ops/einsum/test_torch_log.py
Labels: awaiting review

#2063 Move mcmc predictive to infer
  docs/source/inference_algos.rst
  pyro/infer/__init__.py
  pyro/infer/predictive.py
  tests/infer/test_predictive.py
Labels: awaiting review

#2071 Minor fixes for update to PyTorch 1.3
  .travis.yml
  pyro/distributions/torch_patch.py
  tests/distributions/test_empirical.py
Labels: awaiting review

#2081 Fix autoguide's init_to_median strategy for multivariate distributions
  pyro/infer/autoguide/initialization.py
  tests/infer/test_autoguide.py
Labels: awaiting review, bug

#2079 Fix initialization in bayesian regression tutorial
  tests/test_examples.py
  tutorial/source/bayesian_regression.ipynb
Labels: awaiting review, easy

#2075 Bump to version 0.5.0
  .travis.yml
  docs/requirements.txt
  docs/source/pyro.nn.txt
  examples/air/main.py
  examples/baseball.py
  examples/bayesian_regression.py
  examples/contrib/autoname/mixture.py
  examples/contrib/autoname/scoping_mixture.py
  examples/contrib/autoname/tree_data.py
  examples/contrib/gp/sv-dkl.py
  examples/contrib/oed/ab_test.py
  examples/dmm/dmm.py
  examples/eight_schools/mcmc.py
  examples/eight_schools/svi.py
  examples/hmm.py
  examples/inclined_plane.py
  examples/lda.py
  examples/lkj.py
  examples/minipyro.py
  examples/rsa/generics.py
  examples/rsa/hyperbole.py
  examples/rsa/schelling.py
  examples/rsa/schelling_false.py
  examples/rsa/semantic_parsing.py
  examples/sparse_gamma_def.py
  examples/sparse_regression.py
  examples/vae/ss_vae_M2.py
  examples/vae/vae.py
  examples/vae/vae_comparison.py
  pyro/__init__.py
  pyro/infer/abstract_infer.py
  pyro/infer/elbo.py
  pyro/infer/svi.py
  setup.py
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/bayesian_regression_ii.ipynb
  tutorial/source/bo.ipynb
  tutorial/source/easyguide.ipynb
  tutorial/source/ekf.ipynb
  tutorial/source/enumeration.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/gplvm.ipynb
  tutorial/source/jit.ipynb
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_iii.ipynb
  tutorial/source/tensor_shapes.ipynb
  tutorial/source/tracking_1d.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review

#2086 add block_diag() tensor helper
  pyro/ops/tensor_utils.py
  tests/ops/test_tensor_utils.py
Labels: awaiting review, easy

#2077 seed ops.ssm_gp with some matern kernel utilities
  docs/source/ops.rst
  pyro/ops/ssm_gp.py
  tests/ops/test_ssm_gp.py
Labels: awaiting review

#2088 seed contrib.timeseries with a IndependentMaternGP model
  docs/source/contrib.timeseries.rst
  docs/source/index.rst
  pyro/contrib/timeseries/__init__.py
  pyro/contrib/timeseries/base.py
  pyro/contrib/timeseries/gp.py
  tests/contrib/timeseries/test_gp.py
  tests/ops/test_ssm_gp.py
Labels: awaiting review

#2089 Bump version to 0.5.1 that is python 3.5 compatible
  .travis.yml
  docs/requirements.txt
  docs/source/conf.py
  examples/air/main.py
  examples/baseball.py
  examples/bayesian_regression.py
  examples/contrib/autoname/mixture.py
  examples/contrib/autoname/scoping_mixture.py
  examples/contrib/autoname/tree_data.py
  examples/contrib/gp/sv-dkl.py
  examples/contrib/oed/ab_test.py
  examples/dmm/dmm.py
  examples/eight_schools/mcmc.py
  examples/eight_schools/svi.py
  examples/hmm.py
  examples/inclined_plane.py
  examples/lda.py
  examples/lkj.py
  examples/minipyro.py
  examples/rsa/generics.py
  examples/rsa/hyperbole.py
  examples/rsa/schelling.py
  examples/rsa/schelling_false.py
  examples/rsa/semantic_parsing.py
  examples/sparse_gamma_def.py
  examples/sparse_regression.py
  examples/vae/ss_vae_M2.py
  examples/vae/vae.py
  examples/vae/vae_comparison.py
  pyro/__init__.py
  pyro/infer/mcmc/logger.py
  setup.py
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/bayesian_regression_ii.ipynb
  tutorial/source/bo.ipynb
  tutorial/source/easyguide.ipynb
  tutorial/source/ekf.ipynb
  tutorial/source/enumeration.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/gplvm.ipynb
  tutorial/source/jit.ipynb
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_iii.ipynb
  tutorial/source/tensor_shapes.ipynb
  tutorial/source/tracking_1d.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review

#2093 Implement 1d convolution via fft
  pyro/ops/tensor_utils.py
  tests/ops/test_tensor_utils.py
Labels: awaiting review

#2098 Implement ReflectedDistribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/reflected.py
  tests/distributions/conftest.py
Labels: awaiting review, enhancement

#2092 add example usage for contrib.timeseries
  examples/contrib/timeseries/independent_gps.py
  pyro/contrib/timeseries/gp.py
  tests/test_examples.py
Labels: awaiting review

#2094 add CoupledMaternGP to contrib.timeseries
  examples/contrib/timeseries/gp_models.py
  examples/contrib/timeseries/independent_gps.py
  pyro/contrib/timeseries/__init__.py
  pyro/contrib/timeseries/gp.py
  pyro/ops/ssm_gp.py
  pyro/ops/tensor_utils.py
  tests/contrib/timeseries/test_gp.py
  tests/test_examples.py
Labels: awaiting review

#2101 add block_diagonal tensor utility and rename block_diag => block_diag_embed
  pyro/contrib/timeseries/gp.py
  pyro/ops/tensor_utils.py
  tests/ops/test_tensor_utils.py
Labels: awaiting review, easy

#2102 Implement constraints for nn.Parameters of nn.Modules
  docs/source/parameters.rst
  docs/source/pyro.params.txt
  pyro/params/__init__.py
  pyro/params/constrained_parameter.py
  tests/params/test_constrained_parameter.py
Labels: awaiting review

#2099 add GenericLGSSM to contrib.timeseries
  pyro/contrib/timeseries/__init__.py
  pyro/contrib/timeseries/lgssm.py
  tests/contrib/timeseries/test_gp.py
  tests/contrib/timeseries/test_lgssm.py
Labels: awaiting review

#2100 add GenericLGSSMWithGPNoiseModel to contrib.timeseries
  pyro/contrib/timeseries/__init__.py
  pyro/contrib/timeseries/lgssmgp.py
  tests/contrib/timeseries/test_gp.py
  tests/contrib/timeseries/test_lgssm.py
Labels: awaiting review

#2105 Reorganize docs in pyro.contrib.timeseries
  docs/source/contrib.timeseries.rst
  pyro/contrib/timeseries/__init__.py
Labels: awaiting review, documentation, easy

#2106 add support for nu=0.5 to ssm_gp
  pyro/contrib/timeseries/gp.py
  pyro/contrib/timeseries/lgssm.py
  pyro/contrib/timeseries/lgssmgp.py
  pyro/ops/ssm_gp.py
  tests/contrib/timeseries/test_gp.py
  tests/ops/test_ssm_gp.py
Labels: awaiting review, easy
