Repository pyro-ppl/pyro, pull requests merged in 2019-11, with the labels that each got.

#2107 add DependentMaternGP to contrib.timeseries
  pyro/contrib/timeseries/__init__.py
  pyro/contrib/timeseries/gp.py
  pyro/contrib/timeseries/lgssm.py
  tests/contrib/timeseries/test_gp.py
Labels: awaiting review

#2104 Implement a ConstrainedModule for dynamic constraints
  docs/source/parameters.rst
  pyro/params/__init__.py
  pyro/params/constrained_parameter.py
  tests/params/test_constrained_parameter.py
Labels: awaiting review, low priority

#2114 fix typo in svgd.py
  pyro/infer/svgd.py
Labels: awaiting review, easy

#2112 add LinearlyCoupledDependentMaternGP to contrib.timeseries
  pyro/contrib/timeseries/__init__.py
  pyro/contrib/timeseries/gp.py
  tests/contrib/timeseries/test_gp.py
Labels: awaiting review, easy

#2110 Support python bool in TorchDistribution.mask() w/ short circuit for log_prob
  pyro/distributions/torch_distribution.py
  tests/distributions/test_mask.py
Labels: awaiting review

#2115 Rename ReflectedDistribution to FoldedDistribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/folded.py
  tests/distributions/conftest.py
Labels: awaiting review, easy

#2117 clean-up docs in pyro.contrib.timeseries
  pyro/contrib/timeseries/base.py
  pyro/contrib/timeseries/gp.py
  pyro/contrib/timeseries/lgssm.py
  pyro/contrib/timeseries/lgssmgp.py
Labels: awaiting review, easy

#2121 Simplify Predictive class
  pyro/infer/predictive.py
Labels: awaiting review, easy

#2041 Election tutorial
  tutorial/source/elections.ipynb
  tutorial/source/working_memory.ipynb
Labels: awaiting response

#2123 Fix preditive shapes
  pyro/infer/predictive.py
  tests/infer/test_predictive.py
Labels: awaiting review

#2119 Add interface for custom autoguide initialization
  examples/sparse_regression.py
  pyro/infer/autoguide/guides.py
  pyro/infer/autoguide/initialization.py
  tests/infer/test_autoguide.py
  tutorial/source/gmm.ipynb
Labels: awaiting review

#2125 Draw mcmc chains sequentially when num_cpus < num_chains
  pyro/infer/mcmc/adaptation.py
  pyro/infer/mcmc/api.py
  tests/infer/mcmc/test_mcmc_api.py
Labels: WIP

#2130 Allow setting of @constraint descriptors to nn.Parameters
  pyro/params/constrained_parameter.py
  tests/params/test_constrained_parameter.py
Labels: awaiting review

#2129 Support pickling of easyguides
  pyro/contrib/easyguide/easyguide.py
  tests/contrib/easyguide/test_easyguide.py
Labels: awaiting review, easy

#2126 Make autoguides derive from nn.Module
  pyro/infer/autoguide/guides.py
  tests/contrib/autoguide/test_inference.py
  tests/infer/test_autoguide.py
Labels: awaiting review

#2127 Change parametrization of AutoLowRankMultivariateNormal
  pyro/infer/autoguide/guides.py
Labels: awaiting review, discussion

#2134 Implement PyroModule with poutine aware __getattr__
  docs/source/nn.rst
  docs/source/pyro.nn.txt
  pyro/infer/autoguide/guides.py
  pyro/nn/__init__.py
  pyro/nn/module.py
  tests/nn/test_module.py
Labels: awaiting review

#2136 Remove obsolete pyro.params.constrained_property
  docs/source/parameters.rst
  pyro/params/__init__.py
  pyro/params/constrained_parameter.py
  tests/infer/test_autoguide.py
  tests/params/test_constrained_parameter.py
Labels: awaiting review, easy

#2137 Subclass AutoguideList from nn.ModuleList
  pyro/infer/autoguide/guides.py
  pyro/infer/svgd.py
  tests/infer/test_autoguide.py
Labels: awaiting review

#2141 fix typo in pyro.nn.module docstring
  pyro/nn/module.py
Labels: awaiting review, easy

#2140 Make EasyGuide derive from PyroModule
  pyro/contrib/easyguide/easyguide.py
  pyro/nn/module.py
  tests/contrib/easyguide/test_easyguide.py
  tests/infer/test_autoguide.py
  tests/nn/test_module.py
Labels: awaiting review

#2142 Refactor pyro.contrib.timeseries to use PyroModule
  examples/contrib/timeseries/gp_models.py
  pyro/contrib/timeseries/__init__.py
  pyro/contrib/timeseries/base.py
  pyro/contrib/timeseries/gp.py
  pyro/contrib/timeseries/lgssm.py
  pyro/contrib/timeseries/lgssmgp.py
  pyro/nn/__init__.py
  pyro/nn/module.py
  pyro/ops/ssm_gp.py
  tests/contrib/timeseries/test_gp.py
  tests/contrib/timeseries/test_lgssm.py
  tests/ops/test_ssm_gp.py
Labels: awaiting review

#2148 Support saving of PyroModules in PyroParam store
  pyro/nn/module.py
  tests/nn/test_module.py
Labels: awaiting review

#2150 Recursively set attributes for dynamic autoguides
  pyro/infer/autoguide/guides.py
Labels: awaiting review

#2146 Add smoke test for PyroModule based linear regression
  tests/infer/test_autoguide.py
Labels: awaiting review

#2152 Add named_pyro_params method to PyroModule
  pyro/nn/module.py
  tests/nn/test_module.py
Labels: awaiting review

#2156 Tune defaults of Auto*Normal guides
  pyro/infer/autoguide/guides.py
  tests/infer/test_autoguide.py
Labels: awaiting review

#2158 Add more docs to PyroModule
  pyro/infer/autoguide/guides.py
  pyro/nn/module.py
  tests/nn/test_module.py
Labels: awaiting review

#2155 Make Predictive a PyroModule
  pyro/infer/predictive.py
  tests/infer/test_autoguide.py
Labels: awaiting review

#2160 Make it clear when fullname is defined in PyroModule
  pyro/nn/module.py
  pyro/poutine/lift_messenger.py
Labels: awaiting review, refactor

#2135 Use PyroModule in GP
  pyro/contrib/gp/__init__.py
  pyro/contrib/gp/kernels/brownian.py
  pyro/contrib/gp/kernels/coregionalize.py
  pyro/contrib/gp/kernels/dot_product.py
  pyro/contrib/gp/kernels/isotropic.py
  pyro/contrib/gp/kernels/periodic.py
  pyro/contrib/gp/kernels/static.py
  pyro/contrib/gp/likelihoods/binary.py
  pyro/contrib/gp/likelihoods/gaussian.py
  pyro/contrib/gp/likelihoods/multi_class.py
  pyro/contrib/gp/likelihoods/poisson.py
  pyro/contrib/gp/models/gplvm.py
  pyro/contrib/gp/models/gpr.py
  pyro/contrib/gp/models/model.py
  pyro/contrib/gp/models/sgpr.py
  pyro/contrib/gp/models/vgp.py
  pyro/contrib/gp/models/vsgp.py
  pyro/contrib/gp/parameterized.py
  pyro/infer/trace_mmd.py
  pyro/nn/module.py
  tests/contrib/gp/test_models.py
  tests/contrib/gp/test_parameterized.py
  tests/contrib/timeseries/test_gp.py
  tests/nn/test_module.py
  tutorial/source/bo.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/gplvm.ipynb
Labels: awaiting review

#2164 Support syntax to create PyroModule mixin classes
  pyro/nn/module.py
  tests/nn/test_module.py
  tutorial/source/bayesian_regression.ipynb
Labels: awaiting review

#2143 Add multi-sample ELBO computation via Tensor Monte Carlo
  examples/dmm/dmm.py
  pyro/infer/enum.py
  pyro/infer/traceenum_elbo.py
  pyro/poutine/enumerate_messenger.py
  tests/infer/test_enum.py
  tests/infer/test_valid_models.py
  tests/test_examples.py
Labels: awaiting review, enhancement

#2128 Separate summary and print_summary utility
  examples/baseball.py
  examples/eight_schools/mcmc.py
  pyro/infer/mcmc/api.py
  pyro/infer/mcmc/util.py
Labels: awaiting review

#2167 Store args, kwargs in mcmc
  pyro/infer/mcmc/api.py
Labels: awaiting review, discussion, easy

#2166 Raise FutureWarning for deprecated methods/classes
  .codecov.yml
  docs/source/pyro.infer.mcmc.txt
  pyro/contrib/oed/eig.py
  pyro/infer/abstract_infer.py
  pyro/infer/mcmc/util.py
  pyro/infer/predictive.py
  pyro/infer/svi.py
  pyro/primitives.py
  tests/infer/mcmc/test_mcmc_util.py
  tests/infer/mcmc/test_nuts.py
  tests/infer/test_abstract_infer.py
  tests/params/test_module.py
  tests/poutine/test_poutines.py
  tutorial/source/bayesian_regression_ii.ipynb
Labels: awaiting review

#2157 Rewrite poutine.do to represent single-world counterfactuals
  pyro/poutine/condition_messenger.py
  pyro/poutine/do_messenger.py
  pyro/poutine/handlers.py
  tests/poutine/test_counterfactual.py
  tests/poutine/test_poutines.py
  tests/poutine/test_properties.py
Labels: awaiting review, discussion

#2170 Avoid PyroMeta inheriting from ABCMeta
  pyro/contrib/easyguide/easyguide.py
  pyro/nn/module.py
Labels: awaiting review

#2168 Fix SMCFilter, change interface
  examples/smcfilter.py
  pyro/infer/smcfilter.py
  tests/infer/test_smcfilter.py
Labels: awaiting review, bug

#2175 Move contrib.glmm to contrib.oed.glmm
  docs/source/contrib.glmm.rst
  docs/source/contrib.oed.rst
  docs/source/index.rst
  examples/contrib/oed/ab_test.py
  pyro/contrib/oed/glmm/__init__.py
  pyro/contrib/oed/glmm/glmm.py
  pyro/contrib/oed/glmm/guides.py
  pyro/contrib/oed/util.py
  tests/contrib/oed/test_glmm.py
  tests/contrib/oed/test_linear_models_eig.py
Labels: awaiting review, easy

#2172 Add vectorized interface stubs to pyro.markov
  pyro/poutine/handlers.py
  pyro/poutine/markov_messenger.py
Labels: awaiting review, easy

#2179 Test coveralls for coverage info
  .coveragerc
  .travis.yml
  README.md
  tutorial/source/index.rst
Labels: awaiting review

#2181 Implement Levy Stable distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/stable.py
  tests/distributions/conftest.py
  tests/distributions/test_distributions.py
  tests/distributions/test_stable.py
Labels: awaiting review

#2183 Port BART preprocessing script from sandbox to Pyro repo
  docs/source/contrib.examples.rst
  docs/source/index.rst
  pyro/contrib/examples/bart.py
Labels: Examples, awaiting review

#2185 add comment in Poutine tutorial that the first version of LogJointMessenger can only handle observed samples
  tutorial/source/effect_handlers.ipynb
Labels: awaiting review

#2189 Fix equation rendering in OED election tutorial
  tutorial/source/elections.ipynb
  tutorial/source/index.rst
Labels: Examples, awaiting review, easy

#2190 most contributors can't add tags
  CONTRIBUTING.md
Labels: awaiting review

#2144 Add Tensor Monte Carlo loss function and tests
  examples/dmm/dmm.py
  pyro/infer/__init__.py
  pyro/infer/tracetmc_elbo.py
  pyro/infer/util.py
  pyro/poutine/enumerate_messenger.py
  tests/infer/test_tmc.py
  tests/infer/test_valid_models.py
Labels: awaiting review

#2195 add a comment to set_mode in gp tutorial
  tutorial/source/gp.ipynb
Labels: awaiting review, easy

#2194 Drop the unnecessary warning in renyi_elbo
  pyro/infer/renyi_elbo.py
Labels: awaiting review, easy
