Repository pyro-ppl/pyro, pull requests merged in 2019-06, with the labels that each got.

#1891 Share surrogate loss in `tracegraph_elbo`
  pyro/infer/tracegraph_elbo.py
  pyro/infer/util.py
Labels: awaiting review

#1896 Fix PyTorch training in VAE comparison example
  examples/vae/vae_comparison.py
Labels: awaiting review, easy

#1895 Clarify surrogate elbos in `tracegraph_elbo`
  pyro/infer/tracegraph_elbo.py
Labels: awaiting review

#1900 Add lazily-compiled cpp files to package_data
  setup.py
Labels: awaiting review, easy

#1892 add easyguide example to sparse gamma def
  examples/sparse_gamma_def.py
  tests/test_examples.py
Labels: awaiting review

#1903 Fix bug when deleting a constrained param
  pyro/params/param_store.py
  tests/params/test_param.py
Labels: awaiting review, bug, easy

#1887 Sum of squares
  docs/source/distributions.rst
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/polynomial.py
  tests/distributions/test_flows.py
Labels: awaiting review

#1910 Support ReduceLROnPlateau scheduler
  pyro/optim/lr_scheduler.py
  pyro/optim/optim.py
  tests/optim/test_optim.py
Labels: awaiting review

#1915 NUTS: reduce _System usage_. Simpler `logsumexp`
  pyro/infer/mcmc/nuts.py
Labels: awaiting review

#1907 fix docstring in importance.py
  pyro/infer/importance.py
Labels: awaiting review

#1922 Fix max_plate_nesting off-by-one error in vectorized_importance_weights
  pyro/infer/importance.py
Labels: awaiting review, bug, easy

#1923 Add MCMC section to Gaussian mixture model tutorial
  tutorial/source/gmm.ipynb
Labels: Examples, awaiting review

#1927 Ability to clear cached potential energy computation in HMC
  pyro/infer/mcmc/adaptation.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  tests/infer/mcmc/test_hmc.py
Labels: awaiting review

#1933 Force ipython < 7.6.0
  setup.py
Labels: awaiting review
