Repository pyro-ppl/pyro, pull requests merged in 2020-06, with the labels that each got.

#2516 Expose ImproperUniform distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/improper_uniform.py
  pyro/infer/reparam/split.py
  tests/distributions/test_improper_uniform.py
Labels: awaiting review

#2512 Clean up contrib.epidemiology docs
  docs/source/contrib.epidemiology.rst
  pyro/contrib/epidemiology/compartmental.py
  pyro/contrib/epidemiology/models.py
Labels: awaiting review, documentation, easy

#2514 Eliminate need for CompartmentalModel.transition_bwd()
  pyro/contrib/epidemiology/compartmental.py
  pyro/contrib/epidemiology/models.py
Labels: awaiting review, refactor

#2517 Add a time-heterogeneous SIR model
  examples/contrib/epidemiology/sir.py
  pyro/contrib/epidemiology/__init__.py
  pyro/contrib/epidemiology/compartmental.py
  pyro/contrib/epidemiology/models.py
  pyro/contrib/epidemiology/util.py
  tests/contrib/epidemiology/test_models.py
Labels: awaiting review

#2444 Conditional spline
  docs/source/distributions.rst
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/basic.py
  pyro/distributions/transforms/spline.py
  tests/distributions/test_transforms.py
Labels: awaiting review, enhancement

#2521 Eliminate need for CompartmentalModel class variables
  pyro/contrib/epidemiology/compartmental.py
  pyro/contrib/epidemiology/models.py
  pyro/distributions/torch_patch.py
  tests/contrib/epidemiology/test_models.py
Labels: awaiting review, refactor, usability

#2522 Implement continuous-relaxed inference for CompartmentalModel
  examples/contrib/epidemiology/regional.py
  examples/contrib/epidemiology/sir.py
  pyro/contrib/epidemiology/compartmental.py
  pyro/contrib/epidemiology/distributions.py
  pyro/contrib/epidemiology/models.py
  pyro/contrib/epidemiology/util.py
  tests/contrib/epidemiology/test_distributions.py
  tests/contrib/epidemiology/test_models.py
  tests/test_examples.py
Labels: awaiting review

#2523 Support HaarReparam for non-compartmental variables
  docs/source/contrib.epidemiology.rst
  examples/contrib/epidemiology/regional.py
  examples/contrib/epidemiology/sir.py
  pyro/contrib/epidemiology/__init__.py
  pyro/contrib/epidemiology/compartmental.py
  pyro/contrib/epidemiology/models.py
  setup.py
  tests/contrib/epidemiology/test_models.py
  tests/integration_tests/test_conjugate_gaussian_models.py
Labels: awaiting review

#2526 Support jit in CompartmentalModel
  examples/contrib/epidemiology/regional.py
  examples/contrib/epidemiology/sir.py
  pyro/contrib/epidemiology/compartmental.py
  tests/contrib/epidemiology/test_models.py
  tests/test_examples.py
Labels: awaiting review, easy

#2527 Misc fixes to contrib.epidemiology
  examples/contrib/epidemiology/sir.py
  pyro/contrib/epidemiology/compartmental.py
  pyro/contrib/epidemiology/distributions.py
  pyro/infer/mcmc/api.py
  tests/contrib/epidemiology/test_distributions.py
  tests/contrib/epidemiology/test_models.py
  tests/test_examples.py
Labels: awaiting review

#2529 Implement SVI inference for CompartmentalModel
  docs/source/contrib.epidemiology.rst
  examples/contrib/epidemiology/regional.py
  examples/contrib/epidemiology/sir.py
  pyro/contrib/epidemiology/compartmental.py
  tests/contrib/epidemiology/test_models.py
  tests/test_examples.py
Labels: awaiting review

#2532 Xfail flaky tests (epidemiology SVI)
  tests/common.py
  tests/contrib/epidemiology/test_models.py
  tests/test_examples.py
Labels: awaiting review, easy, testing

#2533 Fix shape errors in CompartmentalModel
  pyro/contrib/epidemiology/compartmental.py
  pyro/poutine/util.py
  tests/contrib/epidemiology/test_models.py
  tests/test_examples.py
Labels: awaiting review, testing

#2536 Fix ZeroInflatedDistribution shape and support
  pyro/distributions/zero_inflated.py
  tests/distributions/test_zero_inflated.py
Labels: awaiting review, easy

#2535 Toy mixture model example
  CONTRIBUTING.md
  examples/toy_mixture_model.py
  tests/test_examples.py
  tutorial/source/index.rst
  tutorial/source/toy_mixture_model.rst
Labels: Examples, awaiting review

#2538 Enable AutoNormal,AutoMultivariateNormal in contrib.epidemiology
  pyro/contrib/epidemiology/compartmental.py
  tests/contrib/epidemiology/test_models.py
Labels: awaiting review

#2525 `SplineCoupling` transform
  docs/source/distributions.rst
  pyro/distributions/diag_normal_mixture.py
  pyro/distributions/gaussian_scale_mixture.py
  pyro/distributions/inverse_gamma.py
  pyro/distributions/relaxed_straight_through.py
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/affine_coupling.py
  pyro/distributions/transforms/spline_coupling.py
  pyro/distributions/zero_inflated.py
  tests/distributions/test_transforms.py
Labels: awaiting review, enhancement

#2540 SplineAutoregressive
  docs/source/distributions.rst
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/affine_autoregressive.py
  pyro/distributions/transforms/spline.py
  pyro/distributions/transforms/spline_autoregressive.py
  tests/distributions/test_transforms.py
Labels: awaiting review, enhancement
