Repository pyro-ppl/pyro, pull requests merged in 2020-02, with the labels that each got.

#2295 Block non-stochastic sites from AutoGuide prototype_trace
  pyro/contrib/easyguide/easyguide.py
  pyro/infer/autoguide/guides.py
  pyro/infer/reparam/neutra.py
Labels: awaiting review, easy, refactor

#2301 Add duration validation to HMMs
  pyro/distributions/hmm.py
  pyro/infer/reparam/hmm.py
  tests/distributions/test_hmm.py
  tests/infer/reparam/test_conjugate.py
  tests/infer/reparam/test_hmm.py
Labels: awaiting review, warnings & errors

#2298 Add NeuTra reparam example
  .gitignore
  examples/neutra.py
  pyro/infer/autoguide/guides.py
  pyro/infer/reparam/neutra.py
  tests/test_examples.py
Labels: awaiting review, discussion

#2304 Add GaussianHMM.posterior_rsample, fix .rsample bugs
  pyro/distributions/distribution.py
  pyro/distributions/hmm.py
  pyro/distributions/torch.py
  pyro/distributions/torch_distribution.py
  pyro/infer/reparam/conjugate.py
  tests/distributions/test_hmm.py
  tutorial/source/stable.ipynb
Labels: awaiting review

#2306 Mark PyroModule non-experimental
  pyro/nn/module.py
Labels: awaiting review, easy

#2050 WIP - AutoNormal Guide
  pyro/infer/autoguide/__init__.py
  pyro/infer/autoguide/guides.py
  tests/infer/test_autoguide.py
Labels: awaiting review

#2310 Remove sudo
  .travis.yml
Labels: awaiting review, testing

#2312 Expose .get_dist() method of contrib.timeseries
  pyro/contrib/timeseries/base.py
  pyro/contrib/timeseries/gp.py
  pyro/contrib/timeseries/lgssm.py
  pyro/contrib/timeseries/lgssmgp.py
Labels: awaiting review, easy, refactor

#2313 Add periodic ops for seasonal forecasting
  pyro/ops/tensor_utils.py
  tests/ops/test_tensor_utils.py
Labels: awaiting review, enhancement

#2309 High-level forecasting interface: contrib.forecast
  docs/source/contrib.forecast.rst
  docs/source/index.rst
  docs/source/primitives.rst
  examples/neutra.py
  pyro/contrib/forecast/__init__.py
  pyro/contrib/forecast/forecaster.py
  pyro/contrib/forecast/util.py
  pyro/distributions/hmm.py
  pyro/ops/gaussian.py
  tests/contrib/forecast/test_forecaster.py
  tests/contrib/forecast/test_util.py
  tests/distributions/test_hmm.py
  tests/infer/reparam/test_neutra.py
Labels: awaiting review, enhancement

#2316 Add evaluation module to contrib.forecast
  docs/source/contrib.forecast.rst
  docs/source/infer.autoguide.rst
  pyro/contrib/forecast/__init__.py
  pyro/contrib/forecast/evaluate.py
  pyro/contrib/forecast/forecaster.py
  pyro/primitives.py
  tests/contrib/forecast/test_evaluate.py
Labels: awaiting review, enhancement

#2318 Add a simple contrib.forecasting example
  examples/contrib/forecast/bart.py
  pyro/contrib/forecast/forecaster.py
  tests/test_examples.py
  tutorial/source/forecast_simple.rst
  tutorial/source/index.rst
Labels: Examples, awaiting review

#2321 Support plates in RenyiELBO
  pyro/infer/renyi_elbo.py
  pyro/infer/util.py
  tests/infer/test_inference.py
  tests/infer/test_multi_sample_elbos.py
Labels: awaiting review

#2320 Implement a forecasting-specific optimizer
  examples/contrib/forecast/bart.py
  pyro/contrib/__init__.py
  pyro/contrib/forecast/evaluate.py
  pyro/contrib/forecast/forecaster.py
  pyro/infer/autoguide/guides.py
  pyro/ops/stats.py
  pyro/ops/tensor_utils.py
  pyro/optim/__init__.py
  pyro/optim/dct_adam.py
  pyro/optim/optim.py
  tests/contrib/forecast/test_evaluate.py
  tests/contrib/forecast/test_forecaster.py
  tests/ops/test_stats.py
  tests/ops/test_tensor_utils.py
  tests/optim/test_optim.py
Labels: awaiting review

#2325 Optimize gaussian op for scalar matrix
  pyro/distributions/hmm.py
  pyro/ops/gaussian.py
  pyro/ops/tensor_utils.py
Labels: awaiting review

#2327 Make pyro.deterministic not warn when called outside of inference
  pyro/optim/dct_adam.py
  pyro/primitives.py
  tests/test_primitives.py
Labels: awaiting review, bug, easy

#2323 Support subsampling in AutoDelta, AutoNormal
  pyro/__init__.py
  pyro/contrib/forecast/forecaster.py
  pyro/distributions/torch.py
  pyro/infer/autoguide/guides.py
  pyro/poutine/subsample_messenger.py
  pyro/primitives.py
  tests/contrib/forecast/test_forecaster.py
  tests/infer/test_autoguide.py
  tests/infer/test_valid_models.py
Labels: awaiting review, enhancement

#2328 fix argparse description in bart.py
  examples/contrib/forecast/bart.py
Labels: awaiting review, easy

#2326 Clean up docs for contrib.forecast
  docs/source/contrib.forecast.rst
  docs/source/contrib.timeseries.rst
  pyro/contrib/forecast/forecaster.py
  pyro/contrib/forecast/util.py
Labels: awaiting review, documentation, easy

#2330 Support warm-starting in forecasting module
  pyro/contrib/forecast/evaluate.py
  pyro/contrib/forecast/forecaster.py
  pyro/contrib/forecast/util.py
  pyro/nn/module.py
  tests/contrib/forecast/test_evaluate.py
Labels: awaiting review, enhancement

#2308 Add tutorial for Boosting Black Box Variational Inference
  examples/neutra.py
  tests/infer/reparam/test_neutra.py
  tutorial/source/boosting_bbvi.ipynb
  tutorial/source/index.rst
Labels: Examples, awaiting review
