Repository pyro-ppl/pyro, pull requests merged in 2020-03, with the labels that each got.

#2324 Optimizing tests in GaussianChainTests
  tests/integration_tests/test_conjugate_gaussian_models.py
Labels: WIP, testing

#2332 add duration kwarg to models in contrib.timeseries
  pyro/contrib/timeseries/gp.py
  pyro/contrib/timeseries/lgssm.py
  pyro/contrib/timeseries/lgssmgp.py
Labels: awaiting review, easy

#2331 Support more likelihoods in contrib.forecast module
  pyro/contrib/forecast/util.py
  pyro/distributions/zero_inflated.py
  tests/contrib/forecast/test_util.py
Labels: awaiting review, enhancement

#2334 Support independent GaussianHMMs via dist.IndependentHMM
  docs/source/distributions.rst
  pyro/contrib/forecast/util.py
  pyro/distributions/__init__.py
  pyro/distributions/hmm.py
  tests/contrib/forecast/test_util.py
  tests/distributions/test_hmm.py
Labels: awaiting review, enhancement

#2335 Add a helper to handle seasonality via regression
  docs/source/contrib.forecast.rst
  pyro/ops/tensor_utils.py
  tests/ops/test_tensor_utils.py
Labels: awaiting review, enhancement

#2333 Optimizing slow inference tests
  tests/infer/test_elbo_mapdata.py
  tests/infer/test_inference.py
  tests/integration_tests/test_conjugate_gaussian_models.py
  tests/integration_tests/test_tracegraph_elbo.py
Labels: awaiting review, testing

#2338 Update torchvision dataset url patching
  pyro/contrib/examples/util.py
  tutorial/source/vae.ipynb
Labels: awaiting review, high priority

#2337 Support IndependentHMM in LinearHMMReparam
  pyro/distributions/hmm.py
  pyro/infer/reparam/hmm.py
  tests/infer/reparam/test_hmm.py
Labels: awaiting review, enhancement

#2336 Fix bug in reshape_batch(LinearHMM(...), ...)
  pyro/contrib/forecast/util.py
  tests/contrib/forecast/test_util.py
Labels: awaiting review, bug

#2340 add clip_norm to contrib.forecasting
  pyro/contrib/forecast/forecaster.py
Labels: awaiting review, easy

#2339 Forecasting tutorial 1: univariate, heavy-tailed
  docs/source/contrib.forecast.rst
  pyro/contrib/forecast/evaluate.py
  pyro/ops/stats.py
  tutorial/source/forecasting_i.ipynb
  tutorial/source/index.rst
Labels: Examples, awaiting review

#2341 fix bart directory not found
  pyro/contrib/examples/bart.py
Labels: easy

#2345 Remove pillow-simd requirement
  docs/requirements.txt
  setup.py
Labels: awaiting review, easy

#2343 Add a Forecasting tutorial on state space models
  docs/source/contrib.forecast.rst
  tutorial/source/forecasting_i.ipynb
  tutorial/source/forecasting_ii.ipynb
  tutorial/source/index.rst
Labels: Examples, awaiting review

#2346 Fix LinearHMM docs
  pyro/distributions/hmm.py
Labels: easy

#2349 Automatically expand noise_dist in ForecastingModel.predict()
  pyro/contrib/forecast/forecaster.py
  tests/contrib/forecast/test_forecaster.py
  tutorial/source/forecasting_i.ipynb
Labels: awaiting review

#2347 add HMCForecaster
  docs/source/contrib.forecast.rst
  pyro/contrib/forecast/__init__.py
  pyro/contrib/forecast/evaluate.py
  pyro/contrib/forecast/forecaster.py
  tests/contrib/forecast/test_evaluate.py
  tests/contrib/forecast/test_forecaster.py
Labels: awaiting review

#2348 Add a forecasting tutorial on hierarchical models
  docs/source/contrib.forecast.rst
  pyro/contrib/forecast/forecaster.py
  pyro/ops/stats.py
  tests/contrib/forecast/test_forecaster.py
  tutorial/source/forecasting_i.ipynb
  tutorial/source/forecasting_ii.ipynb
  tutorial/source/forecasting_iii.ipynb
  tutorial/source/index.rst
Labels: Examples, awaiting review

#2351 Include neutra example in tutorials
  tutorial/source/index.rst
  tutorial/source/neutra.rst
Labels: awaiting review, easy

#2353 Make pyro.subsample appear in docs
  docs/source/primitives.rst
  pyro/poutine/runtime.py
Labels: awaiting review, documentation, easy

#2355 Allow jit compile models with params in HMC
  pyro/infer/mcmc/util.py
  tests/infer/mcmc/test_mcmc_util.py
Labels: awaiting review

#2356 make assertion less strict in contrib.timeseries
  pyro/ops/ssm_gp.py
Labels: awaiting review, easy

#2358 Avoid relying on bunzip2
  pyro/contrib/examples/bart.py
Labels: awaiting review, bug, easy

#2362 Fix some tutorial rendering errors
  tutorial/source/boosting_bbvi.ipynb
  tutorial/source/dirichlet_process_mixture.ipynb
Labels: Examples, awaiting review, documentation, easy, website

#2360 Fix nan issue of stable reparam
  pyro/infer/reparam/stable.py
  tests/infer/reparam/test_stable.py
Labels: awaiting review

#2363 Support batched forecasting
  docs/source/contrib.forecast.rst
  pyro/contrib/forecast/forecaster.py
  tests/contrib/forecast/test_forecaster.py
Labels: awaiting review, enhancement

#2364 Add walltime to backtest() results
  pyro/contrib/forecast/evaluate.py
  tests/contrib/forecast/test_evaluate.py
Labels: awaiting review, enhancement

#2367 Fix device placement of InverseGamma distribution
  pyro/distributions/inverse_gamma.py
Labels: awaiting review, bug

#2365 Fix LocScaleReparam, log params in backtest()
  pyro/contrib/forecast/evaluate.py
  pyro/infer/reparam/loc_scale.py
Labels: awaiting review, bug

#2246 Invertible 1x1 convolution
  docs/source/distributions.rst
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/generalized_channel_permute.py
  tests/distributions/test_transforms.py
Labels: awaiting review, enhancement

#2369 Support subsampling in StableReparam
  pyro/infer/reparam/stable.py
  tests/infer/reparam/test_stable.py
Labels: awaiting review

#2370 Support replay of plate(..., subsample=...)
  pyro/poutine/subsample_messenger.py
  pyro/util.py
  tests/infer/test_autoguide.py
Labels: awaiting review

#2371 Gradually reduce batch_size to avoid OOM errors in backtest
  pyro/contrib/forecast/evaluate.py
Labels: awaiting review

#2372 Expose more options to Forecaster
  pyro/contrib/forecast/forecaster.py
  pyro/infer/svi.py
  tests/contrib/forecast/test_forecaster.py
Labels: awaiting review

#2374 Address numerical stability of Geometric log_prob
  pyro/contrib/forecast/util.py
  pyro/distributions/torch.py
  tests/contrib/forecast/test_util.py
  tests/distributions/conftest.py
  tests/distributions/dist_fixture.py
Labels: awaiting review

#2376 Improve the performance of rsample of GaussianHMM with Normal obs
  pyro/distributions/hmm.py
  pyro/ops/gaussian.py
  tests/distributions/test_hmm.py
  tests/ops/test_gaussian.py
Labels: awaiting review

#2378 Conditional Radial transform
  docs/source/distributions.rst
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/planar.py
  pyro/distributions/transforms/radial.py
  tests/distributions/test_transforms.py
Labels: awaiting review, enhancement

#2382 Fix docs for MCMC
  docs/source/pyro.infer.mcmc.txt
  pyro/infer/mcmc/api.py
  pyro/poutine/handlers.py
Labels: awaiting review, documentation, easy

#2379 Update links
  pyro/contrib/minipyro.py
Labels: awaiting response

#2385 Aesthetic improvements to transform docstrings
  pyro/distributions/transforms/affine_autoregressive.py
  pyro/distributions/transforms/affine_coupling.py
  pyro/distributions/transforms/batchnorm.py
  pyro/distributions/transforms/block_autoregressive.py
  pyro/distributions/transforms/cholesky.py
  pyro/distributions/transforms/generalized_channel_permute.py
  pyro/distributions/transforms/householder.py
  pyro/distributions/transforms/lower_cholesky_affine.py
  pyro/distributions/transforms/neural_autoregressive.py
  pyro/distributions/transforms/permute.py
  pyro/distributions/transforms/planar.py
  pyro/distributions/transforms/polynomial.py
  pyro/distributions/transforms/radial.py
  pyro/distributions/transforms/sylvester.py
Labels: awaiting review, easy

#2383 Speed up SubsampleMessenger
  pyro/poutine/subsample_messenger.py
Labels: awaiting review, easy

#2381 Conditional affine coupling layer
  docs/source/distributions.rst
  docs/source/nn.rst
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/affine_coupling.py
  pyro/distributions/transforms/planar.py
  pyro/distributions/transforms/radial.py
  pyro/nn/__init__.py
  pyro/nn/dense_nn.py
  tests/distributions/test_transforms.py
Labels: awaiting review, enhancement

#2384 `log_abs_det_jacobian` will be recalculated when necessary
  pyro/distributions/transforms/affine_autoregressive.py
  pyro/distributions/transforms/block_autoregressive.py
  pyro/distributions/transforms/planar.py
  pyro/distributions/transforms/polynomial.py
  pyro/distributions/transforms/radial.py
  pyro/distributions/transforms/sylvester.py
Labels: awaiting review, bug

#2368 Element-wise Monotonic Rational Spline
  docs/source/distributions.rst
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/spline.py
  tests/distributions/test_transforms.py
Labels: awaiting review, enhancement

#2388 Allow unused params in CSIS inference
  pyro/infer/csis.py
Labels: awaiting review, bug, easy

#2391 Fix PyroModule[nn.GRU] and other RNNs
  pyro/nn/module.py
  tests/nn/test_module.py
Labels: awaiting review, bug

#2389 Add super().__init__() call to Rejector
  pyro/distributions/rejector.py
  pyro/distributions/testing/rejection_gamma.py
Labels: awaiting review, bug
