Repository pyro-ppl/pyro, pull requests merged in 2020-01, with the labels that each got.

#2235 Refactor reparameterization into pyro.infer.reparam
  docs/source/distributions.rst
  docs/source/infer.reparam.rst
  docs/source/inference.rst
  pyro/distributions/__init__.py
  pyro/distributions/hmm.py
  pyro/distributions/reparameterize.py
  pyro/distributions/stable.py
  pyro/infer/reparam/__init__.py
  pyro/infer/reparam/loc_scale.py
  pyro/infer/reparam/neutra.py
  pyro/infer/reparam/reparam.py
  pyro/infer/reparam/stable.py
  pyro/infer/reparam/transform.py
  pyro/ops/gaussian.py
  pyro/poutine/reparam_messenger.py
  tests/distributions/test_reparameterize.py
  tests/distributions/test_stable.py
  tests/infer/mcmc/test_valid_models.py
  tests/infer/reparam/__init__.py
  tests/infer/reparam/test_loc_scale.py
  tests/infer/reparam/test_neutra.py
  tests/infer/reparam/test_stable.py
  tests/infer/reparam/test_transform.py
  tests/infer/test_inference.py
  tests/infer/test_valid_models.py
Labels: awaiting review, enhancement, refactor

#2240 Switch from pillow to pillow-simd
  setup.py
Labels: awaiting review

#2239 Fix MADE author in dmm tutorial
  tutorial/source/dmm.ipynb
Labels: awaiting review

#2241 Expose pyro.ops.tensor_utils in docs
  docs/source/ops.rst
Labels: awaiting review, documentation, easy

#2244 Fixed `ConditionedPlanar` bug to set `event_dim`
  pyro/distributions/transforms/planar.py
Labels: bug

#2248 Fix typo in tensor_shapes.ipynb
  tutorial/source/tensor_shapes.ipynb
Labels: awaiting review, documentation

#2251 Add release management doc
  RELEASE-MANAGEMENT.md
Labels: awaiting review, easy

#2252 Discrete Cosine reparameterizer
  docs/source/conf.py
  docs/source/distributions.rst
  docs/source/infer.reparam.rst
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/discrete_cosine.py
  pyro/infer/reparam/__init__.py
  pyro/infer/reparam/discrete_cosine.py
  pyro/ops/tensor_utils.py
  tests/distributions/test_transforms.py
  tests/infer/reparam/test_discrete_cosine.py
  tests/ops/test_tensor_utils.py
Labels: awaiting review, enhancement

#2256 Rename stable reparam to make way for skewed reparam
  pyro/distributions/hmm.py
  pyro/distributions/stable.py
  pyro/infer/reparam/__init__.py
  pyro/infer/reparam/stable.py
  tests/infer/mcmc/test_valid_models.py
  tests/infer/reparam/test_stable.py
  tests/infer/test_inference.py
  tests/infer/test_valid_models.py
Labels: awaiting review, refactor

#2257 Add instructions on updating license
  CONTRIBUTING.md
  Makefile
  scripts/update_headers.py
Labels: awaiting review, easy

#2260 Refactor StableHMM to LinearHMM
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/hmm.py
  pyro/infer/reparam/stable.py
  tests/distributions/test_hmm.py
  tests/infer/reparam/test_stable.py
Labels: awaiting review, refactor

#2261 Generalize StableHMMReparam to LinearHMMReparam
  docs/source/infer.reparam.rst
  pyro/distributions/hmm.py
  pyro/distributions/torch_distribution.py
  pyro/infer/reparam/__init__.py
  pyro/infer/reparam/hmm.py
  pyro/infer/reparam/reparam.py
  pyro/infer/reparam/stable.py
  tests/contrib/gp/test_parameterized.py
  tests/distributions/test_independent.py
  tests/infer/reparam/test_hmm.py
  tests/infer/reparam/test_stable.py
Labels: awaiting review, enhancement

#2262 Bump dependency versions to torch=1.4 and torchvision=0.5
  .travis.yml
  docs/source/conf.py
  setup.py
Labels: awaiting review, high priority

#2259 Implement general StableReparam
  docs/requirements.txt
  pyro/distributions/stable.py
  pyro/infer/reparam/__init__.py
  pyro/infer/reparam/hmm.py
  pyro/infer/reparam/stable.py
  tests/distributions/test_stable.py
  tests/infer/reparam/test_hmm.py
  tests/infer/reparam/test_stable.py
Labels: awaiting review, enhancement

#2265 Implement StudentT reparameterizer
  docs/source/infer.reparam.rst
  pyro/infer/reparam/__init__.py
  pyro/infer/reparam/hmm.py
  pyro/infer/reparam/studentt.py
  tests/infer/reparam/test_hmm.py
  tests/infer/reparam/test_studentt.py
Labels: awaiting review, enhancement

#2253 Add tutorial on inference with Stable distributions
  pyro/contrib/examples/finance.py
  tutorial/source/index.rst
  tutorial/source/stable.ipynb
Labels: awaiting review, documentation

#2264 improve speed and numerical stability of scale_tril to precision
  pyro/distributions/multivariate_studentt.py
  pyro/distributions/torch.py
  pyro/ops/gamma_gaussian.py
  tests/distributions/test_mvn.py
  tests/distributions/test_mvt.py
Labels: awaiting review

#2267 Bump version to 1.2.0
  examples/air/main.py
  examples/baseball.py
  examples/contrib/autoname/mixture.py
  examples/contrib/autoname/scoping_mixture.py
  examples/contrib/autoname/tree_data.py
  examples/contrib/cevae/synthetic.py
  examples/contrib/gp/sv-dkl.py
  examples/contrib/oed/ab_test.py
  examples/contrib/timeseries/gp_models.py
  examples/dmm/dmm.py
  examples/eight_schools/mcmc.py
  examples/eight_schools/svi.py
  examples/hmm.py
  examples/inclined_plane.py
  examples/lda.py
  examples/lkj.py
  examples/minipyro.py
  examples/rsa/generics.py
  examples/rsa/hyperbole.py
  examples/rsa/schelling.py
  examples/rsa/schelling_false.py
  examples/rsa/semantic_parsing.py
  examples/sparse_gamma_def.py
  examples/sparse_regression.py
  examples/vae/ss_vae_M2.py
  examples/vae/vae.py
  examples/vae/vae_comparison.py
  pyro/__init__.py
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/bayesian_regression_ii.ipynb
  tutorial/source/bo.ipynb
  tutorial/source/easyguide.ipynb
  tutorial/source/ekf.ipynb
  tutorial/source/enumeration.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/gplvm.ipynb
  tutorial/source/jit.ipynb
  tutorial/source/stable.ipynb
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_iii.ipynb
  tutorial/source/tensor_shapes.ipynb
  tutorial/source/tracking_1d.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review

#2269 Fix tutorial build for the website
  tutorial/source/dirichlet_process_mixture.ipynb
  tutorial/source/stable.ipynb
Labels: awaiting review, easy

#2273 add timeseries.rst and update tutorial menu
  tutorial/source/index.rst
  tutorial/source/timeseries.rst
Labels: awaiting review, easy

#2266 Fix for mcmc api transforms None for potential_fn
  pyro/infer/mcmc/api.py
Labels: awaiting review

#2274 Fix latex rendering in Stochastic Volatility Tutorial
  tutorial/source/stable.ipynb
Labels: awaiting review, easy

#2271 bugfix #2270
  pyro/distributions/mixture.py
Labels: awaiting review

#2280 Implement Gaussian.rsample()
  pyro/ops/gaussian.py
  tests/ops/test_gaussian.py
Labels: awaiting review

#2279 Expand MaskedDistribution batch shape to the broadcast of mask and base_dist batch shapes
  pyro/distributions/torch_distribution.py
  tests/distributions/test_mask.py
Labels: awaiting response

#2291 Add cheap test for log joint computation in neutra reparametrizer
  pyro/infer/reparam/neutra.py
  tests/infer/reparam/test_neutra.py
Labels: awaiting review, easy

#2285 Implement GaussianHMM.posterior().rsample()
  pyro/distributions/hmm.py
  pyro/ops/gaussian.py
  tests/distributions/test_hmm.py
Labels: awaiting review, enhancement

#2278 Add in-place method Distribution.has_rsample_()
  pyro/distributions/distribution.py
  pyro/poutine/broadcast_messenger.py
  tests/infer/test_gradient.py
  tests/infer/test_valid_models.py
  tests/poutine/test_poutines.py
Labels: awaiting review

#2289 Implement .conjugate_update() and ConjugateReparam
  docs/source/conf.py
  docs/source/distributions.rst
  docs/source/infer.reparam.rst
  pyro/distributions/distribution.py
  pyro/distributions/hmm.py
  pyro/distributions/torch.py
  pyro/distributions/torch_distribution.py
  pyro/infer/reparam/__init__.py
  pyro/infer/reparam/conjugate.py
  pyro/poutine/reparam_messenger.py
  pyro/poutine/trace_messenger.py
  tests/distributions/test_conjugate_update.py
  tests/infer/reparam/test_conjugate.py
  tests/infer/test_valid_models.py
Labels: awaiting review, enhancement

#2293 Update BART dataset to include 2019 data
  pyro/contrib/examples/bart.py
Labels: awaiting review, easy

#2282 Add AutoNormalizingFlow autoguide
  docs/source/distributions.rst
  docs/source/infer.autoguide.rst
  pyro/distributions/__init__.py
  pyro/distributions/torch_transform.py
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/affine_autoregressive.py
  pyro/infer/autoguide/__init__.py
  pyro/infer/autoguide/guides.py
  pyro/infer/mcmc/hmc.py
  tests/contrib/autoguide/test_inference.py
  tests/infer/reparam/test_neutra.py
  tests/infer/test_autoguide.py
Labels: awaiting review

#2296 Implement dist.Stable.mean, .variance
  pyro/distributions/stable.py
  tests/distributions/test_stable.py
Labels: awaiting review, easy
