Repository pyro-ppl/pyro, pull requests merged in 2020-11, with the labels that each got.

#2685 Use GPyTorch in SpanningTree.log_prob()
  pyro/distributions/spanning_tree.py
Labels: awaiting review, easy

#2686 Update contributing and release docs
  CONTRIBUTING.md
  RELEASE-MANAGEMENT.md
  setup.py
Labels: awaiting review, easy

#2680 Clarify some .forward() docstrings
  pyro/contrib/easyguide/easyguide.py
  pyro/infer/autoguide/guides.py
  pyro/infer/predictive.py
  pyro/nn/auto_reg_nn.py
  pyro/nn/dense_nn.py
Labels: awaiting review, documentation, easy

#2690 clarify docstring for AutoNormal guide
  pyro/infer/autoguide/guides.py
Labels: awaiting review, documentation, easy

#2692 Stabilize math in SpanningTree.log_partition_function
  pyro/distributions/spanning_tree.cpp
  pyro/distributions/spanning_tree.py
Labels: awaiting review

#2693 Implement a GumbelSoftmaxReparam
  docs/source/infer.reparam.rst
  pyro/infer/reparam/__init__.py
  pyro/infer/reparam/softmax.py
  tests/infer/reparam/test_softmax.py
Labels: awaiting review, enhancement

#2695 Fix typo in svi part 2
  tutorial/source/svi_part_ii.ipynb
Labels: awaiting review, easy

#2683 Fixes for PyTorch 1.7 release
  pyro/distributions/torch_patch.py
  pyro/infer/mcmc/api.py
  pyro/ops/fft.py
  pyro/ops/linalg.py
  pyro/ops/stats.py
  pyro/ops/tensor_utils.py
  pyro/poutine/enum_messenger.py
  setup.cfg
  tests/test_examples.py
Labels: awaiting review

#2697 Add a OneTwoMatching distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/coalescent.py
  pyro/distributions/one_two_matching.py
  setup.py
  tests/distributions/test_one_two_matching.py
Labels: awaiting review, enhancement

#2701 Validate if __debug__ by default
  examples/baseball.py
  examples/capture_recapture/cjs.py
  examples/contrib/autoname/mixture.py
  examples/contrib/autoname/tree_data.py
  examples/contrib/cevae/synthetic.py
  examples/contrib/epidemiology/regional.py
  examples/contrib/epidemiology/sir.py
  examples/contrib/forecast/bart.py
  examples/contrib/funsor/hmm.py
  examples/contrib/timeseries/gp_models.py
  examples/cvae/cvae.py
  examples/eight_schools/mcmc.py
  examples/eight_schools/svi.py
  examples/hmm.py
  examples/lda.py
  examples/lkj.py
  examples/mixed_hmm/experiment.py
  examples/mixed_hmm/model.py
  examples/neutra.py
  examples/scanvi/scanvi.py
  examples/sir_hmc.py
  examples/smcfilter.py
  examples/sparse_gamma_def.py
  examples/sparse_regression.py
  examples/toy_mixture_model_discrete_enumeration.py
  examples/vae/ss_vae_M2.py
  examples/vae/vae.py
  examples/vae/vae_comparison.py
  pyro/distributions/util.py
  pyro/infer/util.py
  pyro/poutine/scale_messenger.py
  pyro/poutine/util.py
  pyro/primitives.py
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/bayesian_regression_ii.ipynb
  tutorial/source/bo.ipynb
  tutorial/source/boosting_bbvi.ipynb
  tutorial/source/dirichlet_process_mixture.ipynb
  tutorial/source/easyguide.ipynb
  tutorial/source/ekf.ipynb
  tutorial/source/enumeration.ipynb
  tutorial/source/epi_intro.ipynb
  tutorial/source/forecasting_dlm.ipynb
  tutorial/source/forecasting_i.ipynb
  tutorial/source/forecasting_ii.ipynb
  tutorial/source/forecasting_iii.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/gplvm.ipynb
  tutorial/source/jit.ipynb
  tutorial/source/mle_map.ipynb
  tutorial/source/modules.ipynb
  tutorial/source/stable.ipynb
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_iii.ipynb
  tutorial/source/tensor_shapes.ipynb
  tutorial/source/tracking_1d.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review, low priority, usability, warnings & errors
