Repository pyro-ppl/pyro, pull requests merged in 2020-05, with the labels that each got.

#2456 Expose heuristic num_particles parameter in sir.py
  examples/contrib/epidemiology/sir.py
  pyro/contrib/epidemiology/compartmental.py
  tests/test_examples.py
Labels: awaiting review, easy

#2457 Add example of sparsely observed SIR model
  pyro/contrib/epidemiology/__init__.py
  pyro/contrib/epidemiology/sir.py
  tests/contrib/epidemiology/test_sir.py
Labels: awaiting review, discussion

#2458 cast to float in dmm.py
  examples/dmm/dmm.py
Labels: awaiting review, discussion, easy

#2459 Fix BatchNorm TransformModule
  pyro/distributions/transforms/batchnorm.py
Labels: awaiting review, bug

#2454 Fix expand bug of ExpandedDistribution
  pyro/distributions/torch_distribution.py
  tests/distributions/test_distributions.py
Labels: awaiting review, easy

#2460 Add SIR model with unknown time of initial infection
  pyro/contrib/epidemiology/__init__.py
  pyro/contrib/epidemiology/compartmental.py
  pyro/contrib/epidemiology/sir.py
  pyro/ops/indexing.py
  tests/contrib/epidemiology/test_sir.py
  tests/ops/test_indexing.py
Labels: awaiting review, enhancement

#2448 adding RandomVariable container class around Distribution
  docs/source/contrib.randomvariable.rst
  docs/source/index.rst
  pyro/contrib/randomvariable/__init__.py
  pyro/contrib/randomvariable/random_variable.py
  pyro/distributions/distribution.py
  tests/contrib/randomvariable/test_random_variable.py
Labels: awaiting review

#2462 Return `pyro.distributions.TransformedDistribution` instead of `torch.distributions.TransformedDistribution` when conditioning
  pyro/distributions/conditional.py
Labels: awaiting review

#2463 Add pairwise correlation plot to sir.py
  examples/contrib/epidemiology/sir.py
  pyro/contrib/epidemiology/seir.py
  pyro/contrib/epidemiology/sir.py
Labels: awaiting review, easy

#2435 Conditional generalized channel permute
  docs/source/distributions.rst
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/generalized_channel_permute.py
  tests/distributions/test_transforms.py
Labels: awaiting review, enhancement

#2471 update param doc
  pyro/params/param_store.py
Labels: awaiting review, documentation, easy

#2402 `ConditionalAffineAutoregressive`
  docs/source/distributions.rst
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/affine_autoregressive.py
  pyro/distributions/transforms/affine_coupling.py
  pyro/distributions/transforms/batchnorm.py
  pyro/distributions/transforms/block_autoregressive.py
  pyro/distributions/transforms/householder.py
  pyro/distributions/transforms/neural_autoregressive.py
  pyro/distributions/transforms/permute.py
  pyro/distributions/transforms/planar.py
  pyro/distributions/transforms/polynomial.py
  pyro/distributions/transforms/radial.py
  pyro/distributions/transforms/spline.py
  pyro/distributions/transforms/sylvester.py
  pyro/nn/auto_reg_nn.py
  tests/distributions/test_transforms.py
Labels: awaiting response, enhancement

#2466 Implement a regional SIR model with approximate inference
  examples/contrib/epidemiology/regional.py
  pyro/contrib/epidemiology/__init__.py
  pyro/contrib/epidemiology/compartmental.py
  pyro/contrib/epidemiology/sir.py
  pyro/contrib/epidemiology/util.py
  pyro/contrib/randomvariable/__init__.py
  tests/contrib/epidemiology/__init__.py
  tests/contrib/epidemiology/test_sir.py
  tests/contrib/epidemiology/test_util.py
  tests/contrib/forecast/__init__.py
  tests/test_examples.py
Labels: awaiting review, enhancement

#2477 Fix new flake8 errors
  examples/capture_recapture/cjs.py
  examples/sparse_regression.py
  pyro/distributions/distribution.py
  pyro/poutine/trace_struct.py
  pyro/util.py
  setup.py
Labels: awaiting review, bug, easy

#2473 Refactor HMC to support structured mass matrix
  docs/source/pyro.infer.mcmc.txt
  pyro/infer/mcmc/__init__.py
  pyro/infer/mcmc/adaptation.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  pyro/ops/gamma_gaussian.py
  pyro/ops/integrator.py
  pyro/ops/tensor_utils.py
  tests/infer/mcmc/test_adaptation.py
  tests/infer/mcmc/test_nuts.py
  tests/ops/test_integrator.py
  tests/ops/test_tensor_utils.py
Labels: awaiting review

#2474 Implement a coalescent time distribution
  docs/source/contrib.epidemiology.rst
  docs/source/distributions.rst
  pyro/contrib/epidemiology/seir.py
  pyro/distributions/__init__.py
  pyro/distributions/coalescent.py
  tests/contrib/epidemiology/test_seir.py
  tests/distributions/test_coalescent.py
Labels: awaiting review

#2465 Implement arrow-head precision adaptation scheme
  pyro/infer/mcmc/__init__.py
  pyro/infer/mcmc/adaptation.py
  pyro/infer/mcmc/hmc.py
  pyro/ops/arrowhead.py
  pyro/ops/welford.py
  tests/infer/mcmc/test_adaptation.py
  tests/infer/mcmc/test_nuts.py
  tests/ops/test_arrowhead.py
  tests/ops/test_welford.py
Labels: awaiting review

#2483 Use arrowhead matrix to SIR models
  examples/contrib/epidemiology/sir.py
  pyro/contrib/epidemiology/compartmental.py
  tests/contrib/epidemiology/test_sir.py
  tests/test_examples.py
Labels: awaiting review

#2482 Add initialization strategy that randomly samples values
  pyro/contrib/epidemiology/compartmental.py
  pyro/infer/autoguide/__init__.py
  pyro/infer/autoguide/initialization.py
  tests/infer/mcmc/test_mcmc_util.py
  tests/infer/test_initialization.py
Labels: awaiting review

#2484 Add Poisson approximation to Binomial.sample()
  pyro/contrib/epidemiology/compartmental.py
  pyro/contrib/epidemiology/distributions.py
  pyro/distributions/conjugate.py
  pyro/distributions/torch.py
  tests/distributions/test_binomial.py
Labels: awaiting review

#2486 Add ESS thoreshold logic to SMCFilter
  examples/contrib/epidemiology/regional.py
  examples/contrib/epidemiology/sir.py
  pyro/contrib/epidemiology/compartmental.py
  pyro/infer/smcfilter.py
Labels: awaiting review

#2487 Relax requirements on coal_times
  pyro/distributions/coalescent.py
  tests/contrib/epidemiology/test_seir.py
  tests/distributions/test_coalescent.py
Labels: awaiting review

#2443 Added with_cache() and refactored basic element-wise transforms
  docs/source/distributions.rst
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/basic.py
  pyro/distributions/transforms/discrete_cosine.py
  pyro/distributions/transforms/lower_cholesky_affine.py
  pyro/distributions/transforms/neural_autoregressive.py
  pyro/distributions/transforms/permute.py
  tests/distributions/test_transforms.py
Labels: awaiting review, easy, enhancement, usability

#2488 Use systematic resampling in SMCFilter
  pyro/contrib/epidemiology/compartmental.py
  pyro/infer/smcfilter.py
  tests/infer/test_smcfilter.py
Labels: awaiting review

#2490 Revise binomial approximation interface
  pyro/contrib/epidemiology/compartmental.py
  pyro/contrib/epidemiology/distributions.py
  pyro/distributions/conjugate.py
  pyro/distributions/torch.py
  tests/distributions/test_binomial.py
Labels: awaiting review

#2492 add HaarTransform
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/discrete_cosine.py
  pyro/distributions/transforms/haar.py
  pyro/ops/tensor_utils.py
  tests/distributions/test_haar.py
  tests/distributions/test_transforms.py
Labels: awaiting review

#2493 Add a HaarReparam and use it in contrib.epidemiology
  docs/source/distributions.rst
  docs/source/infer.reparam.rst
  examples/contrib/epidemiology/regional.py
  examples/contrib/epidemiology/sir.py
  pyro/contrib/epidemiology/compartmental.py
  pyro/distributions/transforms/haar.py
  pyro/infer/reparam/__init__.py
  pyro/infer/reparam/discrete_cosine.py
  pyro/infer/reparam/haar.py
  pyro/infer/reparam/unit_jacobian.py
  tests/contrib/epidemiology/test_seir.py
  tests/contrib/epidemiology/test_sir.py
  tests/distributions/test_haar.py
  tests/infer/reparam/test_haar.py
  tests/infer/reparam/test_unit_jacobian.py
  tests/test_examples.py
Labels: awaiting review

#2491 add TruncatedPolyaGamma distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/polya_gamma.py
  tests/distributions/test_polya_gamma.py
Labels: awaiting review

#2494 Fix reraising logic
  pyro/poutine/trace_messenger.py
Labels: awaiting review, easy, warnings & errors

#2495 Implement a SplitReparam and use it in contrib.epidemiology
  docs/source/infer.reparam.rst
  examples/contrib/epidemiology/regional.py
  examples/contrib/epidemiology/sir.py
  pyro/contrib/epidemiology/compartmental.py
  pyro/contrib/epidemiology/util.py
  pyro/infer/mcmc/util.py
  pyro/infer/reparam/__init__.py
  pyro/infer/reparam/split.py
  tests/contrib/conftest.py
  tests/contrib/epidemiology/test_seir.py
  tests/contrib/epidemiology/test_sir.py
  tests/infer/reparam/test_split.py
  tests/test_examples.py
Labels: awaiting review

#2497 Add correlation plot to examples/.../sir.py
  examples/contrib/epidemiology/sir.py
Labels: awaiting review, easy

#2472 Added `dim` keyword arg
  pyro/distributions/transforms/affine_coupling.py
  pyro/distributions/transforms/permute.py
  tests/distributions/test_transforms.py
Labels: awaiting review, easy, enhancement

#2499 Reorganize contrib.epidemiology models
  docs/source/contrib.epidemiology.rst
  examples/contrib/epidemiology/sir.py
  pyro/contrib/epidemiology/__init__.py
  pyro/contrib/epidemiology/models.py
  pyro/contrib/epidemiology/seir.py
  tests/contrib/epidemiology/test_models.py
  tests/contrib/epidemiology/test_seir.py
Labels: awaiting review, easy, refactor

#2500 Add a shifted Stirling approximation to log Beta function
  docs/source/ops.rst
  pyro/contrib/epidemiology/compartmental.py
  pyro/contrib/epidemiology/distributions.py
  pyro/distributions/conjugate.py
  pyro/distributions/torch.py
  pyro/ops/special.py
  tests/distributions/test_binomial.py
  tests/ops/test_special.py
Labels: awaiting review

#2501 Remove installation section in docs
  docs/source/index.rst
  docs/source/installation.rst
Labels: awaiting review

#2502 Use approximate log_beta() in .fit(), .predict()
  examples/sir_hmc.py
  pyro/contrib/epidemiology/compartmental.py
  pyro/contrib/epidemiology/distributions.py
  pyro/contrib/epidemiology/seir.py
  pyro/contrib/epidemiology/util.py
  pyro/distributions/coalescent.py
  pyro/distributions/conjugate.py
  pyro/distributions/extended.py
  pyro/distributions/hmm.py
  pyro/ops/einsum/torch_log.py
  pyro/ops/special.py
  pyro/ops/tensor_utils.py
  tests/distributions/test_extended.py
  tests/ops/test_special.py
  tests/ops/test_tensor_utils.py
Labels: awaiting review

#2504 Bug fix to AffineAutoregressive
  .gitattributes
  pyro/distributions/transforms/affine_autoregressive.py
  tests/distributions/test_transforms.py
Labels: bug, easy

#2508 Fix behavior of disable_validation=False
  pyro/contrib/epidemiology/compartmental.py
  pyro/infer/mcmc/api.py
Labels: awaiting review, usability

#2507 add simple map/mle tutorial
  tutorial/source/index.rst
  tutorial/source/mle_map.ipynb
Labels: awaiting review, documentation, easy

#2509 Resurrect num_quant_bins=2 in contrib.epidemiology
  pyro/contrib/epidemiology/util.py
  tests/contrib/epidemiology/test_models.py
  tests/contrib/epidemiology/test_quant.py
Labels: awaiting review, easy

#2498 Add overdispersed models to contrib.epidemiology
  examples/contrib/epidemiology/regional.py
  examples/contrib/epidemiology/sir.py
  pyro/contrib/epidemiology/__init__.py
  pyro/contrib/epidemiology/compartmental.py
  pyro/contrib/epidemiology/distributions.py
  pyro/contrib/epidemiology/models.py
  tests/contrib/epidemiology/test_distributions.py
  tests/contrib/epidemiology/test_models.py
  tests/test_examples.py
Labels: awaiting review
