Repository pyro-ppl/pyro, pull requests merged in 2020-12, with the labels that each got.

#2706 Silence pyro.param warning if .training is False
  pyro/primitives.py
Labels: awaiting review

#2707 Add a OneOneMatching distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/one_one_matching.py
  tests/distributions/test_one_one_matching.py
  tests/distributions/test_one_two_matching.py
Labels: awaiting review, low priority

#2710 Stabilize Bethe approximation in matching distributions
  pyro/distributions/one_one_matching.py
  pyro/distributions/one_two_matching.py
  tests/distributions/test_one_one_matching.py
  tests/distributions/test_one_two_matching.py
Labels: awaiting review, bug

#2703 VectorizedMarkovMessenger proposal
  pyro/contrib/funsor/__init__.py
  pyro/contrib/funsor/handlers/__init__.py
  pyro/contrib/funsor/handlers/plate_messenger.py
  pyro/contrib/funsor/handlers/trace_messenger.py
  tests/contrib/funsor/test_vectorized_markov.py
Labels: awaiting review, enhancement

#2712 Add rate parameter to CoalescentTimes distribution
  pyro/distributions/coalescent.py
  tests/distributions/test_coalescent.py
Labels: awaiting review, enhancement

#2709 Support MaskedDistribution in contrib.forecast
  pyro/contrib/forecast/util.py
  tests/contrib/forecast/test_util.py
Labels: awaiting review

#2715 Replace custom factor with pyro.factor in tutorials
  tutorial/source/RSA-hyperbole.ipynb
  tutorial/source/RSA-implicature.ipynb
  tutorial/source/search_inference.py
Labels: awaiting review, easy

#2717 Bump Funsor dependency to latest master commit
  setup.py
Labels: awaiting review, easy

#2716 TraceMarkovEnum_ELBO - a trace implementation of ELBO-based SVI that supports model side enumeration of Markov variables
  pyro/contrib/funsor/infer/__init__.py
  pyro/contrib/funsor/infer/traceenum_elbo.py
  tests/contrib/funsor/test_vectorized_markov.py
Labels: awaiting response, enhancement
