Repository pyro-ppl/pyro, pull requests merged in 2020-10, with the labels that each got.

#2643 add support for logits parameterization in zero-inflated distributions
  docs/source/distributions.rst
  pyro/contrib/forecast/util.py
  pyro/distributions/__init__.py
  pyro/distributions/zero_inflated.py
  tests/distributions/test_shapes.py
  tests/distributions/test_zero_inflated.py
  tests/infer/test_enum.py
Labels: awaiting review

#2648 Expand interface of CompartmentalModel.finalize()
  pyro/contrib/epidemiology/compartmental.py
  tests/contrib/epidemiology/test_models.py
Labels: awaiting review

#2649 update readme
  README.md
Labels: documentation

#2650 remove some stale wording in a few tutorials
  tutorial/source/dmm.ipynb
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_iii.ipynb
Labels: Examples

#2642 add scANVI example from single cell transcriptomics
  examples/scanvi/data.py
  examples/scanvi/scanvi.py
  setup.py
  tests/test_examples.py
Labels: Examples, awaiting review

#2652 Add docs for constraints
  docs/source/distributions.rst
  pyro/distributions/constraints.py
Labels: awaiting review, documentation

#2647 Fix exception chaining all over the codebase
  pyro/contrib/autoname/named.py
  pyro/contrib/forecast/util.py
  pyro/infer/discrete.py
  pyro/infer/mcmc/logger.py
  pyro/infer/reparam/neutra.py
  pyro/ops/contract.py
  pyro/ops/packed.py
  pyro/poutine/trace_messenger.py
  pyro/poutine/trace_struct.py
Labels: awaiting response, warnings & errors

#2653 Replace torch.jit.script with torch.jit.script_if_tracing
  pyro/distributions/hmm.py
  pyro/distributions/util.py
Labels: awaiting review, easy, refactor

#2651 added ordered logistic distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/constraints.py
  pyro/distributions/ordered_logistic.py
  tests/distributions/conftest.py
  tests/distributions/test_ordered_logistic.py
  tests/infer/test_valid_models.py
Labels: awaiting review

#2666 simplify pre-processing in scanvi.py
  examples/scanvi/data.py
  examples/scanvi/scanvi.py
Labels: awaiting review, easy

#2664 Allow pyro.factor statements in guide
  pyro/infer/util.py
  pyro/primitives.py
  tests/infer/test_valid_models.py
Labels: awaiting review, easy

#2667 Move DMM data loader to contrib.examples
  examples/dmm.py
  examples/dmm/__init__.py
  examples/dmm/util.py
  examples/hmm.py
  pyro/contrib/examples/polyphonic_data_loader.py
  tests/test_examples.py
  tutorial/source/dmm.ipynb
Labels: Examples, awaiting review, easy

#2614 Make HMM examples compatible with contrib.funsor through pyroapi
  .travis.yml
  examples/contrib/funsor/hmm.py
  setup.py
  tests/common.py
  tests/test_examples.py
Labels: Examples, awaiting review

#2668 Add a "getting started" page to tutorials and rearrange the table of contents
  tutorial/source/capture_recapture.rst
  tutorial/source/cevae.rst
  tutorial/source/dkl.rst
  tutorial/source/einsum.rst
  tutorial/source/epi_regional.rst
  tutorial/source/epi_sir.rst
  tutorial/source/hmm.rst
  tutorial/source/index.rst
  tutorial/source/lda.rst
  tutorial/source/mcmc.rst
  tutorial/source/neutra.rst
  tutorial/source/sir_hmc.rst
  tutorial/source/sparse_gamma.rst
  tutorial/source/svi_horovod.rst
  tutorial/source/timeseries.rst
  tutorial/source/toy_mixture_model_discrete_enumeration.rst
Labels: awaiting review, documentation

#2669 Display all examples in the tutorial index
  tutorial/source/autoname_examples.rst
  tutorial/source/baseball.rst
  tutorial/source/hmm_funsor.rst
  tutorial/source/inclined_plane.rst
  tutorial/source/index.rst
  tutorial/source/lkj.rst
  tutorial/source/mixed_hmm.rst
  tutorial/source/scanvi.rst
  tutorial/source/smcfilter.rst
  tutorial/source/sparse_regression.rst
Labels: awaiting review, documentation

#2662 create OrderedTransform
  docs/source/distributions.rst
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/ordered.py
  tests/distributions/test_ordered_logistic.py
  tests/distributions/test_transforms.py
Labels: awaiting review

#2675 fix scanvi model
  examples/scanvi/data.py
  examples/scanvi/scanvi.py
Labels: awaiting review, easy

#2674 Add more collapse tests
  tests/infer/test_valid_models.py
Labels: awaiting review, easy, testing

#2672 Fixes for 1.5.0 release
  README.md
  setup.py
Labels: awaiting review

#2676 Return funsor.Variable from pyro.sample inside collapse
  pyro/poutine/collapse_messenger.py
  tests/infer/test_valid_models.py
Labels: awaiting review

#2677 Warn if infer_discrete finds no enumerated sites
  pyro/infer/discrete.py
  tests/infer/test_discrete.py
Labels: awaiting review, warnings & errors

#2679 Fix TraceEnum_ELBO.compute_marginals() bug #2678
  pyro/infer/traceenum_elbo.py
  tests/infer/test_enum.py
Labels: awaiting review

#2682 Attempt to fix help(MyDistribution)
  pyro/distributions/distribution.py
Labels: awaiting review, documentation
