Repository pyro-ppl/pyro, pull requests merged in 2020-04, with the labels that each got.

#2395 Fix .travis.yml to use sourceline
  .travis.yml
Labels: awaiting review, easy

#2393 make DCTAdam acknowledge subsample
  pyro/contrib/forecast/forecaster.py
  pyro/optim/dct_adam.py
  pyro/poutine/subsample_messenger.py
  tests/contrib/forecast/test_forecaster.py
  tests/optim/test_optim.py
Labels: awaiting review, discussion

#2398 support NegativeBinomial in forecast
  pyro/contrib/forecast/util.py
  pyro/distributions/zero_inflated.py
  tests/contrib/forecast/test_util.py
Labels: awaiting review

#2399 raise error if mcmc observes subsample site
  pyro/infer/mcmc/util.py
  tests/infer/mcmc/test_mcmc_util.py
Labels: awaiting review

#2377 Fix bugs at reshape_batch LinearHMM
  pyro/contrib/forecast/util.py
  pyro/distributions/torch.py
  tests/contrib/forecast/test_util.py
Labels: awaiting review

#2400 Bump to version 1.3.1
  examples/air/main.py
  examples/baseball.py
  examples/contrib/autoname/mixture.py
  examples/contrib/autoname/scoping_mixture.py
  examples/contrib/autoname/tree_data.py
  examples/contrib/cevae/synthetic.py
  examples/contrib/forecast/bart.py
  examples/contrib/gp/sv-dkl.py
  examples/contrib/oed/ab_test.py
  examples/contrib/timeseries/gp_models.py
  examples/dmm/dmm.py
  examples/eight_schools/mcmc.py
  examples/eight_schools/svi.py
  examples/hmm.py
  examples/inclined_plane.py
  examples/lda.py
  examples/lkj.py
  examples/minipyro.py
  examples/neutra.py
  examples/rsa/generics.py
  examples/rsa/hyperbole.py
  examples/rsa/schelling.py
  examples/rsa/schelling_false.py
  examples/rsa/semantic_parsing.py
  examples/sparse_gamma_def.py
  examples/sparse_regression.py
  examples/vae/ss_vae_M2.py
  examples/vae/vae.py
  examples/vae/vae_comparison.py
  pyro/__init__.py
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/bayesian_regression_ii.ipynb
  tutorial/source/bo.ipynb
  tutorial/source/easyguide.ipynb
  tutorial/source/ekf.ipynb
  tutorial/source/enumeration.ipynb
  tutorial/source/forecasting_i.ipynb
  tutorial/source/forecasting_ii.ipynb
  tutorial/source/forecasting_iii.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/gplvm.ipynb
  tutorial/source/jit.ipynb
  tutorial/source/stable.ipynb
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_iii.ipynb
  tutorial/source/tensor_shapes.ipynb
  tutorial/source/tracking_1d.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review

#2405 Support use of PyroParam and PyroSample as decorators
  pyro/nn/module.py
  pyro/params/param_store.py
  tests/nn/test_module.py
Labels: awaiting review, discussion

#2403 Add a PyroModule tutorial
  tutorial/Makefile
  tutorial/source/index.rst
  tutorial/source/modules.ipynb
Labels: Examples, awaiting review

#2406 Remove unimported `dist.` from tensor shapes tutorial
  tutorial/source/tensor_shapes.ipynb
Labels: awaiting review

#2411 ConditionalHouseholder
  docs/source/distributions.rst
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/householder.py
  pyro/distributions/transforms/sylvester.py
  tests/distributions/test_transforms.py
Labels: awaiting review, easy, enhancement

#2413 Allow bounded support in DiscreteCosineReparam
  pyro/infer/reparam/discrete_cosine.py
  tests/infer/reparam/test_discrete_cosine.py
Labels: awaiting review

#2414 Add extended Binomial and BetaBinomial distributions
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/constraints.py
  pyro/distributions/extended.py
  pyro/distributions/transforms/generalized_channel_permute.py
  tests/distributions/conftest.py
  tests/distributions/test_extended.py
Labels: awaiting review

#2412 ConditionalNeuralAutoregressive
  docs/source/distributions.rst
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/affine_autoregressive.py
  pyro/distributions/transforms/affine_coupling.py
  pyro/distributions/transforms/batchnorm.py
  pyro/distributions/transforms/block_autoregressive.py
  pyro/distributions/transforms/generalized_channel_permute.py
  pyro/distributions/transforms/householder.py
  pyro/distributions/transforms/neural_autoregressive.py
  pyro/distributions/transforms/permute.py
  pyro/distributions/transforms/planar.py
  pyro/distributions/transforms/radial.py
  pyro/distributions/transforms/sylvester.py
  tests/distributions/test_transforms.py
Labels: awaiting review, easy, enhancement

#2416 Fix retry logic in MCMC _get_init_params()
  pyro/infer/mcmc/util.py
Labels: awaiting review, easy

#2419 Implement safe_log() to avoid infinite gradients
  pyro/ops/einsum/torch_log.py
  pyro/ops/tensor_utils.py
  tests/ops/test_tensor_utils.py
Labels: awaiting review, easy

#2417 Expose initialization strategy in HMC
  pyro/infer/autoguide/__init__.py
  pyro/infer/autoguide/initialization.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  pyro/infer/mcmc/util.py
  tests/infer/mcmc/test_mcmc_api.py
  tests/infer/mcmc/test_mcmc_util.py
Labels: awaiting review

#2418 Fix backward printing in warn_if_nan, warn_if_inf
  pyro/util.py
  tests/test_util.py
Labels: awaiting review, warnings & errors

#2420 avoid finding init_params when unnecessary
  pyro/infer/mcmc/api.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/util.py
  pyro/poutine/handlers.py
  tests/infer/mcmc/test_mcmc_util.py
  tutorial/source/dmm.ipynb
  tutorial/source/modules.ipynb
Labels: awaiting review

#2422 Stop using deprecated PyTorch function signatures.
  pyro/optim/clipped_adam.py
Labels: awaiting review

#2424 Stop using a deprecated torch function in adagrad_rmsprop.py.
  pyro/optim/adagrad_rmsprop.py
Labels: awaiting review

#2410 Example: discrete SIR models with HMC inference
  Makefile
  examples/sir_hmc.py
  pyro/distributions/hmm.py
  setup.cfg
  tests/test_examples.py
  tutorial/source/_static/img/sir_hmc/energy-trace.png
  tutorial/source/_static/img/sir_hmc/forecast.png
  tutorial/source/_static/img/sir_hmc/parameters.png
  tutorial/source/index.rst
  tutorial/source/sir_hmc.rst
Labels: Examples, awaiting review

#2421 fix DPMM tutorial and update make scrub
  tutorial/source/RSA-hyperbole.ipynb
  tutorial/source/RSA-implicature.ipynb
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/bayesian_regression_ii.ipynb
  tutorial/source/bo.ipynb
  tutorial/source/boosting_bbvi.ipynb
  tutorial/source/cleannb.py
  tutorial/source/csis.ipynb
  tutorial/source/custom_objectives.ipynb
  tutorial/source/dirichlet_process_mixture.ipynb
  tutorial/source/dmm.ipynb
  tutorial/source/easyguide.ipynb
  tutorial/source/effect_handlers.ipynb
  tutorial/source/ekf.ipynb
  tutorial/source/elections.ipynb
  tutorial/source/enumeration.ipynb
  tutorial/source/forecasting_i.ipynb
  tutorial/source/forecasting_ii.ipynb
  tutorial/source/forecasting_iii.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/gplvm.ipynb
  tutorial/source/intro_part_i.ipynb
  tutorial/source/intro_part_ii.ipynb
  tutorial/source/jit.ipynb
  tutorial/source/modules.ipynb
  tutorial/source/ss-vae.ipynb
  tutorial/source/stable.ipynb
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_ii.ipynb
  tutorial/source/svi_part_iii.ipynb
  tutorial/source/tensor_shapes.ipynb
  tutorial/source/tracking_1d.ipynb
  tutorial/source/vae.ipynb
  tutorial/source/working_memory.ipynb
Labels: awaiting review, low priority

#2425 Implement structured mass matrix in HMC
  pyro/infer/mcmc/adaptation.py
  pyro/infer/mcmc/hmc.py
  pyro/infer/mcmc/nuts.py
  pyro/ops/integrator.py
  tests/infer/mcmc/test_adaptation.py
  tests/infer/mcmc/test_nuts.py
Labels: awaiting review

#2428 Use full mass matrix for globals in SIR example
  examples/sir_hmc.py
  tests/test_examples.py
Labels: awaiting review, easy

#2429 Fix recovery_time to known value in SIR models
  examples/sir_hmc.py
  tutorial/source/_static/img/sir_hmc/energy-trace.png
  tutorial/source/_static/img/sir_hmc/forecast.png
  tutorial/source/_static/img/sir_hmc/parameters.png
  tutorial/source/sir_hmc.rst
Labels: awaiting review

#2430 Add smoothing parameter to Discrete Cosine transform and reparam
  pyro/distributions/transforms/discrete_cosine.py
  pyro/infer/reparam/discrete_cosine.py
  tests/distributions/test_transforms.py
  tests/infer/reparam/test_discrete_cosine.py
Labels: awaiting review, enhancement

#2432 expose MaskedDistribution to pyro.distributions namespace
  docs/source/distributions.rst
  pyro/distributions/__init__.py
Labels: awaiting review, easy

#2433 Fix clamping bug in SIR example's quantize helpers
  examples/sir_hmc.py
Labels: awaiting review, bug

#2431 Fix SIR predict() use of reparameterizers
  examples/sir_hmc.py
  tests/test_examples.py
Labels: awaiting review, bug

#2434 add quintic spline quantization strategy to sir_hmc.py
  examples/sir_hmc.py
  tests/test_examples.py
Labels: awaiting review

#2436 Added permutation of `AutoRegressiveNN` to buffer
  pyro/nn/auto_reg_nn.py
Labels: awaiting review, bug, easy

#2437 Start a contrib.epidemiology module
  docs/source/contrib.epidemiology.rst
  docs/source/contrib.forecast.rst
  docs/source/contrib.minipyro.rst
  docs/source/index.rst
  examples/contrib/epidemiology/sir.py
  examples/sir_hmc.py
  pyro/contrib/__init__.py
  pyro/contrib/epidemiology/__init__.py
  pyro/contrib/epidemiology/compartmental.py
  pyro/contrib/epidemiology/sir.py
  pyro/contrib/epidemiology/util.py
  tests/contrib/epidemiology/test_sir.py
  tests/test_examples.py
Labels: awaiting review

#2438 Remove DCT and higher order spline from sir_hmc.py
  examples/sir_hmc.py
  tests/test_examples.py
Labels: awaiting review, easy

#2439 Allow negative total_count in Extended distributions
  examples/sir_hmc.py
  pyro/contrib/epidemiology/sir.py
  pyro/distributions/extended.py
  tests/distributions/test_extended.py
Labels: awaiting review

#2440 add more quantization strategies to contrib.epi
  examples/contrib/epidemiology/sir.py
  pyro/contrib/epidemiology/compartmental.py
  pyro/contrib/epidemiology/sir.py
  pyro/contrib/epidemiology/util.py
  tests/contrib/epidemiology/test_quant.py
  tests/test_examples.py
Labels: awaiting review

#2445 Simplify compartmental model interface
  examples/contrib/epidemiology/sir.py
  pyro/contrib/epidemiology/__init__.py
  pyro/contrib/epidemiology/compartmental.py
  pyro/contrib/epidemiology/sir.py
  tests/contrib/epidemiology/test_sir.py
Labels: awaiting review

#2446 Implement a simple SEIR model
  docs/source/contrib.epidemiology.rst
  examples/contrib/epidemiology/sir.py
  pyro/contrib/epidemiology/__init__.py
  pyro/contrib/epidemiology/seir.py
  pyro/contrib/epidemiology/sir.py
  tests/contrib/epidemiology/test_seir.py
  tests/test_examples.py
Labels: awaiting review, enhancement

#2427 Add header check to lint stage
  Makefile
  scripts/update_headers.py
Labels: awaiting review, easy, low priority

#2450 Add a factory for Poisson / NegativeBinomial / Binomial / BetaBinomial
  docs/source/contrib.epidemiology.rst
  pyro/contrib/epidemiology/__init__.py
  pyro/contrib/epidemiology/distributions.py
  pyro/contrib/epidemiology/seir.py
  pyro/contrib/epidemiology/sir.py
  tests/contrib/epidemiology/test_distributions.py
  tests/contrib/epidemiology/test_seir.py
  tests/contrib/epidemiology/test_sir.py
Labels: awaiting review

#2452 Use SMC to initialize compartmental models
  pyro/contrib/epidemiology/compartmental.py
  pyro/contrib/epidemiology/seir.py
  pyro/contrib/epidemiology/sir.py
Labels: awaiting review

#2451 Implement overdispersed SIR and SEIR models
  examples/contrib/epidemiology/sir.py
  pyro/contrib/epidemiology/__init__.py
  pyro/contrib/epidemiology/compartmental.py
  pyro/contrib/epidemiology/distributions.py
  pyro/contrib/epidemiology/seir.py
  pyro/contrib/epidemiology/sir.py
  tests/contrib/epidemiology/test_seir.py
  tests/contrib/epidemiology/test_sir.py
  tests/test_examples.py
Labels: awaiting review

#2455 Change SEIR models to observe S2E rather than E2I
  pyro/contrib/epidemiology/seir.py
Labels: awaiting review, easy
