Repository pyro-ppl/pyro, pull requests merged in 2020-09, with the labels that each got.

#2587 Reducing code duplication in minipyro
  tests/contrib/test_minipyro.py
Labels: awaiting response, refactor

#2617 Fix LKJ sample shape bug
  pyro/distributions/lkj.py
  tests/distributions/test_lkj.py
Labels: awaiting review, bug, easy

#2611 Add a basic Trace_ELBO and JIT ELBOs to contrib.funsor
  pyro/contrib/funsor/__init__.py
  pyro/contrib/funsor/handlers/enum_messenger.py
  pyro/contrib/funsor/handlers/plate_messenger.py
  pyro/contrib/funsor/infer/__init__.py
  pyro/contrib/funsor/infer/elbo.py
  pyro/contrib/funsor/infer/trace_elbo.py
  pyro/contrib/funsor/infer/traceenum_elbo.py
  pyro/contrib/funsor/infer/tracetmc_elbo.py
  pyro/infer/enum.py
  tests/contrib/funsor/conftest.py
  tests/contrib/funsor/test_pyroapi_funsor.py
Labels: awaiting review

#2621 Fix enumeration notebook tiny problem
  tutorial/source/enumeration.ipynb
Labels: Examples

#2622 Fix subsample docs
  pyro/primitives.py
Labels: awaiting review, easy

#2623 Simple change to make DiagNormal and BNAF be plotted side-by-side
  examples/neutra.py
Labels: Examples, awaiting response

#2626 Adding CVAE tutorial
  examples/cvae/baseline.py
  examples/cvae/cvae.py
  examples/cvae/main.py
  examples/cvae/mnist.py
  examples/cvae/util.py
  tests/test_examples.py
  tutorial/source/cvae.ipynb
  tutorial/source/index.rst
Labels: awaiting review

#2620 Implement a funsor-based poutine.collapse
  docs/source/pyro.poutine.txt
  pyro/distributions/distribution.py
  pyro/infer/abstract_infer.py
  pyro/poutine/__init__.py
  pyro/poutine/collapse_messenger.py
  pyro/poutine/handlers.py
  setup.py
  tests/infer/test_gradient.py
  tests/infer/test_valid_models.py
Labels: awaiting review

#2631 Add regression test for #2627
  tests/infer/mcmc/test_valid_models.py
Labels: awaiting review, easy

#2632 Support tracing of latents in contrib.forecast
  pyro/contrib/forecast/forecaster.py
  tests/contrib/forecast/test_forecaster.py
Labels: awaiting review, enhancement

#2635 Add a block_plate() helper
  pyro/poutine/messenger.py
  pyro/poutine/plate_messenger.py
  pyro/primitives.py
  tests/infer/test_valid_models.py
Labels: awaiting review, discussion

#2637 Adding training visualization to the CVAE tutorial
  tutorial/source/cvae.ipynb
Labels: Examples, awaiting response

#2638 Fix model-directed subsampling in AutoGuide
  pyro/infer/autoguide/guides.py
  tests/infer/test_autoguide.py
Labels: awaiting review, bug, easy

#2636 Support HaarReparam in contrib.forecast
  pyro/contrib/forecast/forecaster.py
  pyro/contrib/forecast/util.py
  pyro/infer/reparam/discrete_cosine.py
  pyro/infer/reparam/haar.py
  pyro/infer/reparam/unit_jacobian.py
  tests/contrib/forecast/test_forecaster.py
  tutorial/source/forecasting_i.ipynb
Labels: awaiting review

#2640 Optimize logmatmulexp() and friends
  pyro/distributions/hmm.py
  pyro/distributions/spanning_tree.py
  pyro/ops/einsum/torch_log.py
Labels: awaiting review, easy

#2641 Fix cyclic import in DistributionMeta
  pyro/distributions/distribution.py
  pyro/poutine/collapse_messenger.py
Labels: awaiting review, bug

#2645 Fix forecaster replay logic
  pyro/contrib/forecast/forecaster.py
Labels: awaiting review, bug, easy

#2646 Add an optional .finalize() method to CompartmentalModel
  pyro/contrib/epidemiology/compartmental.py
  tests/contrib/epidemiology/test_models.py
Labels: awaiting review
