Repository pyro-ppl/pyro, pull requests merged in 2020-08, with the labels that each got.

#2586 [WIP] Fix summations over repeated plate dims in RenyiELBO
  pyro/infer/util.py
  tests/infer/test_inference.py
Labels: awaiting review

#2583 Initialize contrib.funsor with new primitives, pyroapi backend, and some tests
  .travis.yml
  Makefile
  docs/requirements.txt
  docs/source/contrib.funsor.rst
  docs/source/index.rst
  pyro/contrib/__init__.py
  pyro/contrib/funsor/__init__.py
  pyro/contrib/funsor/handlers/__init__.py
  pyro/contrib/funsor/handlers/named_messenger.py
  pyro/contrib/funsor/handlers/primitives.py
  pyro/contrib/funsor/handlers/runtime.py
  pyro/contrib/funsor/infer/__init__.py
  pyro/poutine/handlers.py
  pyro/poutine/messenger.py
  setup.py
  tests/contrib/funsor/conftest.py
  tests/contrib/funsor/test_named_handlers.py
  tests/contrib/funsor/test_pyroapi_funsor.py
Labels: awaiting review, enhancement

#2591 Fix MCMC with potential_fn issue
  pyro/infer/mcmc/api.py
  tests/infer/mcmc/test_mcmc_api.py
Labels: awaiting review

#2584 Low-level tutorial for contrib.funsor
  tutorial/source/contrib_funsor_intro_i.ipynb
  tutorial/source/index.rst
Labels: Examples, awaiting review, documentation

#2588 Add a second, higher-level tutorial for contrib.funsor
  pyro/contrib/funsor/handlers/named_messenger.py
  tutorial/source/contrib_funsor_intro_ii.ipynb
  tutorial/source/index.rst
Labels: Examples, awaiting review, documentation

#2599 Implement a detach() helper that works on distributions
  pyro/distributions/util.py
  pyro/infer/tracegraph_elbo.py
  pyro/infer/util.py
  setup.cfg
  tests/distributions/test_util.py
Labels: awaiting review

#2589 Add basic parallel and sequential enumeration support to contrib.funsor
  pyro/contrib/funsor/handlers/__init__.py
  pyro/contrib/funsor/handlers/enum_messenger.py
  pyro/contrib/funsor/handlers/replay_messenger.py
  pyro/contrib/funsor/handlers/trace_messenger.py
  tests/contrib/funsor/test_named_handlers.py
  tests/contrib/funsor/test_pyroapi_funsor.py
  tests/contrib/funsor/test_valid_models_enum.py
Labels: awaiting review, enhancement

#2594 Implement sequential plate in contrib.funsor
  pyro/contrib/funsor/handlers/plate_messenger.py
  tests/contrib/funsor/test_valid_models_sequential_plate.py
Labels: Blocked, awaiting review

#2593 Implement vectorized plate and subsampling in contrib.funsor
  pyro/contrib/funsor/__init__.py
  pyro/contrib/funsor/handlers/__init__.py
  pyro/contrib/funsor/handlers/plate_messenger.py
  pyro/infer/enum.py
  tests/contrib/funsor/test_valid_models_plate.py
  tests/contrib/funsor/test_valid_models_sequential_plate.py
Labels: awaiting review

#2604 Fix parallel pytest test collection
  tests/common.py
  tests/infer/mcmc/test_mcmc_util.py
Labels: awaiting review, easy

#2595 Implement sampling enumeration strategies and TraceTMC_ELBO in contrib.funsor
  pyro/contrib/funsor/handlers/enum_messenger.py
  pyro/contrib/funsor/infer/__init__.py
  pyro/contrib/funsor/infer/tracetmc_elbo.py
  setup.py
  tests/contrib/funsor/test_tmc.py
Labels: awaiting review

#2596 Implement fully functioning TraceEnum_ELBO in contrib.funsor
  pyro/contrib/funsor/handlers/plate_messenger.py
  pyro/contrib/funsor/handlers/replay_messenger.py
  pyro/contrib/funsor/infer/__init__.py
  pyro/contrib/funsor/infer/traceenum_elbo.py
  pyro/contrib/funsor/infer/tracetmc_elbo.py
  tests/contrib/funsor/test_enum_funsor.py
Labels: awaiting review

#2609 skip print summary if mcmc samples are empty
  pyro/infer/mcmc/util.py
Labels: awaiting review, easy
