Repository pyro-ppl/pyro, pull requests merged in 2020-07, with the labels that each got.

#2549 Fix notebook tests by temporarily ignoring FutureWarning
  .travis.yml
  scripts/update_headers.py
Labels: awaiting review

#2544 Test for whether `TransformModule`s work for density estimation
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/householder.py
  pyro/distributions/transforms/planar.py
  pyro/distributions/transforms/radial.py
  pyro/distributions/transforms/spline.py
  tests/distributions/test_transforms.py
Labels: awaiting review, bug

#2553 Add intro tutorial to contrib.epidemiology
  docs/source/contrib.epidemiology.rst
  pyro/contrib/epidemiology/compartmental.py
  tutorial/source/enumeration.ipynb
  tutorial/source/epi_intro.ipynb
  tutorial/source/epi_regional.rst
  tutorial/source/epi_sir.rst
  tutorial/source/index.rst
  tutorial/source/sir_hmc.rst
Labels: awaiting review

#2554 tweak sparse regression example
  examples/sparse_regression.py
Labels: awaiting review, easy

#2558 Add advanced modeling section to epidemiology intro tutorial
  tutorial/source/epi_intro.ipynb
Labels: Examples, awaiting review

#2559 Add an SEIRD example with custom .compute_flows()
  pyro/contrib/epidemiology/models.py
  tests/contrib/epidemiology/test_models.py
  tutorial/source/epi_intro.ipynb
Labels: awaiting review

#2563 Tweak defaults for CompartmentalModel.fit_mcmc()
  pyro/contrib/epidemiology/compartmental.py
  tests/contrib/epidemiology/test_models.py
  tutorial/source/epi_intro.ipynb
Labels: awaiting review, easy

#2551 Dense MatrixExponential Transform
  docs/source/distributions.rst
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/affine_autoregressive.py
  pyro/distributions/transforms/affine_coupling.py
  pyro/distributions/transforms/block_autoregressive.py
  pyro/distributions/transforms/cholesky.py
  pyro/distributions/transforms/householder.py
  pyro/distributions/transforms/matrix_exponential.py
  pyro/distributions/transforms/neural_autoregressive.py
  pyro/distributions/transforms/permute.py
  pyro/distributions/transforms/planar.py
  pyro/distributions/transforms/polynomial.py
  pyro/distributions/transforms/radial.py
  pyro/distributions/transforms/spline_autoregressive.py
  pyro/distributions/transforms/spline_coupling.py
  pyro/distributions/transforms/sylvester.py
  tests/distributions/test_transforms.py
Labels: awaiting review, enhancement

#2561 Address cholesky issue with arrowhead mass trix
  pyro/ops/arrowhead.py
Labels: awaiting review

#2542 First Normalizing flows Tutorial
  pyro/distributions/conditional.py
  pyro/distributions/torch_patch.py
  pyro/distributions/transforms/spline.py
  setup.py
  tutorial/source/index.rst
  tutorial/source/normalizing_flows_i.ipynb
Labels: Examples, awaiting review, documentation

#2565 Bump to version 1.4.0
  examples/air/main.py
  examples/baseball.py
  examples/contrib/autoname/mixture.py
  examples/contrib/autoname/scoping_mixture.py
  examples/contrib/autoname/tree_data.py
  examples/contrib/cevae/synthetic.py
  examples/contrib/epidemiology/regional.py
  examples/contrib/epidemiology/sir.py
  examples/contrib/forecast/bart.py
  examples/contrib/gp/sv-dkl.py
  examples/contrib/oed/ab_test.py
  examples/contrib/timeseries/gp_models.py
  examples/dmm/dmm.py
  examples/eight_schools/mcmc.py
  examples/eight_schools/svi.py
  examples/hmm.py
  examples/inclined_plane.py
  examples/lda.py
  examples/lkj.py
  examples/minipyro.py
  examples/neutra.py
  examples/rsa/generics.py
  examples/rsa/hyperbole.py
  examples/rsa/schelling.py
  examples/rsa/schelling_false.py
  examples/rsa/semantic_parsing.py
  examples/sir_hmc.py
  examples/sparse_gamma_def.py
  examples/sparse_regression.py
  examples/toy_mixture_model_discrete_enumeration.py
  examples/vae/ss_vae_M2.py
  examples/vae/vae.py
  examples/vae/vae_comparison.py
  pyro/__init__.py
  tutorial/source/air.ipynb
  tutorial/source/bayesian_regression.ipynb
  tutorial/source/bayesian_regression_ii.ipynb
  tutorial/source/bo.ipynb
  tutorial/source/easyguide.ipynb
  tutorial/source/ekf.ipynb
  tutorial/source/enumeration.ipynb
  tutorial/source/epi_intro.ipynb
  tutorial/source/forecasting_i.ipynb
  tutorial/source/forecasting_ii.ipynb
  tutorial/source/forecasting_iii.ipynb
  tutorial/source/gmm.ipynb
  tutorial/source/gp.ipynb
  tutorial/source/gplvm.ipynb
  tutorial/source/jit.ipynb
  tutorial/source/modules.ipynb
  tutorial/source/stable.ipynb
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_iii.ipynb
  tutorial/source/tensor_shapes.ipynb
  tutorial/source/tracking_1d.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review

#2566 Fix tutorial TOC
  tutorial/source/mle_map.ipynb
Labels: awaiting review, easy

#2569 Add favicon to tutorials
  tutorial/source/_static/img/favicon/favicon.ico
  tutorial/source/conf.py
Labels: Examples, awaiting review, easy

#2575 Add a horovod optimizer and example
  docs/source/conf.py
  docs/source/pyro.optim.txt
  examples/svi_horovod.py
  pyro/optim/__init__.py
  pyro/optim/horovod.py
  setup.py
  tests/common.py
  tests/test_examples.py
  tutorial/source/index.rst
  tutorial/source/svi_horovod.rst
Labels: Examples, awaiting review, enhancement

#2576 removed explicit calls to `forward` in VAE tutorial
  tutorial/source/ss-vae.ipynb
  tutorial/source/vae.ipynb
Labels: Examples, awaiting review

#2573 ConditionalMatrixExponential
  docs/source/distributions.rst
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/matrix_exponential.py
  pyro/distributions/transforms/radial.py
  tests/distributions/test_transforms.py
Labels: awaiting review, enhancement

#2574 ConditionalSplineAutoregressive (w/o isort)
  docs/source/distributions.rst
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/spline_autoregressive.py
  tests/distributions/test_transforms.py
Labels: awaiting review, enhancement

#2582 Add git attributes
  .gitattributes
Labels: awaiting review, easy
