Repository pyro-ppl/pyro, pull requests merged in 2021-09, with the labels that each got.

#2824 Add automatic dependency tracking to AutoStructured guide
  docs/source/infer.util.rst
  docs/source/inference.rst
  pyro/infer/autoguide/guides.py
  pyro/infer/inspect.py
  pyro/poutine/messenger.py
  tests/infer/test_autoguide.py
  tests/infer/test_inspect.py
Labels: enhancement, awaiting review

#2918 Add pyro.util.deep_to() to recursively call .to() on Python data structures
  pyro/distributions/util.py
  tests/distributions/test_util.py
Labels: enhancement, usability, awaiting review

#2884 Add automatic reparametrization strategies
  docs/source/infer.reparam.rst
  pyro/distributions/projected_normal.py
  pyro/distributions/stable.py
  pyro/infer/reparam/__init__.py
  pyro/infer/reparam/strategies.py
  pyro/infer/reparam/transform.py
  pyro/poutine/reparam_messenger.py
  tests/infer/reparam/test_strategies.py
Labels: enhancement, awaiting review

#2925 Enable loading optimizer to a specific device
  pyro/optim/optim.py
Labels: enhancement, awaiting review

#2927 Fix Cholesky error handling
  pyro/ops/integrator.py
Labels: awaiting review

#2930 Update coalescent.py
  pyro/distributions/coalescent.py
Labels: documentation

#2934 Fix multi-sample tests in contribfunsor by scaling samples manually
  pyro/contrib/funsor/handlers/enum_messenger.py
  setup.py
Labels: bug, awaiting review

#2936 Move AutoStructured to a separate file
  pyro/infer/autoguide/__init__.py
  pyro/infer/autoguide/guides.py
  pyro/infer/autoguide/structured.py
  pyro/infer/autoguide/utils.py
  pyro/infer/reparam/structured.py
Labels: awaiting review, easy, refactor
