Repository pyro-ppl/pyro, pull requests merged in 2021-08, with the labels that each got.

#2910 Fix bug in LRScheduler checkpointing
  .gitignore
  pyro/optim/optim.py
  tests/common.py
  tests/optim/test_optim.py
Labels: bug, awaiting review

#2914 Add ParamStoreDict.scope() method
  .github/workflows/ci.yml
  pyro/params/param_store.py
  tests/params/test_param.py
Labels: discussion, usability, awaiting review

#2917 Clarify error message on model-side sequential enumeration
  pyro/util.py
  tests/infer/test_enum.py
  tests/infer/test_valid_models.py
Labels: usability, awaiting review, warnings & errors

#2921 add link to tensor shapes tutorial
  tutorial/source/tensor_shapes.ipynb
Labels: documentation, awaiting review, easy
