Repository pyro-ppl/pyro, pull requests merged in 2021-07, with the labels that each got.

#2887 Update to PyTorch 1.9.0
  .github/workflows/ci.yml
  docs/source/conf.py
  pyro/contrib/examples/util.py
  pyro/contrib/gp/models/gpr.py
  pyro/contrib/gp/models/sgpr.py
  pyro/contrib/gp/models/vgp.py
  pyro/contrib/gp/models/vsgp.py
  pyro/contrib/gp/util.py
  pyro/contrib/oed/glmm/guides.py
  pyro/contrib/tracking/extended_kalman_filter.py
  pyro/distributions/spanning_tree.py
  pyro/distributions/torch_patch.py
  pyro/distributions/transforms/cholesky.py
  pyro/distributions/transforms/generalized_channel_permute.py
  pyro/infer/autoguide/guides.py
  pyro/infer/mcmc/adaptation.py
  pyro/infer/util.py
  pyro/ops/arrowhead.py
  pyro/ops/gamma_gaussian.py
  pyro/ops/tensor_utils.py
  setup.cfg
  setup.py
  tests/contrib/funsor/test_vectorized_markov.py
  tests/contrib/gp/test_conditional.py
  tests/contrib/randomvariable/test_random_variable.py
  tests/contrib/tracking/test_dynamic_models.py
  tests/distributions/test_hmm.py
  tests/distributions/test_mvt.py
  tests/distributions/test_ordered_logistic.py
  tests/distributions/test_torch_patch.py
  tests/distributions/test_transforms.py
  tests/infer/mcmc/test_hmc.py
  tests/infer/reparam/test_structured.py
  tests/infer/test_autoguide.py
  tests/ops/test_arrowhead.py
  tests/ops/test_gamma_gaussian.py
  tests/ops/test_gaussian.py
  tests/ops/test_ssm_gp.py
  tests/ops/test_tensor_utils.py
  tests/perf/test_benchmark.py
Labels: awaiting review, high priority

#2892 Update enumeration tutorial
  tutorial/source/enumeration.ipynb
  tutorial/source/tensor_shapes.ipynb
Labels: Examples, awaiting review

#2894 Add analytic single-sample test for ELBO gradient estimators
  tests/infer/test_gradient.py
Labels: question, testing

#2895 Add Logistic distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/logistic.py
  tests/distributions/conftest.py
Labels: awaiting review, enhancement

#2896 Implement AutoGuideList.quantiles()
  pyro/infer/autoguide/guides.py
  tests/infer/test_autoguide.py
Labels: awaiting review, easy

#2904 Implement PositivePowerTransform
  docs/source/conf.py
  docs/source/distributions.rst
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/power.py
  tests/distributions/test_transforms.py
Labels: awaiting review, enhancement

#2906 Cleanup coveralls in CI based on latest documentation
  .github/workflows/ci.yml
Labels: awaiting review

#2898 Sampling functions for the MuE/missing data discrete HMM.
  examples/contrib/mue/FactorMuE.py
  examples/contrib/mue/ProfileHMM.py
  pyro/contrib/mue/dataloaders.py
  pyro/contrib/mue/missingdatahmm.py
  pyro/contrib/mue/models.py
  tests/contrib/mue/test_dataloaders.py
  tests/contrib/mue/test_missingdatahmm.py
  tests/contrib/mue/test_statearrangers.py
Labels: awaiting review
