Repository pyro-ppl/pyro, pull requests merged in 2021-04, with the labels that each got.

#2791 Add a SoftLaplace distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/multivariate_studentt.py
  pyro/distributions/softlaplace.py
  tests/distributions/conftest.py
  tests/distributions/test_distributions.py
Labels: awaiting review, enhancement

#2793 Allow saving of a subset of variables in MCMC
  pyro/infer/mcmc/api.py
  tests/infer/mcmc/test_mcmc_api.py
Labels: awaiting review, enhancement

#2800 Add SoftLaplace.mean, .variance properties
  pyro/distributions/softlaplace.py
  tests/distributions/test_distributions.py
Labels: awaiting review

#2802 Implement sparse Poisson.log_prob() computation
  pyro/distributions/torch.py
  tests/distributions/conftest.py
Labels: awaiting review

#2814 Simplify param names in callable optim configs
  examples/air/main.py
  pyro/nn/module.py
  pyro/optim/optim.py
  pyro/params/param_store.py
  tests/infer/test_inference.py
  tests/integration_tests/test_tracegraph_elbo.py
  tests/optim/test_optim.py
  tutorial/source/svi_part_i.ipynb
  tutorial/source/svi_part_iii.ipynb
Labels: awaiting review, bug, usability

#2818 Condition on tensor instead of scalar in Intro part ii tutorial
  tutorial/source/intro_part_ii.ipynb
Labels: awaiting review

#2822 hmm example with vectorized time dimension
  examples/contrib/funsor/hmm.py
  pyro/contrib/funsor/infer/__init__.py
  pyro/contrib/funsor/infer/traceenum_elbo.py
Labels: Examples, awaiting review

#2812 Add an AutoStructured guide and StructuredReparam
  docs/source/infer.autoguide.rst
  docs/source/infer.reparam.rst
  pyro/infer/autoguide/__init__.py
  pyro/infer/autoguide/guides.py
  pyro/infer/reparam/__init__.py
  pyro/infer/reparam/structured.py
  tests/infer/reparam/test_structured.py
  tests/infer/test_autoguide.py
Labels: awaiting review, enhancement

#2823 Switch to softplus transforms for autoguide scales
  pyro/infer/autoguide/guides.py
Labels: awaiting review, easy

#2828 Fix infer.csis to ignore gradient when parameter not used, which has a gradient of None
  pyro/infer/csis.py
Labels: awaiting review, bug

#2829 Fix AutoStructured guide
  pyro/infer/autoguide/guides.py
  pyro/primitives.py
  tests/infer/reparam/test_structured.py
  tests/infer/test_autoguide.py
Labels: awaiting review, bug
