Repository pyro-ppl/pyro, pull requests merged in 2021-06, with the labels that each got.

#2853 Type Hints for Optim module and Setup MyPy as part of CI
  .gitignore
  .travis.yml
  pyro/__init__.py
  pyro/optim/adagrad_rmsprop.py
  pyro/optim/clipped_adam.py
  pyro/optim/dct_adam.py
  pyro/optim/horovod.py
  pyro/optim/lr_scheduler.py
  pyro/optim/multi.py
  pyro/optim/optim.py
  setup.cfg
Labels: usability

#2858 Incorporate mypy into lint stage
  .travis.yml
  Makefile
  examples/__init__.py
  examples/contrib/__init__.py
  examples/contrib/funsor/__init__.py
  examples/cvae/__init__.py
  examples/scanvi/__init__.py
  setup.cfg
  setup.py
Labels: awaiting review, discussion

#2826 Sine Skewed Toridial distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/sine_skewed.py
  tests/distributions/conftest.py
  tests/distributions/test_distributions.py
  tests/distributions/test_sine_skewed.py
Labels: awaiting review, enhancement

#2856 Implement pyro.ops.streaming module
  docs/source/ops.rst
  pyro/ops/streaming.py
  setup.cfg
  tests/common.py
  tests/ops/test_streaming.py
Labels: awaiting review, enhancement

#2864 Updated docstring with DS name for `SineBivariateVonMises`.
  pyro/distributions/sine_bivariate_von_mises.py
Labels: awaiting review, easy

#2863 Fix LocScaleReparam(centered=1.0)
  pyro/infer/reparam/loc_scale.py
  tests/infer/reparam/test_loc_scale.py
Labels: awaiting review, bug, easy

#2531 Test github actions for CI
  .github/workflows/ci.yml
  .travis.yml
  README.md
  pyro/distributions/sine_skewed.py
  tests/contrib/test_minipyro.py
  tests/distributions/test_sine_skewed.py
Labels: awaiting review, high priority

#2866 Enable LocScaleReparam for AsymmetricLaplace distribution
  pyro/distributions/asymmetriclaplace.py
  pyro/infer/reparam/loc_scale.py
  tests/distributions/conftest.py
  tests/infer/reparam/test_loc_scale.py
Labels: awaiting review

#2871 Fix AutoNormal.quantiles
  .github/workflows/ci.yml
  pyro/infer/autoguide/guides.py
  tests/infer/test_autoguide.py
Labels: awaiting review

#2872 Implement a SoftAsymmetricLaplace distribution
  .github/workflows/ci.yml
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/asymmetriclaplace.py
  tests/distributions/conftest.py
Labels: awaiting review

#2857 StreamingMCMC class
  docs/source/pyro.infer.mcmc.txt
  pyro/infer/mcmc/__init__.py
  pyro/infer/mcmc/api.py
  pyro/infer/mcmc/util.py
  tests/infer/mcmc/test_mcmc_api.py
Labels: awaiting review, enhancement

#2852 Predictive and Deterministic tutorial
  tutorial/source/index.rst
  tutorial/source/predictive_deterministic.ipynb
Labels: Examples, awaiting review

#2874 Implement a SkewLogistic distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/logistic.py
  tests/distributions/conftest.py
Labels: awaiting review, low priority

#2879 Implementation of rhat for StreamingMCMC
  pyro/infer/mcmc/api.py
  pyro/infer/mcmc/util.py
  tests/infer/mcmc/test_mcmc_api.py
Labels: awaiting review, discussion

#2881 Fix not executed testing code
  tests/infer/test_autoguide.py
Labels: awaiting review, easy

#2876 Make ReparamMessenger aware of InitMessenger, simplifying initialization
  pyro/contrib/epidemiology/compartmental.py
  pyro/infer/autoguide/initialization.py
  pyro/infer/reparam/conjugate.py
  pyro/infer/reparam/hmm.py
  pyro/infer/reparam/loc_scale.py
  pyro/infer/reparam/neutra.py
  pyro/infer/reparam/projected_normal.py
  pyro/infer/reparam/reparam.py
  pyro/infer/reparam/softmax.py
  pyro/infer/reparam/split.py
  pyro/infer/reparam/stable.py
  pyro/infer/reparam/structured.py
  pyro/infer/reparam/studentt.py
  pyro/infer/reparam/transform.py
  pyro/infer/reparam/unit_jacobian.py
  pyro/poutine/reparam_messenger.py
  pyro/primitives.py
  tests/infer/reparam/test_conjugate.py
  tests/infer/reparam/test_discrete_cosine.py
  tests/infer/reparam/test_haar.py
  tests/infer/reparam/test_hmm.py
  tests/infer/reparam/test_loc_scale.py
  tests/infer/reparam/test_neutra.py
  tests/infer/reparam/test_projected_normal.py
  tests/infer/reparam/test_softmax.py
  tests/infer/reparam/test_split.py
  tests/infer/reparam/test_stable.py
  tests/infer/reparam/test_structured.py
  tests/infer/reparam/test_studentt.py
  tests/infer/reparam/test_transform.py
  tests/infer/reparam/test_unit_jacobian.py
  tests/infer/reparam/util.py
Labels: awaiting review, enhancement, usability
