Repository pyro-ppl/pyro, pull requests merged in 2021-03, with the labels that each got.

#2775 Fix MNIST url redirection
  .travis.yml
  README.md
  docs/source/conf.py
  examples/cvae/mnist.py
  examples/vae/utils/mnist_cached.py
  pyro/contrib/examples/util.py
  setup.py
Labels: high priority

#2774 Revert to old default scale constraint in autoguides
  pyro/infer/autoguide/guides.py
Labels: awaiting review, discussion, high priority

#2776 Use torch==1.8.0 and torchvision==0.9.0
  .travis.yml
  README.md
  docs/source/conf.py
Labels: awaiting review, high priority

#2778 [docs] added note about graphviz in docs readme
  docs/README.md
Labels: awaiting review

#2779 Note make format and make lint in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: awaiting review, documentation

#2725 Fix expectation computations in TraceEnum_ELBO by using adjoints to calculate marginals
  pyro/contrib/funsor/infer/traceenum_elbo.py
  pyro/contrib/funsor/infer/tracetmc_elbo.py
  setup.py
  tests/contrib/funsor/test_enum_funsor.py
Labels: awaiting review

#2784 Use pyro.contrib.examples.util.MNIST in tutorials
  tutorial/source/vae.ipynb
Labels: awaiting review, easy, high priority

#2770 add svi part iv tutorial
  tutorial/source/index.rst
  tutorial/source/svi_part_iv.ipynb
Labels: awaiting review, documentation

#2785 Fix links in SVI part IV tutorial
  tutorial/source/conf.py
  tutorial/source/svi_part_iv.ipynb
Labels: awaiting review, easy

#2782 Catch nan values in TraceEnum_ELBO grads
  tests/contrib/funsor/test_enum_funsor.py
Labels: awaiting review, enhancement

#2728 MuE distributions for Pyro.
  .gitignore
  docs/source/contrib.mue.rst
  docs/source/index.rst
  examples/contrib/mue/FactorMuE.py
  examples/contrib/mue/ProfileHMM.py
  pyro/contrib/mue/__init__.py
  pyro/contrib/mue/dataloaders.py
  pyro/contrib/mue/missingdatahmm.py
  pyro/contrib/mue/models.py
  pyro/contrib/mue/statearrangers.py
  tests/contrib/mue/test_dataloaders.py
  tests/contrib/mue/test_missingdatahmm.py
  tests/contrib/mue/test_models.py
  tests/contrib/mue/test_statearrangers.py
  tests/test_examples.py
  tutorial/source/index.rst
  tutorial/source/mue_factor.rst
  tutorial/source/mue_profile.rst
Labels: awaiting review

#2786 Fix regression in unfold/Approximate pattern in funsor#488
  pyro/contrib/funsor/infer/traceenum_elbo.py
  pyro/contrib/funsor/infer/tracetmc_elbo.py
Labels: awaiting review, bug

#2788 Bump funsor version to include Approximate
  setup.py
Labels: awaiting review, easy

#2781 Funsor-based infer_discrete for (max, add) semiring
  pyro/contrib/funsor/handlers/replay_messenger.py
  pyro/contrib/funsor/infer/__init__.py
  pyro/contrib/funsor/infer/discrete.py
  tests/contrib/funsor/test_infer_discrete.py
Labels: awaiting review

#2789 Add a sample option to pyro.contrib.funsor.infer_discrete
  pyro/contrib/funsor/infer/discrete.py
  tests/contrib/funsor/test_infer_discrete.py
Labels: awaiting review, enhancement

#2790 Enhance LDA tutorial
  tutorial/source/prodlda.ipynb
Labels: awaiting review
