Repository pyro-ppl/pyro, pull requests merged in 2021-01, with the labels that each got.

#2727 Add SpanningTree properties .mode, .edge_mean
  pyro/distributions/spanning_tree.cpp
  pyro/distributions/spanning_tree.py
  tests/distributions/test_spanning_tree.py
Labels: awaiting review

#2730 Fix Sphinx build for MLE tutorial
  tutorial/source/mle_map.ipynb
Labels: Examples, awaiting review, bug, easy

#2732 Prefer pyro.plate over plate in docs
  pyro/primitives.py
  pyro/util.py
  tests/infer/test_autoguide.py
  tutorial/source/ss-vae.ipynb
  tutorial/source/svi_part_ii.ipynb
Labels: awaiting review, documentation

#2731 Support more batch distributions in HaarReparam
  pyro/contrib/forecast/util.py
  pyro/infer/reparam/discrete_cosine.py
  pyro/infer/reparam/haar.py
  pyro/infer/reparam/unit_jacobian.py
  pyro/ops/tensor_utils.py
  pyro/poutine/plate_messenger.py
  tests/contrib/forecast/test_util.py
Labels: awaiting review

#2733 Reduce log verbosity in CEVAE
  pyro/contrib/cevae/__init__.py
Labels: awaiting review, easy

#2726 Make replay work correctly with vectorized_markov
  pyro/contrib/funsor/handlers/plate_messenger.py
  pyro/contrib/funsor/handlers/trace_messenger.py
  pyro/contrib/funsor/infer/traceenum_elbo.py
  tests/contrib/funsor/test_vectorized_markov.py
Labels: awaiting review, bug

#2734 Fix measure_vars for guide enumerated models
  pyro/contrib/funsor/infer/traceenum_elbo.py
  tests/contrib/funsor/test_vectorized_markov.py
Labels: awaiting response

#2735 AffineBeta distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/affine_beta.py
  tests/distributions/conftest.py
Labels: awaiting response

#2738 Add goodness of fit test helpers for testing distributions
  docs/source/index.rst
  docs/source/testing.rst
  pyro/distributions/affine_beta.py
  pyro/distributions/testing/__init__.py
  pyro/distributions/testing/gof.py
  pyro/distributions/testing/special.py
  tests/common.py
  tests/distributions/conftest.py
  tests/distributions/test_distributions.py
  tests/distributions/test_von_mises.py
  tests/distributions/testing/test_special.py
Labels: awaiting review, testing

#2736 Implement ProjectedNormal distribution and reparametrizer
  docs/source/distributions.rst
  docs/source/infer.reparam.rst
  pyro/distributions/__init__.py
  pyro/distributions/constraints.py
  pyro/distributions/projected_normal.py
  pyro/distributions/von_mises_3d.py
  pyro/infer/autoguide/guides.py
  pyro/infer/autoguide/initialization.py
  pyro/infer/autoguide/utils.py
  pyro/infer/reparam/__init__.py
  pyro/infer/reparam/projected_normal.py
  tests/common.py
  tests/distributions/conftest.py
  tests/distributions/test_constraints.py
  tests/distributions/test_distributions.py
  tests/infer/reparam/test_projected_normal.py
  tests/infer/test_autoguide.py
Labels: awaiting review

#2743 Detach AutoGuide.median() and .quantiles()
  pyro/infer/autoguide/guides.py
  tests/infer/test_autoguide.py
  tutorial/source/stable.ipynb
Labels: awaiting review, usability

#2746 Make TransformReparam compatible with .to_event()
  pyro/infer/reparam/transform.py
  tests/infer/reparam/test_transform.py
Labels: awaiting review, bug

#2749 Support constraints.sphere in AutoDelta
  docs/source/distributions.rst
  pyro/distributions/projected_normal.py
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/normalize.py
  pyro/infer/reparam/projected_normal.py
  pyro/ops/tensor_utils.py
  tests/distributions/test_constraints.py
  tests/distributions/test_transforms.py
  tests/infer/test_autoguide.py
Labels: awaiting review, enhancement

#2748 Expose ExpandedDistribution in pyro.distributions
  pyro/distributions/__init__.py
Labels: awaiting review, easy

#2752 Expose contrib.funsor inference algorithms in docs
  docs/source/contrib.funsor.rst
Labels: awaiting review, easy
