Repository pyro-ppl/pyro, pull requests merged in 2021-11, with the labels that each got.

#2953 Implement GuideMessenger, AutoNormalMessenger, AutoRegressiveMessenger
  docs/source/infer.autoguide.rst
  docs/source/pyro.poutine.txt
  pyro/infer/autoguide/__init__.py
  pyro/infer/autoguide/effect.py
  pyro/infer/elbo.py
  pyro/infer/enum.py
  pyro/infer/traceenum_elbo.py
  pyro/poutine/__init__.py
  pyro/poutine/guide.py
  pyro/poutine/messenger.py
  tests/infer/test_autoguide.py
Labels: enhancement, awaiting review

#2958 Fix docs build and clean up docs/requirements.txt
  docs/requirements.txt
  tests/contrib/oed/test_finite_spaces_eig.py
  tests/infer/test_enum.py
Labels: documentation, awaiting review, easy

#2960 Work around setuptools breakage
  .github/workflows/ci.yml
Labels: high priority, awaiting review

#2961 Updated doc_string for `SineBivariateVonMises`.
  pyro/distributions/sine_bivariate_von_mises.py
Labels: awaiting review, easy

#2955 Implement AutoHierarchicalNormalMessenger
  docs/source/infer.autoguide.rst
  pyro/infer/autoguide/__init__.py
  pyro/infer/autoguide/effect.py
  tests/infer/test_autoguide.py
Labels: enhancement, awaiting response

#2959 Support discrete variables in get_dependencies() via ProvenanceTensor
  pyro/infer/inspect.py
  pyro/ops/provenance.py
  tests/infer/test_inspect.py
Labels: enhancement, awaiting review

#2962 Port numpyro.render_model() to Pyro
  .github/workflows/ci.yml
  .gitignore
  docs/source/conf.py
  docs/source/inference_algos.rst
  pyro/__init__.py
  pyro/infer/inspect.py
  pyro/util.py
  tutorial/source/index.rst
  tutorial/source/intro_part_i.ipynb
  tutorial/source/model_rendering.ipynb
Labels: enhancement, usability, awaiting review

#2964 Fix provenance of kwargs
  pyro/ops/provenance.py
Labels: bug, awaiting review

#2963 Change coordinatization of AutoMultivariateNormal
  pyro/infer/autoguide/guides.py
  tests/infer/autoguide/test_inference.py
  tests/infer/autoguide/test_mean_field_entropy.py
  tests/infer/reparam/test_neutra.py
Labels: enhancement, awaiting review

#2972 add UnitLowerCholeskyTransform; change default parameterization for AutoMultivariateNormal
  docs/source/distributions.rst
  pyro/distributions/constraints.py
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/unit_cholesky.py
  pyro/infer/autoguide/guides.py
  tests/distributions/test_transforms.py
Labels: awaiting review, easy
