Repository pyro-ppl/pyro, pull requests merged in 2021-05, with the labels that each got.

#2830 Clarify documentation of pyro.primitives
  docs/source/primitives.rst
  pyro/poutine/lift_messenger.py
  pyro/primitives.py
Labels: awaiting review, documentation, easy

#2838 Fix docs issue for sphinx-4
  docs/source/conf.py
Labels: awaiting review, easy, high priority

#2841 Remove overly-narrow validation check from AutoStructured
  pyro/infer/autoguide/guides.py
Labels: awaiting review, easy

#2840 Fix math expressions for latex pdf docs.
  pyro/contrib/timeseries/gp.py
  tutorial/source/normalizing_flows_i.ipynb
  tutorial/source/ss-vae.ipynb
  tutorial/source/vae.ipynb
Labels: awaiting review, bug

#2846 Fix pyro.poutine.do to avoid duplicate entries in cond_indep_stack
  pyro/poutine/do_messenger.py
  tests/poutine/test_counterfactual.py
Labels: awaiting review, bug, easy

#2821 Bivariate von Mises Distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/sine_bivariate_von_mises.py
  pyro/ops/special.py
  tests/distributions/conftest.py
  tests/distributions/test_distributions.py
  tests/distributions/test_sine_bivariate_von_mises.py
  tests/ops/test_special.py
Labels: awaiting review, enhancement

#2850 Implement AsymmetricLaplace distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/asymmetriclaplace.py
  tests/distributions/conftest.py
Labels: awaiting review
