Repository pyro-ppl/pyro, pull requests merged in 2021-02, with the labels that each got.

#2757 Upgrade to PyTorch 1.7
  .travis.yml
  docs/source/conf.py
  pyro/distributions/constraints.py
  pyro/ops/fft.py
  pyro/ops/stats.py
  pyro/ops/tensor_utils.py
  setup.py
  tests/distributions/test_util.py
  tests/test_examples.py
Labels: awaiting review

#2759 Fix Delta.arg_constraints and .support
  pyro/distributions/constraints.py
  pyro/distributions/delta.py
Labels: awaiting review, easy

#2762 Docs: Add reference for effect handlers
  docs/source/poutine.rst
Labels: documentation

#2760 Add positive_ordered_vector and corr_matrix constraints
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/constraints.py
  pyro/distributions/lkj.py
  pyro/distributions/torch_patch.py
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/cholesky.py
  tests/distributions/conftest.py
  tests/distributions/test_constraints.py
  tests/distributions/test_distributions.py
  tests/distributions/test_transforms.py
Labels: awaiting review

#2751 Implement poutine.get_mask() and use it to optimize NeuTra etc
  pyro/contrib/funsor/handlers/trace_messenger.py
  pyro/distributions/util.py
  pyro/infer/autoguide/guides.py
  pyro/infer/predictive.py
  pyro/infer/reparam/conjugate.py
  pyro/infer/reparam/neutra.py
  pyro/infer/reparam/split.py
  pyro/ops/packed.py
  pyro/poutine/__init__.py
  pyro/poutine/mask_messenger.py
  pyro/poutine/runtime.py
  tests/infer/test_predictive.py
Labels: awaiting review

#2764 Fix bitwise & for bool and Tensor in MaskMessenger
  pyro/poutine/mask_messenger.py
Labels: awaiting review, bug

#2745 Autoname messenger
  pyro/contrib/autoname/__init__.py
  pyro/contrib/autoname/autoname.py
  tests/contrib/autoname/test_autoname.py
Labels: awaiting review

#2753 Update dev branch to use PyTorch 1.8 prerelease
  .gitignore
  .travis.yml
  README.md
  docs/source/conf.py
  pyro/contrib/gp/parameterized.py
  pyro/distributions/affine_beta.py
  pyro/distributions/conjugate.py
  pyro/distributions/constraints.py
  pyro/distributions/hmm.py
  pyro/distributions/kl.py
  pyro/distributions/lkj.py
  pyro/distributions/testing/rejection_exponential.py
  pyro/distributions/torch.py
  pyro/distributions/torch_distribution.py
  pyro/distributions/torch_patch.py
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/affine_autoregressive.py
  pyro/distributions/transforms/affine_coupling.py
  pyro/distributions/transforms/basic.py
  pyro/distributions/transforms/batchnorm.py
  pyro/distributions/transforms/block_autoregressive.py
  pyro/distributions/transforms/cholesky.py
  pyro/distributions/transforms/discrete_cosine.py
  pyro/distributions/transforms/generalized_channel_permute.py
  pyro/distributions/transforms/haar.py
  pyro/distributions/transforms/householder.py
  pyro/distributions/transforms/lower_cholesky_affine.py
  pyro/distributions/transforms/matrix_exponential.py
  pyro/distributions/transforms/neural_autoregressive.py
  pyro/distributions/transforms/normalize.py
  pyro/distributions/transforms/ordered.py
  pyro/distributions/transforms/permute.py
  pyro/distributions/transforms/planar.py
  pyro/distributions/transforms/polynomial.py
  pyro/distributions/transforms/radial.py
  pyro/distributions/transforms/spline.py
  pyro/distributions/transforms/spline_autoregressive.py
  pyro/distributions/transforms/spline_coupling.py
  pyro/distributions/transforms/sylvester.py
  pyro/distributions/zero_inflated.py
  pyro/infer/autoguide/utils.py
  setup.cfg
  setup.py
  tests/contrib/epidemiology/test_models.py
  tests/distributions/conftest.py
  tests/distributions/dist_fixture.py
  tests/distributions/test_distributions.py
  tests/distributions/test_hmm.py
  tests/distributions/test_lkj.py
  tests/distributions/test_transforms.py
  tests/infer/test_gradient.py
  tests/infer/test_valid_models.py
  tests/test_examples.py
Labels: awaiting review

#2739 Add a Distribution.infer_shapes() method to statically infer shapes
  .gitignore
  pyro/distributions/affine_beta.py
  pyro/distributions/conjugate.py
  pyro/distributions/multivariate_studentt.py
  pyro/distributions/projected_normal.py
  pyro/distributions/torch.py
  pyro/distributions/torch_distribution.py
  tests/distributions/test_distributions.py
Labels: awaiting review, enhancement

#2771 Deprecate LKJCorrCholesky distribution
  examples/contrib/forecast/bart.py
  examples/lkj.py
  pyro/distributions/lkj.py
  tests/distributions/conftest.py
  tests/distributions/test_distributions.py
  tests/distributions/test_lkj.py
  tests/infer/test_autoguide.py
Labels: awaiting review

#2772 Support obs_mask kwarg in sample statements
  pyro/primitives.py
  tests/infer/mcmc/test_valid_models.py
  tests/infer/test_valid_models.py
Labels: awaiting review, discussion, enhancement

#2767 Stabilize autoguide scale parameters via SoftplusTransform
  docs/source/distributions.rst
  pyro/distributions/constraints.py
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/softplus.py
  pyro/infer/autoguide/guides.py
  tests/contrib/autoguide/test_inference.py
  tests/distributions/test_transforms.py
  tests/infer/test_autoguide.py
Labels: awaiting review
