Repository pyro-ppl/pyro, pull requests merged in 2022-12, with the labels that each got.

#3159 Allow rendering of semisupervised models
  pyro/infer/inspect.py
  tests/infer/test_inspect.py
  tutorial/source/model_rendering.ipynb
Labels: enhancement, awaiting review

#3164 Allow torch>=2
  pyro/distributions/torch_patch.py
Labels: awaiting review, easy

#3163 add GroupedNormalNormal distribution
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/grouped_normal_normal.py
  tests/distributions/test_grouped_normal_normal.py
Labels: awaiting review

#3012 Add make tutorial to docs CI workflow
  .github/workflows/ci.yml
Labels: documentation, awaiting review, testing
