Repository pyro-ppl/pyro, pull requests merged in 2022-01, with the labels that each got.

#3004 Clarified comments in `minipyro.py` to fix #3003
  pyro/contrib/minipyro.py
Labels: awaiting review

#3009 Add missing docs for ProjectedNormal parameter
  pyro/distributions/projected_normal.py
Labels: documentation, awaiting review, easy

#3011 Support 4D ProjectedNormal distribution
  pyro/distributions/projected_normal.py
  tests/distributions/conftest.py
Labels: awaiting review

#3010 add log normal negative binomial distributions
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/log_normal_negative_binomial.py
  pyro/ops/special.py
  tests/distributions/conftest.py
  tests/distributions/test_distributions.py
  tests/distributions/test_log_normal_negative_binomial.py
  tests/ops/test_special.py
Labels: enhancement, awaiting review
