Repository pyro-ppl/pyro, pull requests merged in 2022-07, with the labels that each got.

#3111 Expose docs for pyro.contrib.funsor.infer.infer_discrete
  docs/source/contrib.funsor.rst
Labels: documentation, awaiting review, easy

#3113 Allow autocorrelation() to run without MKL
  pyro/ops/stats.py
Labels: awaiting review, easy

#3115 Fix multinomial_goodness_of_fit printing
  pyro/distributions/testing/gof.py
  tests/distributions/testing/test_gof.py
Labels: awaiting review, easy

#3114 Numerically stabilize autocorrelation()
  pyro/ops/stats.py
  tests/ops/test_stats.py
Labels: awaiting review, easy

#3116 Implement NanMaskedNormal, NanMaskedMultivariateNormal
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/nanmasked.py
  tests/distributions/test_nanmasked.py
Labels: enhancement, awaiting review

#3119 Fix links in workflow tutorial
  tutorial/source/workflow.ipynb
Labels: Examples, awaiting review, easy

#3118 Implement Resamper for interactive prior tuning
  docs/source/conf.py
  docs/source/infer.util.rst
  pyro/infer/resampler.py
  tests/infer/test_resampler.py
  tutorial/source/conf.py
  tutorial/source/index.rst
  tutorial/source/prior_predictive.ipynb
Labels: enhancement, awaiting review

#3120 fix entropy term in distributions.py (wrong isinstance check)
  pyro/distributions/torch_distribution.py
Labels: awaiting review, easy
