Repository pyro-ppl/pyro, pull requests merged in 2022-05, with the labels that each got.

#3071 Numerically stabilize ProjectedNormal.log_prob() via erfc
  pyro/distributions/projected_normal.py
  pyro/ops/special.py
  tests/common.py
  tests/distributions/conftest.py
  tests/distributions/test_distributions.py
  tests/distributions/test_projected_normal.py
Labels: awaiting review

#3077 fix Nystrom approximation equation indices
  pyro/contrib/gp/models/sgpr.py
Labels: documentation, awaiting review

#3078 remove extraneous svi step call in documentation
  pyro/contrib/gp/models/model.py
Labels: documentation, awaiting review

#3083 Add type assertion for `model_args` and `model_kwargs` of `render_model`
  pyro/infer/inspect.py
Labels: awaiting review

#3086 Remove `batch_expand` helper function in air example
  examples/air/air.py
Labels: awaiting review

#3087 Fix a typo in air tutorial
  tutorial/source/air.ipynb
Labels: awaiting review

#3084 Fix Nyström Typo
  pyro/contrib/gp/models/sgpr.py
Labels: documentation, awaiting review

#3081 Use provenance tracking to compute downstream costs in `TraceGraph_ELBO`
  examples/air/main.py
  pyro/infer/tracegraph_elbo.py
  pyro/ops/provenance.py
  tests/infer/test_compute_downstream_costs.py
Labels: awaiting review, refactor
