Repository pyro-ppl/pyro, pull requests merged in 2022-03, with the labels that each got.

#2977 Tutorial on Bayesian workflow, with a SARS-CoV-2 running example
  pyro/ops/special.py
  tutorial/source/index.rst
  tutorial/source/logistic-growth.ipynb
  tutorial/source/workflow.ipynb
Labels: Examples, awaiting review

#3027 Improvements to GP documentation
  tutorial/source/_static/img/gpr-fit.gif
  tutorial/source/_static/img/svgpr-fit.gif
  tutorial/source/gp.ipynb
Labels: Examples, awaiting review

#3036 Added type assertion for better code clarity
  pyro/contrib/gp/models/gpr.py
  pyro/contrib/gp/models/model.py
  pyro/contrib/gp/models/sgpr.py
  pyro/contrib/gp/models/vgp.py
  pyro/contrib/gp/models/vsgp.py
Labels: awaiting review, warnings & errors

#3039 improved `render_model`
  pyro/infer/inspect.py
  pyro/nn/module.py
  tests/infer/enum_growth.ipynb
  tutorial/source/intro_long.ipynb
  tutorial/source/mle_map.ipynb
  tutorial/source/model_rendering.ipynb
Labels: enhancement, awaiting review

#3038 add GitHub URL for PyPi
  setup.py
Labels: awaiting review

#3045 Update to PyTorch 1.11.0
  .github/workflows/ci.yml
  .readthedocs.yml
  Makefile
  docs/source/conf.py
  examples/baseball.py
  pyro/contrib/gp/models/sgpr.py
  pyro/contrib/gp/util.py
  pyro/distributions/multivariate_studentt.py
  pyro/distributions/omt_mvn.py
  pyro/distributions/transforms/generalized_channel_permute.py
  pyro/distributions/transforms/lower_cholesky_affine.py
  pyro/infer/autoguide/gaussian.py
  pyro/infer/mcmc/adaptation.py
  pyro/ops/arrowhead.py
  pyro/ops/gamma_gaussian.py
  pyro/ops/integrator.py
  pyro/ops/linalg.py
  pyro/ops/provenance.py
  pyro/ops/tensor_utils.py
  pyro/poutine/collapse_messenger.py
  setup.cfg
  setup.py
  tests/contrib/funsor/test_enum_funsor.py
  tests/infer/enum_growth.ipynb
  tests/infer/test_jit.py
  tests/ops/test_gaussian.py
  tests/ops/test_linalg.py
  tests/poutine/test_poutines.py
  tests/test_examples.py
  tutorial/source/gp.ipynb
Labels: awaiting review

#3047 Drop more references to Python 3.6
  README.md
  setup.cfg
  setup.py
  tests/distributions/test_pickle.py
  tutorial/source/cleannb.py
Labels: awaiting review, easy
