Repository pyro-ppl/pyro, pull requests merged in 2022-10, with the labels that each got.

#3145 Expose Gaussian algorithms
  pyro/distributions/hmm.py
  pyro/ops/gaussian.py
  tests/distributions/test_hmm.py
  tests/ops/test_gaussian.py
Labels: awaiting review, easy

#3147 Pin visdom version to unblock CI
  setup.py
Labels: awaiting review, easy

#3140 fix_reverse_out_bound_quadratic_spline
  pyro/distributions/transforms/spline.py
Labels: awaiting review

#3146 Improve sequential_gaussian_filter_sample()
  examples/contrib/forecast/bart.py
  profiler/gaussianhmm.py
  pyro/distributions/hmm.py
  pyro/ops/gaussian.py
  tests/ops/gaussian.py
  tests/ops/test_gaussian.py
Labels: enhancement, awaiting review

#3151 Add jitter to Cholesky factorization in Gaussian ops
  pyro/distributions/hmm.py
  pyro/distributions/transforms/cholesky.py
  pyro/ops/gaussian.py
  pyro/ops/tensor_utils.py
  tests/ops/test_gaussian.py
Labels: awaiting review
