Repository pyro-ppl/pyro, pull requests merged in 2023-08, with the labels that each got.

#3253 Fix GammaPoisson distribution from ignoring validate_args param
  pyro/distributions/conjugate.py
Labels: bug

#3258 fix custom_guide in intro_long.ipynb
  tutorial/source/intro_long.ipynb
Labels: documentation

#3264 use generator arg in dataloader in cevae
  pyro/contrib/cevae/__init__.py
Labels: awaiting review, easy

#3261 SBVM sampler fix
  pyro/distributions/sine_bivariate_von_mises.py
Labels: bug
