Repository pyro-ppl/pyro, pull requests merged in 2023-06, with the labels that each got.

#3224 Create FUNDING.yml
  .github/FUNDING.yml
Labels: awaiting review

#3229 Fix jit ELBO sign error
  pyro/infer/trace_mean_field_elbo.py
  pyro/infer/tracegraph_elbo.py
  pyro/ops/provenance.py
  tests/infer/test_jit.py
Labels: bug, awaiting review

#3231 Replace flake8+isort with ruff
  .github/workflows/ci.yml
  Makefile
  pyproject.toml
  pyro/contrib/funsor/__init__.py
  pyro/distributions/constraints.py
  pyro/poutine/messenger.py
  setup.py
Labels: awaiting review, testing

#3233 fix _loc_scale method in AutoMultivariateNormal
  pyro/infer/autoguide/guides.py
  tests/infer/test_autoguide.py
Labels: awaiting response
