Repository pyro-ppl/pyro, pull requests merged in 2023-04, with the labels that each got.

#3198 Fixing typos in `infer.inspect`
  pyro/infer/inspect.py
Labels: awaiting review, easy

#3195 Bug fix about device of subsample in subsample_messenger.py
  pyro/poutine/subsample_messenger.py
Labels: bug, awaiting review

#3197 Dependency tracking tutorial
  tutorial/source/svi_part_iii.ipynb
Labels: awaiting review
