Repository pyro-ppl/pyro, pull requests merged in 2023-01, with the labels that each got.

#3168 Allow registering of custom exception handlers for potential_fn computations
  pyro/infer/mcmc/hmc.py
  pyro/ops/integrator.py
Labels: awaiting review

#3167 Update base learning rate scheduler
  pyro/optim/pytorch_optimizers.py
Labels: bug, awaiting review, easy

#3175 Update GP tutorials to unblock #3174
  tutorial/source/bo.ipynb
  tutorial/source/gp.ipynb
Labels: awaiting review, easy

#3125 add substitute handler
  docs/source/pyro.poutine.txt
  pyro/poutine/__init__.py
  pyro/poutine/handlers.py
  pyro/poutine/substitute_messenger.py
  tests/poutine/test_poutines.py
Labels: enhancement, awaiting review
