Repository pyro-ppl/pyro, pull requests merged in 2023-05, with the labels that each got.

#3204 Make patch_dependency safer under dependency drift
  pyro/distributions/torch_patch.py
  pyro/optim/pytorch_optimizers.py
Labels: awaiting review

#3199 Deprecate `CorrLCholeskyTransform` in favor of upstream `CorrCholeskyTransform`
  docs/source/distributions.rst
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/cholesky.py
  tests/distributions/test_lkj.py
  tests/distributions/test_transforms.py
Labels: awaiting review, refactor

#3205 VAE: Improved ELBO plots
  examples/vae/utils/vae_plots.py
  examples/vae/vae.py
Labels: documentation, awaiting review

#3210 Remove vestigial lines from pyro/__init__.py __all__
  pyro/__init__.py
Labels: awaiting review

#3212 Clear .unconstrained weakrefs before pickling; rebuild them more often
  pyro/contrib/easyguide/easyguide.py
  pyro/contrib/util.py
  pyro/distributions/torch_patch.py
  pyro/infer/elbo.py
  pyro/nn/module.py
  pyro/params/param_store.py
  pyro/poutine/guide.py
  tests/nn/test_module.py
Labels: awaiting review

#3217 Add `pl.Trainer` args to argparse
  examples/svi_lightning.py
Labels: awaiting review

#3192 Run CI with PyTorch 2.0
  .github/workflows/ci.yml
  examples/baseball.py
  pyro/contrib/examples/multi_mnist.py
  setup.py
  tests/contrib/cevae/test_cevae.py
  tests/contrib/test_minipyro.py
  tests/distributions/test_rejector.py
  tests/distributions/test_stable.py
  tests/infer/reparam/test_stable.py
  tutorial/source/prodlda.ipynb
Labels: testing, Blocked

#3220 make ProvenanceTensor behave more like a Tensor (closes #3218)
  pyro/ops/provenance.py
  tests/ops/test_provenance.py
Labels: bug, awaiting response

#3223 Refactor `ProvenanceTensor` to use `pytree`
  pyro/ops/provenance.py
  tests/ops/test_provenance.py
Labels: refactor
