Repository pyro-ppl/pyro, pull requests merged in 2023-10, with the labels that each got.

#3272 Drop the support for PyTorch<2.0
  CONTRIBUTING.md
  Makefile
  docs/source/conf.py
  examples/baseball.py
  examples/contrib/cevae/synthetic.py
  examples/contrib/epidemiology/regional.py
  examples/contrib/epidemiology/sir.py
  examples/contrib/funsor/hmm.py
  examples/contrib/mue/FactorMuE.py
  examples/contrib/mue/ProfileHMM.py
  examples/einsum.py
  examples/hmm.py
  examples/sir_hmc.py
  examples/sparse_gamma_def.py
  examples/sparse_regression.py
  examples/svi_horovod.py
  examples/svi_lightning.py
  profiler/gaussianhmm.py
  pyro/contrib/gp/parameterized.py
  pyro/infer/mcmc/api.py
  pyro/ops/provenance.py
  pyro/optim/pytorch_optimizers.py
  setup.py
  tests/common.py
  tests/conftest.py
  tests/contrib/timeseries/test_gp.py
  tests/contrib/timeseries/test_lgssm.py
  tests/distributions/test_cuda.py
  tests/infer/autoguide/test_gaussian.py
  tests/test_examples.py
  tutorial/source/logistic-growth.ipynb
Labels: breaking

#3271 Add `param_store.py` type hints
  pyro/params/param_store.py
  setup.cfg
Labels: awaiting review

#3278 Drop Python 3.7 support
  .readthedocs.yml
  setup.cfg
  setup.py
Labels: breaking

#3281 Update link to Nolan reference of Stable distribution
  pyro/distributions/stable.py
  pyro/infer/reparam/stable.py
Labels: awaiting review, easy

#3283 Fix `pyro.poutine.handlers`
  pyro/poutine/handlers.py
Labels: bug

#3285 Add handlers explicitly
  pyro/contrib/autoname/autoname.py
  pyro/contrib/funsor/handlers/__init__.py
  pyro/poutine/handlers.py
Labels: usability, awaiting review

#3287 Use `functools.wraps` to preserve `handler` signature
  pyro/poutine/block_messenger.py
  pyro/poutine/handlers.py
Labels: usability, awaiting review, easy
