Repository pyro-ppl/pyro, pull requests merged in 2023-07, with the labels that each got.

#3242 Revert to support `torch>=1.11.0`
  .github/workflows/ci.yml
  pyro/ops/provenance.py
  setup.py
Labels: awaiting review

#3246 Concatenate torch docstrings at end of distribution wrappers
  Makefile
  docs/source/conf.py
  pyro/contrib/forecast/forecaster.py
  pyro/distributions/torch.py
Labels: documentation, awaiting review

#3250 Disable pdf builds on readthedocs
  docs/source/conf.py
Labels: awaiting review

#3251 Disable pdf and epub build on readthedocs
  .readthedocs.yml
  docs/source/conf.py
Labels: awaiting review

#3247 Fix #3245 bug in poutine.trace(graph_type="dense")
  pyro/poutine/trace_messenger.py
  tests/integration_tests/test_tracegraph_elbo.py
  tests/poutine/test_poutines.py
Labels: bug, awaiting review
