Repository pyro-ppl/pyro, pull requests merged in 2024-05, with the labels that each got.

#3363 Add jupyter lab option to docker Makefile
  docker/Makefile
Labels: enhancement, usability

#3366 Fix PyroModule rendering error in local-parameter mode
  pyro/nn/module.py
  tests/nn/test_module.py
Labels: bug, awaiting review

#3369 Add Stable distribution with numerically integrated log-probability calculation (StableWithLogProb).
  docs/source/distributions.rst
  pyro/distributions/__init__.py
  pyro/distributions/stable.py
  pyro/distributions/stable_log_prob.py
  pyro/infer/reparam/stable.py
  pyro/infer/reparam/strategies.py
  tests/distributions/test_stable_with_log_prob.py
  tutorial/source/stable.ipynb
Labels: enhancement, awaiting review
