Repository pyro-ppl/pyro, pull requests merged in 2024-02, with the labels that each got.

#3318 Get CI working with new black, torch, pytest
  examples/capture_recapture/cjs.py
  examples/contrib/funsor/hmm.py
  examples/hmm.py
  examples/mixed_hmm/experiment.py
  pyro/contrib/autoname/autoname.py
  pyro/contrib/bnn/hidden_layer.py
  pyro/contrib/cevae/__init__.py
  pyro/contrib/epidemiology/models.py
  pyro/contrib/funsor/handlers/__init__.py
  pyro/contrib/funsor/handlers/replay_messenger.py
  pyro/contrib/funsor/infer/trace_elbo.py
  pyro/contrib/funsor/infer/traceenum_elbo.py
  pyro/contrib/funsor/infer/tracetmc_elbo.py
  pyro/contrib/timeseries/lgssmgp.py
  pyro/contrib/tracking/distributions.py
  pyro/distributions/__init__.py
  pyro/distributions/asymmetriclaplace.py
  pyro/distributions/conditional.py
  pyro/distributions/conjugate.py
  pyro/distributions/constraints.py
  pyro/distributions/grouped_normal_normal.py
  pyro/distributions/hmm.py
  pyro/distributions/inverse_gamma.py
  pyro/distributions/lkj.py
  pyro/distributions/log_normal_negative_binomial.py
  pyro/distributions/one_one_matching.py
  pyro/distributions/one_two_matching.py
  pyro/distributions/sine_skewed.py
  pyro/distributions/stable.py
  pyro/distributions/torch.py
  pyro/distributions/transforms/basic.py
  pyro/distributions/transforms/block_autoregressive.py
  pyro/distributions/transforms/cholesky.py
  pyro/distributions/transforms/permute.py
  pyro/distributions/transforms/power.py
  pyro/distributions/transforms/softplus.py
  pyro/infer/autoguide/gaussian.py
  pyro/infer/rws.py
  pyro/nn/module.py
  pyro/params/param_store.py
  pyro/poutine/enum_messenger.py
  pyro/poutine/handlers.py
  pyro/poutine/runtime.py
  pyro/poutine/trace_struct.py
  pyro/primitives.py
  tests/contrib/funsor/test_tmc.py
  tests/infer/test_smcfilter.py
  tests/infer/test_tmc.py
  tests/ops/test_welford.py
  tests/perf/test_benchmark.py
Labels: awaiting review

#3321 Annotate handlers & add py.typed
  pyro/poutine/collapse_messenger.py
  pyro/poutine/handlers.py
  pyro/poutine/trace_messenger.py
  pyro/primitives.py
  pyro/py.typed
Labels: awaiting review

#3320 Port implementation of SimplexToOrderedTransform from numpyro
  docs/source/distributions.rst
  pyro/distributions/transforms/__init__.py
  pyro/distributions/transforms/simplex_to_ordered.py
  tests/distributions/test_transforms.py
Labels: awaiting review

#3317 Prevent observation masks improperly expanding samples in plates
  pyro/primitives.py
  tests/test_primitives.py
Labels: awaiting review

#3323 Document InferDict and Message typed dicts
  pyro/poutine/runtime.py
Labels: documentation, awaiting review

#3325 Fix bug in CVAE example
  examples/cvae/baseline.py
  tests/test_examples.py
Labels: awaiting response

#3327 Add a simple PyTorch training example
  examples/svi_torch.py
  tests/test_examples.py
  tutorial/source/index.rst
  tutorial/source/svi_torch.rst
Labels: Examples, awaiting review

#3326 Add .github/workflows/publish.yml to publish to pypi.org
  .github/workflows/publish.yml
Labels: awaiting review

#3328 Fix interaction between PyroParam and torch.func.grad
  pyro/nn/module.py
  tests/nn/test_module.py
Labels: bug, awaiting review

#3333 Explicitly import distributions from torch
  Makefile
  pyro/distributions/__init__.py
  pyro/distributions/constraints.py
  pyro/distributions/torch.py
  pyro/distributions/transforms/__init__.py
  setup.py
  tests/infer/test_gradient.py
Labels: documentation, awaiting review, warnings & errors

#3334 Fix typing of poutine.trace(model).get_trace()
  pyro/poutine/handlers.py
  pyro/poutine/reparam_messenger.py
  pyro/poutine/trace_messenger.py
Labels: awaiting review, warnings & errors
