Repository pyro-ppl/pyro, pull requests merged in 2024-03, with the labels that each got.

#3337 Type annotate `pyro.nn.module`
  pyro/nn/module.py
  pyro/ops/provenance.py
  pyro/params/param_store.py
  pyro/poutine/reparam_messenger.py
  pyro/poutine/runtime.py
  setup.cfg
Labels: awaiting review

#3339 Introducing PyroModuleList, because torch.nn.ModueList reinitializies modules when slice-indexing
  pyro/nn/__init__.py
  pyro/nn/module.py
  tests/nn/test_module.py
Labels: awaiting review

#3340 Add function for calculating quantiles of weighed samples.
  pyro/ops/stats.py
  tests/ops/test_stats.py
Labels: awaiting response

#3342 Type annotate `pyro.nn.dense_nn` and `pyro.nn.auto_reg_nn`
  pyro/nn/auto_reg_nn.py
  pyro/nn/dense_nn.py
Labels: awaiting review

#3336 Enable type checking of the tests folder
  Makefile
  setup.cfg
Labels: awaiting review

#3345 Introducing pyro.infer.predictive.WeighedPredictive which reports weights along with predicted samples
  pyro/infer/__init__.py
  pyro/infer/importance.py
  pyro/infer/predictive.py
  pyro/infer/util.py
  pyro/ops/stats.py
  tests/infer/test_predictive.py
Labels: enhancement, awaiting review

#3349 GCC-8 CI error test
  .github/workflows/ci.yml
Labels: awaiting review

#3351 Add effective sample size analytics to WeighedPredictive results
  pyro/infer/importance.py
  pyro/infer/predictive.py
  tests/infer/test_predictive.py
Labels: awaiting review
